import type { TopicContent } from '../../types'

export const hashTableBasics: TopicContent = {
  id: 'hash-table-basics',
  title: { en: 'Hash Table Patterns', zh: '哈希表模式' },
  description: { en: 'Master 5 patterns: frequency count, two sum, anagrams, sliding window + map, LRU cache', zh: '掌握5种模式：频率计数、两数之和、字谜、滑动窗口+映射、LRU缓存' },
  timeEstimate: '45 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## Why Hash Tables are Powerful",
      "",
      "Hash tables trade space for speed. Instead of searching through n elements (O(n)), you can look up in O(1) average time. The cost: using O(n) extra space to store the hash table.",
      "",
      "Most interviews love hash tables because they're space-efficient optimizations and teach you to think creatively about trading resources.",
      "",
      "## Pattern 1: Frequency Counting",
      "",
      "Count how many times each element appears. Return elements meeting some frequency criteria.",
      "",
      "```javascript",
      "function topKFrequent(nums, k) {",
      "  // Count frequencies",
      "  const count = {}",
      "  for (const num of nums) {",
      "    count[num] = (count[num] || 0) + 1",
      "  }",
      "  ",
      "  // Bucket sort by frequency",
      "  const buckets = Array(nums.length + 1).fill(null).map(() => [])",
      "  for (const [num, freq] of Object.entries(count)) {",
      "    buckets[freq].push(num)",
      "  }",
      "  ",
      "  // Collect top k",
      "  const result = []",
      "  for (let i = buckets.length - 1; i >= 0 && result.length < k; i--) {",
      "    result.push(...buckets[i])",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "The trick: instead of sorting by value, bucket elements by frequency. This is O(n) instead of O(n log n).",
      "",
      "## Pattern 2: Two Sum",
      "",
      "Find two numbers in array that sum to target.",
      "",
      "```javascript",
      "function twoSum(nums, target) {",
      "  const seen = {}",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const complement = target - nums[i]",
      "    if (complement in seen) {",
      "      return [seen[complement], i]",
      "    }",
      "    seen[nums[i]] = i",
      "  }",
      "  return []",
      "}",
      "```",
      "",
      "For each number, check if its complement (target - number) was already seen. Store numbers in a map as you go.",
      "",
      "## Pattern 3: Anagram Detection",
      "",
      "Two strings are anagrams if they contain the same characters with the same frequency.",
      "",
      "```javascript",
      "function isAnagram(s, t) {",
      "  if (s.length !== t.length) return false",
      "  const count = {}",
      "  for (const char of s) {",
      "    count[char] = (count[char] || 0) + 1",
      "  }",
      "  for (const char of t) {",
      "    count[char]--",
      "    if (count[char] < 0) return false",
      "  }",
      "  return true",
      "}",
      "```",
      "",
      "Count frequency in first string. For second string, decrement counters. If any goes negative, not an anagram.",
      "",
      "**Group Anagrams Problem:**",
      "",
      "```javascript",
      "function groupAnagrams(strs) {",
      "  const groups = {}",
      "  for (const str of strs) {",
      "    const key = str.split('').sort().join('')  // Sorted form is the key",
      "    if (!groups[key]) groups[key] = []",
      "    groups[key].push(str)",
      "  }",
      "  return Object.values(groups)",
      "}",
      "```",
      "",
      "All anagrams have the same sorted form. Use sorted form as the map key.",
      "",
      "## Pattern 4: Sliding Window + Map",
      "",
      "Combine sliding window with a hash map for character frequency problems.",
      "",
      "```javascript",
      "function findAnagrams(s, p) {",
      "  const result = []",
      "  const pCount = {}, windowCount = {}",
      "  for (const char of p) pCount[char] = (pCount[char] || 0) + 1",
      "  ",
      "  let matched = 0  // How many characters have matching frequency",
      "  for (let right = 0; right < s.length; right++) {",
      "    const char = s[right]",
      "    windowCount[char] = (windowCount[char] || 0) + 1",
      "    if (windowCount[char] === pCount[char]) matched++",
      "    ",
      "    // Shrink from left",
      "    if (right >= p.length) {",
      "      const leftChar = s[right - p.length]",
      "      if (windowCount[leftChar] === pCount[leftChar]) matched--",
      "      windowCount[leftChar]--",
      "    }",
      "    ",
      "    if (matched === Object.keys(pCount).length) {",
      "      result.push(right - p.length + 1)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "The key optimization: track `matched` count instead of comparing maps each iteration. This is O(n) instead of O(n * alphabet_size).",
      "",
      "## Pattern 5: LRU Cache",
      "",
      "Least Recently Used cache: fixed capacity, evict least recently used item when full.",
      "",
      "```javascript",
      "class LRUCache {",
      "  constructor(capacity) {",
      "    this.capacity = capacity",
      "    this.cache = new Map()  // JavaScript Map maintains insertion order",
      "  }",
      "  ",
      "  get(key) {",
      "    if (!this.cache.has(key)) return -1",
      "    // Move to end (most recently used)",
      "    const value = this.cache.get(key)",
      "    this.cache.delete(key)",
      "    this.cache.set(key, value)",
      "    return value",
      "  }",
      "  ",
      "  put(key, value) {",
      "    if (this.cache.has(key)) {",
      "      this.cache.delete(key)",
      "    } else if (this.cache.size === this.capacity) {",
      "      // Remove least recently used (first element)",
      "      const firstKey = this.cache.keys().next().value",
      "      this.cache.delete(firstKey)",
      "    }",
      "    this.cache.set(key, value)",
      "  }",
      "}",
      "```",
      "",
      "JavaScript Map preserves insertion order. Mark accessed items as most recent by deleting and re-inserting them.",
      "",
      "## Hash Function Basics",
      "",
      "A hash function maps data to fixed-size values. Good properties:",
      "- **Deterministic**: same input always gives same output",
      "- **Uniform**: different inputs map across the full range",
      "- **Fast**: computable in constant time",
      "",
      "Collisions happen when two different inputs hash to the same value. Handling methods:",
      "- **Chaining**: store linked list at each bucket",
      "- **Open addressing**: probe for next empty slot",
      "",
      "## Time Complexity Reality",
      "",
      "Hash table operations are O(1) on average, O(n) worst case (all collisions). In practice, collision-resistant hash functions and resizing make O(1) the norm.",
      "",
      "| Operation | Average | Worst |",
      "|-----------|---------|-------|",
      "| Lookup | O(1) | O(n) |",
      "| Insert | O(1) | O(n) |",
      "| Delete | O(1) | O(n) |",
      "",
      "## Space-Time Tradeoff",
      "",
      "Every hash table problem is fundamentally about trading space for time. Before using a hash table, ask: \"Am I trading enough space to get meaningful speedup?\" Sometimes O(n) space for O(1) lookups is worth it. Sometimes it's not."
    ].join('\n'),
    zh: [
      "## 为什么哈希表强大",
      "",
      "哈希表用空间换速度。与其搜索n个元素（O(n)），你可以用O(1)平均时间查找。代价：使用O(n)额外空间存储哈希表。",
      "",
      "大多数面试喜欢哈希表，因为它们是空间效率优化并教你思考如何交换资源。",
      "",
      "## 模式1：频率计数",
      "",
      "计数每个元素出现多少次。返回满足某些频率标准的元素。",
      "",
      "```javascript",
      "function topKFrequent(nums, k) {",
      "  // 计数频率",
      "  const count = {}",
      "  for (const num of nums) {",
      "    count[num] = (count[num] || 0) + 1",
      "  }",
      "  ",
      "  // 按频率桶排序",
      "  const buckets = Array(nums.length + 1).fill(null).map(() => [])",
      "  for (const [num, freq] of Object.entries(count)) {",
      "    buckets[freq].push(num)",
      "  }",
      "  ",
      "  // 收集前k个",
      "  const result = []",
      "  for (let i = buckets.length - 1; i >= 0 && result.length < k; i--) {",
      "    result.push(...buckets[i])",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "技巧：与其按值排序，不如按频率分桶元素。这是O(n)而不是O(n log n)。",
      "",
      "## 模式2：两数之和",
      "",
      "找数组中两个和为目标的数字。",
      "",
      "```javascript",
      "function twoSum(nums, target) {",
      "  const seen = {}",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const complement = target - nums[i]",
      "    if (complement in seen) {",
      "      return [seen[complement], i]",
      "    }",
      "    seen[nums[i]] = i",
      "  }",
      "  return []",
      "}",
      "```",
      "",
      "对每个数字，检查其补数（目标 - 数字）是否之前见过。当你继续时在映射中存储数字。",
      "",
      "## 模式3：字谜检测",
      "",
      "如果两个字符串包含相同字符且频率相同，它们是字谜。",
      "",
      "```javascript",
      "function isAnagram(s, t) {",
      "  if (s.length !== t.length) return false",
      "  const count = {}",
      "  for (const char of s) {",
      "    count[char] = (count[char] || 0) + 1",
      "  }",
      "  for (const char of t) {",
      "    count[char]--",
      "    if (count[char] < 0) return false",
      "  }",
      "  return true",
      "}",
      "```",
      "",
      "在第一个字符串中计数频率。对于第二个字符串，递减计数器。如果任何一个变为负，不是字谜。",
      "",
      "**分组字谜问题：**",
      "",
      "```javascript",
      "function groupAnagrams(strs) {",
      "  const groups = {}",
      "  for (const str of strs) {",
      "    const key = str.split('').sort().join('')  // 排序形式是键",
      "    if (!groups[key]) groups[key] = []",
      "    groups[key].push(str)",
      "  }",
      "  return Object.values(groups)",
      "}",
      "```",
      "",
      "所有字谜有相同的排序形式。使用排序形式作为映射键。",
      "",
      "## 模式4：滑动窗口 + 映射",
      "",
      "结合滑动窗口和哈希映射用于字符频率问题。",
      "",
      "```javascript",
      "function findAnagrams(s, p) {",
      "  const result = []",
      "  const pCount = {}, windowCount = {}",
      "  for (const char of p) pCount[char] = (pCount[char] || 0) + 1",
      "  ",
      "  let matched = 0  // 多少字符有匹配的频率",
      "  for (let right = 0; right < s.length; right++) {",
      "    const char = s[right]",
      "    windowCount[char] = (windowCount[char] || 0) + 1",
      "    if (windowCount[char] === pCount[char]) matched++",
      "    ",
      "    // 从左收缩",
      "    if (right >= p.length) {",
      "      const leftChar = s[right - p.length]",
      "      if (windowCount[leftChar] === pCount[leftChar]) matched--",
      "      windowCount[leftChar]--",
      "    }",
      "    ",
      "    if (matched === Object.keys(pCount).length) {",
      "      result.push(right - p.length + 1)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "关键优化：追踪`matched`计数而不是每次迭代比较映射。这是O(n)而不是O(n * 字母表大小)。",
      "",
      "## 模式5：LRU缓存",
      "",
      "最近最少使用缓存：固定容量，满时驱逐最少使用的项。",
      "",
      "```javascript",
      "class LRUCache {",
      "  constructor(capacity) {",
      "    this.capacity = capacity",
      "    this.cache = new Map()  // JavaScript Map维护插入顺序",
      "  }",
      "  ",
      "  get(key) {",
      "    if (!this.cache.has(key)) return -1",
      "    // 移到末尾（最近使用）",
      "    const value = this.cache.get(key)",
      "    this.cache.delete(key)",
      "    this.cache.set(key, value)",
      "    return value",
      "  }",
      "  ",
      "  put(key, value) {",
      "    if (this.cache.has(key)) {",
      "      this.cache.delete(key)",
      "    } else if (this.cache.size === this.capacity) {",
      "      // 删除最少使用（第一个元素）",
      "      const firstKey = this.cache.keys().next().value",
      "      this.cache.delete(firstKey)",
      "    }",
      "    this.cache.set(key, value)",
      "  }",
      "}",
      "```",
      "",
      "JavaScript Map保留插入顺序。通过删除并重新插入来标记访问的项为最近。",
      "",
      "## 哈希函数基础",
      "",
      "哈希函数将数据映射到固定大小的值。好的属性：",
      "- **确定性**：相同输入总是给相同输出",
      "- **均匀**：不同输入映射遍历完整范围",
      "- **快速**：在常数时间内可计算",
      "",
      "碰撞发生在两个不同输入哈希到相同值时。处理方法：",
      "- **链式**：在每个桶存储链表",
      "- **开放寻址**：探测下一个空槽",
      "",
      "## 时间复杂度现实",
      "",
      "哈希表操作平均O(1)，最坏O(n)（所有碰撞）。实践上，碰撞抵抗哈希函数和调整大小使O(1)成为常态。",
      "",
      "| 操作 | 平均 | 最坏 |",
      "|------|------|-----|",
      "| 查找 | O(1) | O(n) |",
      "| 插入 | O(1) | O(n) |",
      "| 删除 | O(1) | O(n) |",
      "",
      "## 空间-时间权衡",
      "",
      "每个哈希表问题根本上是关于用空间换时间。使用哈希表前，问自己：「我是否用足够的空间换有意义的加速？」有时O(n)空间以O(1)查找值得。有时不值得。"
    ].join('\n'),
  },
  leetcode: [
    { id: 1, title: 'Two Sum', titleZh: '两数之和', difficulty: 'Easy' },
    { id: 49, title: 'Group Anagrams', titleZh: '字母异位词分组', difficulty: 'Medium' },
    { id: 128, title: 'Longest Consecutive Sequence', titleZh: '最长连续序列', difficulty: 'Medium' },
    { id: 146, title: 'LRU Cache', titleZh: 'LRU缓存', difficulty: 'Medium' },
  ],
}
