import type { TopicContent } from '../../types'

export const stackQueueBasics: TopicContent = {
  id: 'stack-queue-basics',
  title: { en: 'Stack, Queue & Monotonic Stack', zh: '栈、队列与单调栈' },
  description: { en: 'Master LIFO/FIFO basics and the powerful monotonic stack pattern', zh: '掌握LIFO/FIFO基础和强大的单调栈模式' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## Stack: LIFO Last-In-First-Out",
      "",
      "A stack is a list where you add and remove from the same end (the top). Last element added is the first removed. Imagine a stack of plates - you take the top plate, not the bottom one.",
      "",
      "```javascript",
      "class Stack {",
      "  constructor() { this.items = [] }",
      "  push(val) { this.items.push(val) }",
      "  pop() { return this.items.pop() }",
      "  top() { return this.items[this.items.length - 1] }",
      "  isEmpty() { return this.items.length === 0 }",
      "}",
      "```",
      "",
      "**Stack use cases:**",
      "- Parentheses matching (is every `(` paired with `)`?)",
      "- Undo/redo functionality",
      "- Backtracking and DFS",
      "- Expression evaluation",
      "",
      "## Queue: FIFO First-In-First-Out",
      "",
      "A queue is like a line at a store. First person in is served first. Add to the back, remove from the front.",
      "",
      "```javascript",
      "class Queue {",
      "  constructor() { this.items = [] }",
      "  enqueue(val) { this.items.push(val) }",
      "  dequeue() { return this.items.shift() }",
      "  front() { return this.items[0] }",
      "  isEmpty() { return this.items.length === 0 }",
      "}",
      "```",
      "",
      "**Queue use cases:**",
      "- Level-order traversal (BFS)",
      "- Task scheduling",
      "- Print queue",
      "- Message passing",
      "",
      "## Valid Parentheses Pattern",
      "",
      "Classic stack problem: given a string of parentheses, is it valid (every open has a matching close)?",
      "",
      "```javascript",
      "function isValid(s) {",
      "  const stack = []",
      "  const pairs = { '(': ')', '[': ']', '{': '}' }",
      "  for (const char of s) {",
      "    if (char in pairs) {",
      "      stack.push(char)  // Opening bracket",
      "    } else {",
      "      if (!stack.length || pairs[stack.pop()] !== char) {",
      "        return false",
      "      }",
      "    }",
      "  }",
      "  return stack.length === 0",
      "}",
      "```",
      "",
      "For `()[]{}`: push `(`, then see `)`, pop and match ✓. Push `[`, see `]`, match ✓. And so on.",
      "",
      "## Monotonic Stack Pattern",
      "",
      "A **monotonic stack** maintains elements in increasing (or decreasing) order. When you want to add a new element that breaks the order, you pop elements off the stack. This lets you solve \"next greater/smaller element\" problems efficiently.",
      "",
      "**Key insight:** When you pop an element to maintain monotonicity, you've found its next greater element!",
      "",
      "## Next Greater Element",
      "",
      "Given array `[1, 4, 2, 7, 6]`, for each element, find the next element that is greater. Answer: `[4, 7, 7, -1, -1]`.",
      "",
      "Naïve approach: O(n²) - for each element, scan right until finding something greater.",
      "",
      "**Monotonic stack approach O(n):**",
      "",
      "```javascript",
      "function nextGreaterElement(arr) {",
      "  const n = arr.length",
      "  const result = new Array(n).fill(-1)",
      "  const stack = []  // Stack of indices",
      "  ",
      "  for (let i = n - 1; i >= 0; i--) {",
      "    // Pop elements smaller than current",
      "    while (stack.length && arr[stack[stack.length - 1]] < arr[i]) {",
      "      const idx = stack.pop()",
      "      result[idx] = arr[i]",
      "    }",
      "    stack.push(i)",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**How it works for [1, 4, 2, 7, 6]:**",
      "- Start from right (i=4, value 6). Stack is empty, push 4.",
      "- i=3, value 7. arr[4]=6 < 7, pop 4, result[4]=7, push 3.",
      "- i=2, value 2. arr[3]=7 >= 2, push 2.",
      "- i=1, value 4. arr[2]=2 < 4, pop 2, result[2]=4. arr[3]=7 >= 4, push 1.",
      "- i=0, value 1. arr[1]=4 >= 1, push 0.",
      "- Result: [4, 7, 7, -1, -1] ✓",
      "",
      "## Why Monotonic Stack Works",
      "",
      "When you encounter an element greater than the stack top, you know that element is the next greater for all smaller elements you pop. This relationship is found in O(1) per element because each element enters and leaves the stack once.",
      "",
      "## Monotonic Stack for Largest Rectangle in Histogram",
      "",
      "Given histogram heights, find the largest rectangle. Use monotonic stack to find the span of each bar's influence.",
      "",
      "```javascript",
      "function largestRectangle(heights) {",
      "  const stack = []",
      "  let maxArea = 0",
      "  for (let i = 0; i < heights.length; i++) {",
      "    while (stack.length && heights[stack[stack.length - 1]] > heights[i]) {",
      "      const h = heights[stack.pop()]",
      "      const w = stack.length ? i - stack[stack.length - 1] - 1 : i",
      "      maxArea = Math.max(maxArea, h * w)",
      "    }",
      "    stack.push(i)",
      "  }",
      "  while (stack.length) {",
      "    const h = heights[stack.pop()]",
      "    const w = stack.length ? heights.length - stack[stack.length - 1] - 1 : heights.length",
      "    maxArea = Math.max(maxArea, h * w)",
      "  }",
      "  return maxArea",
      "}",
      "```",
      "",
      "The monotonic stack tracks increasing heights. When you find a smaller height, the previous bars can no longer extend. Calculate the rectangle those bars form.",
      "",
      "## Stack vs Queue Comparison",
      "",
      "| Feature | Stack | Queue |",
      "|---------|-------|-------|",
      "| Order | LIFO | FIFO |",
      "| Add | O(1) top | O(1) back |",
      "| Remove | O(1) top | O(1) front |",
      "| Use case | Undo, DFS, parentheses | BFS, scheduling |",
      "| Monotonic variant | Monotonic stack | Monotonic deque |"
    ].join('\n'),
    zh: [
      "## 栈：LIFO后进先出",
      "",
      "栈是一个从同一端（顶部）添加和删除的列表。最后添加的元素第一个被删除。想象一堆盘子 - 你拿顶部的盘子，不是底部的。",
      "",
      "```javascript",
      "class Stack {",
      "  constructor() { this.items = [] }",
      "  push(val) { this.items.push(val) }",
      "  pop() { return this.items.pop() }",
      "  top() { return this.items[this.items.length - 1] }",
      "  isEmpty() { return this.items.length === 0 }",
      "}",
      "```",
      "",
      "**栈用例：**",
      "- 括号匹配（是否每个`(`都与`)`配对？）",
      "- 撤销/重做功能",
      "- 回溯和DFS",
      "- 表达式求值",
      "",
      "## 队列：FIFO先进先出",
      "",
      "队列就像商店排队。第一个进来的人先被服务。从后面添加，从前面移除。",
      "",
      "```javascript",
      "class Queue {",
      "  constructor() { this.items = [] }",
      "  enqueue(val) { this.items.push(val) }",
      "  dequeue() { return this.items.shift() }",
      "  front() { return this.items[0] }",
      "  isEmpty() { return this.items.length === 0 }",
      "}",
      "```",
      "",
      "**队列用例：**",
      "- 层序遍历（BFS）",
      "- 任务调度",
      "- 打印队列",
      "- 消息传递",
      "",
      "## 有效括号模式",
      "",
      "经典栈问题：给定括号字符串，是否有效（每个开放都有匹配的关闭）？",
      "",
      "```javascript",
      "function isValid(s) {",
      "  const stack = []",
      "  const pairs = { '(': ')', '[': ']', '{': '}' }",
      "  for (const char of s) {",
      "    if (char in pairs) {",
      "      stack.push(char)  // 开括号",
      "    } else {",
      "      if (!stack.length || pairs[stack.pop()] !== char) {",
      "        return false",
      "      }",
      "    }",
      "  }",
      "  return stack.length === 0",
      "}",
      "```",
      "",
      "对于`()[]{}`: push `(`，然后看`)`, pop并匹配 ✓。Push `[`，看`]`，匹配 ✓。以此类推。",
      "",
      "## 单调栈模式",
      "",
      "**单调栈**维护元素按递增（或递减）顺序。当添加新元素破坏顺序时，从栈中弹出元素。这让你有效解决「下一个更大/更小元素」问题。",
      "",
      "**关键洞察：** 当弹出元素以维护单调性时，你找到了它的下一个更大元素！",
      "",
      "## 下一个更大元素",
      "",
      "给定数组`[1, 4, 2, 7, 6]`，对每个元素，找下一个更大的元素。答案：`[4, 7, 7, -1, -1]`。",
      "",
      "幼稚方法：O(n²) - 对每个元素，从右扫描直到找到更大的。",
      "",
      "**单调栈方法O(n):**",
      "",
      "```javascript",
      "function nextGreaterElement(arr) {",
      "  const n = arr.length",
      "  const result = new Array(n).fill(-1)",
      "  const stack = []  // 索引的栈",
      "  ",
      "  for (let i = n - 1; i >= 0; i--) {",
      "    // 弹出小于当前的元素",
      "    while (stack.length && arr[stack[stack.length - 1]] < arr[i]) {",
      "      const idx = stack.pop()",
      "      result[idx] = arr[i]",
      "    }",
      "    stack.push(i)",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**对[1, 4, 2, 7, 6]的工作方式：**",
      "- 从右开始(i=4, 值6)。栈为空，push 4。",
      "- i=3, 值7。arr[4]=6 < 7，pop 4，result[4]=7，push 3。",
      "- i=2, 值2。arr[3]=7 >= 2，push 2。",
      "- i=1, 值4。arr[2]=2 < 4，pop 2，result[2]=4。arr[3]=7 >= 4，push 1。",
      "- i=0, 值1。arr[1]=4 >= 1，push 0。",
      "- 结果：[4, 7, 7, -1, -1] ✓",
      "",
      "## 为什么单调栈有效",
      "",
      "当遇到大于栈顶的元素时，你知道该元素是所有弹出的较小元素的下一个更大值。这个关系在O(1)每个元素中找到，因为每个元素进入和离开栈一次。",
      "",
      "## 用于直方图中最大矩形的单调栈",
      "",
      "给定直方图高度，找最大矩形。使用单调栈找每个条的影响范围。",
      "",
      "```javascript",
      "function largestRectangle(heights) {",
      "  const stack = []",
      "  let maxArea = 0",
      "  for (let i = 0; i < heights.length; i++) {",
      "    while (stack.length && heights[stack[stack.length - 1]] > heights[i]) {",
      "      const h = heights[stack.pop()]",
      "      const w = stack.length ? i - stack[stack.length - 1] - 1 : i",
      "      maxArea = Math.max(maxArea, h * w)",
      "    }",
      "    stack.push(i)",
      "  }",
      "  while (stack.length) {",
      "    const h = heights[stack.pop()]",
      "    const w = stack.length ? heights.length - stack[stack.length - 1] - 1 : heights.length",
      "    maxArea = Math.max(maxArea, h * w)",
      "  }",
      "  return maxArea",
      "}",
      "```",
      "",
      "单调栈追踪递增的高度。当找到较小的高度时，之前的条无法再扩展。计算这些条形成的矩形。",
      "",
      "## 栈vs队列比较",
      "",
      "| 特征 | 栈 | 队列 |",
      "|------|------|------|",
      "| 顺序 | LIFO | FIFO |",
      "| 添加 | O(1)顶 | O(1)后 |",
      "| 删除 | O(1)顶 | O(1)前 |",
      "| 用例 | 撤销, DFS, 括号 | BFS, 调度 |",
      "| 单调变体 | 单调栈 | 单调双端队列 |"
    ].join('\n'),
  },
  leetcode: [
    { id: 20, title: 'Valid Parentheses', titleZh: '有效的括号', difficulty: 'Easy' },
    { id: 739, title: 'Daily Temperatures', titleZh: '每日温度', difficulty: 'Medium' },
    { id: 496, title: 'Next Greater Element I', titleZh: '下一个更大元素 I', difficulty: 'Easy' },
    { id: 84, title: 'Largest Rectangle in Histogram', titleZh: '柱状图中最大的矩形', difficulty: 'Hard' },
  ],
}
