import type { TopicContent } from '../../types'

export const graphBasicsContent: TopicContent = {
  id: 'graphs-basics',
  title: { en: 'Graph Basics & DFS/BFS', zh: '图的基础与DFS/BFS' },
  description: { en: 'Master adjacency list/matrix, directed/undirected graphs, and traversal patterns', zh: '掌握邻接表/矩阵、有向/无向图和遍历模式' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## Graph Representations",
      "",
      "A graph is a collection of nodes (vertices) and edges connecting them. Two main representations:",
      "",
      "### Adjacency List (Most Common)",
      "",
      "Store a list of neighbors for each node.",
      "",
      "```javascript",
      "const graph = {",
      "  0: [1, 2],",
      "  1: [0, 3],",
      "  2: [0, 3],",
      "  3: [1, 2]",
      "}",
      "```",
      "",
      "**Pros**: Space O(V + E), cache friendly, easier to code",
      "",
      "**Cons**: Checking if edge exists is O(degree)",
      "",
      "### Adjacency Matrix (Less Common)",
      "",
      "2D array where matrix[i][j] = 1 if edge exists, 0 otherwise.",
      "",
      "```javascript",
      "const matrix = [",
      "  [0, 1, 1, 0],  // node 0 connects to 1, 2",
      "  [1, 0, 0, 1],  // node 1 connects to 0, 3",
      "  [1, 0, 0, 1],  // node 2 connects to 0, 3",
      "  [0, 1, 1, 0]   // node 3 connects to 1, 2",
      "]",
      "```",
      "",
      "**Pros**: Check edge existence in O(1), works for dense graphs",
      "",
      "**Cons**: Space O(V²) even for sparse graphs",
      "",
      "## Directed vs Undirected",
      "",
      "**Directed Graph**: Edges have direction (A → B doesn't imply B → A)",
      "```",
      "1 → 2",
      "3 → 1",
      "```",
      "",
      "**Undirected Graph**: Edges are bidirectional (A-B means both A→B and B→A)",
      "```",
      "1 - 2",
      "3 - 1",
      "```",
      "",
      "In adjacency list, directed graphs only store one direction. Undirected graphs store both.",
      "",
      "## DFS: Depth-First Search",
      "",
      "Explore as far as possible before backtracking. Uses stack (recursion or explicit).",
      "",
      "```javascript",
      "function dfs(graph, start) {",
      "  const visited = new Set()",
      "  const result = []",
      "  ",
      "  function explore(node) {",
      "    if (visited.has(node)) return",
      "    visited.add(node)",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      explore(neighbor)",
      "    }",
      "  }",
      "  ",
      "  explore(start)",
      "  return result",
      "}",
      "```",
      "",
      "**Iterative DFS:**",
      "```javascript",
      "function dfsIterative(graph, start) {",
      "  const visited = new Set()",
      "  const stack = [start]",
      "  const result = []",
      "  ",
      "  while (stack.length) {",
      "    const node = stack.pop()",
      "    if (visited.has(node)) continue",
      "    visited.add(node)",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        stack.push(neighbor)",
      "      }",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## BFS: Breadth-First Search",
      "",
      "Explore level by level. Uses queue.",
      "",
      "```javascript",
      "function bfs(graph, start) {",
      "  const visited = new Set([start])",
      "  const queue = [start]",
      "  const result = []",
      "  ",
      "  while (queue.length) {",
      "    const node = queue.shift()",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        visited.add(neighbor)",
      "        queue.push(neighbor)",
      "      }",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## DFS vs BFS",
      "",
      "| Property | DFS | BFS |",
      "|----------|-----|-----|",
      "| Memory | Potentially large (deep trees) | More uniform |",
      "| Discovery order | Deep-first | Level-by-level |",
      "| Best for | Cycles, topological sort | Shortest path, connected components |",
      "| Time | O(V + E) | O(V + E) |",
      "| Space | O(h) for recursion, O(V) for visited | O(w) queue, O(V) for visited |",
      "",
      "## Connected Components",
      "",
      "Find all separate groups of connected nodes.",
      "",
      "```javascript",
      "function countComponents(graph) {",
      "  const visited = new Set()",
      "  let count = 0",
      "  ",
      "  function dfs(node) {",
      "    visited.add(node)",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) dfs(neighbor)",
      "    }",
      "  }",
      "  ",
      "  for (const node in graph) {",
      "    if (!visited.has(node)) {",
      "      dfs(node)",
      "      count++",
      "    }",
      "  }",
      "  return count",
      "}",
      "```",
      "",
      "Run DFS from each unvisited node. Each DFS explores one component.",
      "",
      "## Cycle Detection",
      "",
      "Detect if graph has a cycle.",
      "",
      "**For undirected graphs:**",
      "```javascript",
      "function hasCycle(graph, n) {",
      "  const visited = new Set()",
      "  ",
      "  function dfs(node, parent) {",
      "    visited.add(node)",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        if (dfs(neighbor, node)) return true",
      "      } else if (neighbor !== parent) {",
      "        return true  // Back edge found",
      "      }",
      "    }",
      "    return false",
      "  }",
      "  ",
      "  for (let i = 0; i < n; i++) {",
      "    if (!visited.has(i) && dfs(i, -1)) return true",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "Key: If we visit a node that's already visited and it's not our parent, we've found a cycle.",
      "",
      "## Time Complexity",
      "",
      "Both DFS and BFS have the same complexity:",
      "- **Time**: O(V + E) - visit each vertex once, traverse each edge once",
      "- **Space**: O(V) for visited set + O(V) for recursion stack (DFS) or queue (BFS)"
    ].join('\n'),
    zh: [
      "## 图的表示",
      "",
      "图是节点（顶点）及连接它们的边的集合。两种主要表示：",
      "",
      "### 邻接表（最常见）",
      "",
      "为每个节点存储邻居列表。",
      "",
      "```javascript",
      "const graph = {",
      "  0: [1, 2],",
      "  1: [0, 3],",
      "  2: [0, 3],",
      "  3: [1, 2]",
      "}",
      "```",
      "",
      "**优点**：空间O(V + E)，缓存友好，更容易编码",
      "",
      "**缺点**：检查边是否存在是O(度）",
      "",
      "### 邻接矩阵（较不常见）",
      "",
      "2D数组，其中matrix[i][j] = 1如果边存在，否则0。",
      "",
      "```javascript",
      "const matrix = [",
      "  [0, 1, 1, 0],  // 节点0连接到1, 2",
      "  [1, 0, 0, 1],  // 节点1连接到0, 3",
      "  [1, 0, 0, 1],  // 节点2连接到0, 3",
      "  [0, 1, 1, 0]   // 节点3连接到1, 2",
      "]",
      "```",
      "",
      "**优点**：检查边存在O(1)，适用于稠密图",
      "",
      "**缺点**：空间O(V²)即使对于稀疏图",
      "",
      "## 有向vs无向",
      "",
      "**有向图**：边有方向（A → B不意味着B → A）",
      "```",
      "1 → 2",
      "3 → 1",
      "```",
      "",
      "**无向图**：边是双向的（A-B意味着A→B和B→A）",
      "```",
      "1 - 2",
      "3 - 1",
      "```",
      "",
      "在邻接表中，有向图仅存储一个方向。无向图存储两个。",
      "",
      "## DFS：深度优先搜索",
      "",
      "尽可能远地探索，然后回溯。使用栈（递归或显式）。",
      "",
      "```javascript",
      "function dfs(graph, start) {",
      "  const visited = new Set()",
      "  const result = []",
      "  ",
      "  function explore(node) {",
      "    if (visited.has(node)) return",
      "    visited.add(node)",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      explore(neighbor)",
      "    }",
      "  }",
      "  ",
      "  explore(start)",
      "  return result",
      "}",
      "```",
      "",
      "**迭代DFS：**",
      "```javascript",
      "function dfsIterative(graph, start) {",
      "  const visited = new Set()",
      "  const stack = [start]",
      "  const result = []",
      "  ",
      "  while (stack.length) {",
      "    const node = stack.pop()",
      "    if (visited.has(node)) continue",
      "    visited.add(node)",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        stack.push(neighbor)",
      "      }",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## BFS：广度优先搜索",
      "",
      "逐层探索。使用队列。",
      "",
      "```javascript",
      "function bfs(graph, start) {",
      "  const visited = new Set([start])",
      "  const queue = [start]",
      "  const result = []",
      "  ",
      "  while (queue.length) {",
      "    const node = queue.shift()",
      "    result.push(node)",
      "    ",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        visited.add(neighbor)",
      "        queue.push(neighbor)",
      "      }",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## DFS vs BFS",
      "",
      "| 属性 | DFS | BFS |",
      "|------|-----|-----|",
      "| 内存 | 潜在大（深树） | 更均匀 |",
      "| 发现顺序 | 深优先 | 逐层 |",
      "| 最佳用途 | 循环，拓扑排序 | 最短路径，连通分量 |",
      "| 时间 | O(V + E) | O(V + E) |",
      "| 空间 | O(h)递归，O(V)已访问 | O(w)队列，O(V)已访问 |",
      "",
      "## 连通分量",
      "",
      "找到所有连通节点的独立组。",
      "",
      "```javascript",
      "function countComponents(graph) {",
      "  const visited = new Set()",
      "  let count = 0",
      "  ",
      "  function dfs(node) {",
      "    visited.add(node)",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) dfs(neighbor)",
      "    }",
      "  }",
      "  ",
      "  for (const node in graph) {",
      "    if (!visited.has(node)) {",
      "      dfs(node)",
      "      count++",
      "    }",
      "  }",
      "  return count",
      "}",
      "```",
      "",
      "从每个未访问的节点运行DFS。每个DFS探索一个分量。",
      "",
      "## 循环检测",
      "",
      "检测图是否有循环。",
      "",
      "**对于无向图：**",
      "```javascript",
      "function hasCycle(graph, n) {",
      "  const visited = new Set()",
      "  ",
      "  function dfs(node, parent) {",
      "    visited.add(node)",
      "    for (const neighbor of graph[node]) {",
      "      if (!visited.has(neighbor)) {",
      "        if (dfs(neighbor, node)) return true",
      "      } else if (neighbor !== parent) {",
      "        return true  // 找到回边",
      "      }",
      "    }",
      "    return false",
      "  }",
      "  ",
      "  for (let i = 0; i < n; i++) {",
      "    if (!visited.has(i) && dfs(i, -1)) return true",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "关键：如果我们访问已访问的节点且它不是我们的父，我们找到了循环。",
      "",
      "## 时间复杂度",
      "",
      "DFS和BFS有相同的复杂度：",
      "- **时间**：O(V + E) - 访问每个顶点一次，遍历每条边一次",
      "- **空间**：O(V)已访问集合 + O(V)递归栈（DFS）或队列（BFS）"
    ].join('\n'),
  },
  leetcode: [
    { id: 200, title: 'Number of Islands', titleZh: '岛屿数量', difficulty: 'Medium' },
    { id: 133, title: 'Clone Graph', titleZh: '克隆图', difficulty: 'Medium' },
    { id: 207, title: 'Course Schedule', titleZh: '课程表', difficulty: 'Medium' },
  ],
}
