import type { TopicContent } from '../../types'

export const unionFindContent: TopicContent = {
  id: 'graphs-union-find',
  title: { en: 'Union-Find (Disjoint Set Union)', zh: '并查集（DSU）' },
  description: { en: 'Master union-find data structure with path compression and union by rank', zh: '掌握带路径压缩和按秩合并的并查集数据结构' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## Union-Find Overview",
      "",
      "Union-Find (or Disjoint Set Union) is a data structure that efficiently tracks and merges equivalence classes. Perfect for connectivity and cycle detection problems.",
      "",
      "**Core operations:**",
      "- `find(x)`: Which set does x belong to? (Find the root/representative)",
      "- `union(x, y)`: Merge the sets containing x and y",
      "- Both operations: O(α(n)) ≈ O(1) with optimizations",
      "",
      "## Basic Union-Find Implementation",
      "",
      "```javascript",
      "class UnionFind {",
      "  constructor(n) {",
      "    this.parent = Array.from({length: n}, (_, i) => i)",
      "    this.rank = Array(n).fill(0)",
      "  }",
      "  ",
      "  find(x) {",
      "    if (this.parent[x] !== x) {",
      "      this.parent[x] = this.find(this.parent[x])  // Path compression",
      "    }",
      "    return this.parent[x]",
      "  }",
      "  ",
      "  union(x, y) {",
      "    const rootX = this.find(x)",
      "    const rootY = this.find(y)",
      "    if (rootX === rootY) return false  // Already in same set",
      "    ",
      "    // Union by rank",
      "    if (this.rank[rootX] < this.rank[rootY]) {",
      "      this.parent[rootX] = rootY",
      "    } else if (this.rank[rootX] > this.rank[rootY]) {",
      "      this.parent[rootY] = rootX",
      "    } else {",
      "      this.parent[rootY] = rootX",
      "      this.rank[rootX]++",
      "    }",
      "    return true",
      "  }",
      "}",
      "```",
      "",
      "## Path Compression",
      "",
      "When finding the root, make every node point directly to the root. This flattens the tree, making future operations faster.",
      "",
      "```",
      "Before: 4 → 3 → 2 → 1 (long path)",
      "After:  4 → 1, 3 → 1, 2 → 1 (flattened)",
      "```",
      "",
      "Each find now traverses fewer nodes. This is the key to near-constant time operations.",
      "",
      "## Union by Rank",
      "",
      "When merging two sets, attach the smaller tree under the larger tree. This keeps the tree shallow.",
      "",
      "Without union by rank: Union on worst case creates a chain (O(n) find).",
      "With union by rank: Always keeps depth ~log(n) (O(log n) find, O(1) with compression).",
      "",
      "## Cycle Detection in Undirected Graphs",
      "",
      "If adding an edge would connect two nodes that are already in the same set, adding that edge would create a cycle.",
      "",
      "```javascript",
      "function hasCycle(edges, n) {",
      "  const uf = new UnionFind(n)",
      "  for (const [u, v] of edges) {",
      "    if (uf.find(u) === uf.find(v)) {",
      "      return true  // u and v already connected, edge creates cycle",
      "    }",
      "    uf.union(u, v)",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "## Connected Components",
      "",
      "Count distinct groups.",
      "",
      "```javascript",
      "function countComponents(n, edges) {",
      "  const uf = new UnionFind(n)",
      "  for (const [u, v] of edges) {",
      "    uf.union(u, v)",
      "  }",
      "  ",
      "  const roots = new Set()",
      "  for (let i = 0; i < n; i++) {",
      "    roots.add(uf.find(i))",
      "  }",
      "  return roots.size",
      "}",
      "```",
      "",
      "## Minimum Cost to Connect Points",
      "",
      "Connect all points with minimum total cost (essentially Kruskal's algorithm).",
      "",
      "```javascript",
      "function minCostToConnectPoints(points) {",
      "  // Build all edges with distances",
      "  const edges = []",
      "  for (let i = 0; i < points.length; i++) {",
      "    for (let j = i + 1; j < points.length; j++) {",
      "      const dist = Math.abs(points[i][0] - points[j][0]) +",
      "                   Math.abs(points[i][1] - points[j][1])",
      "      edges.push([dist, i, j])",
      "    }",
      "  }",
      "  ",
      "  // Sort by distance",
      "  edges.sort((a, b) => a[0] - b[0])",
      "  ",
      "  // Greedily add edges",
      "  const uf = new UnionFind(points.length)",
      "  let cost = 0",
      "  let edgesAdded = 0",
      "  for (const [dist, u, v] of edges) {",
      "    if (uf.find(u) !== uf.find(v)) {",
      "      uf.union(u, v)",
      "      cost += dist",
      "      edgesAdded++",
      "      if (edgesAdded === points.length - 1) break",
      "    }",
      "  }",
      "  return cost",
      "}",
      "```",
      "",
      "## Union-Find vs DFS/BFS",
      "",
      "| Problem | Union-Find | DFS/BFS |",
      "|---------|-----------|---------|",
      "| Cycle detection | ✅ Efficient | ✅ Works |",
      "| Connected components | ✅ Clean | ✅ Works |",
      "| Find path between nodes | ❌ Doesn't track paths | ✅ Tracks paths |",
      "| Minimum spanning tree | ✅ Natural fit | ❌ Less natural |",
      "| Online connectivity | ✅ Incremental | ❌ Requires full graph |",
      "",
      "## Time Complexity",
      "",
      "With both path compression and union by rank:",
      "- **Find**: O(α(n)) ≈ O(1) in practice",
      "- **Union**: O(α(n)) ≈ O(1) in practice",
      "- **α(n)**: Inverse Ackermann function, practically never exceeds 4 for any realistic input",
      "",
      "## When to Use Union-Find",
      "",
      "- Connectivity queries (are x and y in same component?)",
      "- Cycle detection",
      "- Minimum spanning trees (Kruskal's algorithm)",
      "- Equivalence classes",
      "- Online union-find where graph is built incrementally",
      "",
      "Avoid for problems where you need to track actual paths between nodes - use DFS/BFS instead."
    ].join('\n'),
    zh: [
      "## 并查集概述",
      "",
      "并查集（或不相交集合并）是有效追踪和合并等价类的数据结构。对于连通性和循环检测问题完美。",
      "",
      "**核心操作：**",
      "- `find(x)`：x属于哪个集合？（找到根/代表）",
      "- `union(x, y)`：合并包含x和y的集合",
      "- 两个操作：带优化O(α(n)) ≈ O(1)",
      "",
      "## 基本并查集实现",
      "",
      "```javascript",
      "class UnionFind {",
      "  constructor(n) {",
      "    this.parent = Array.from({length: n}, (_, i) => i)",
      "    this.rank = Array(n).fill(0)",
      "  }",
      "  ",
      "  find(x) {",
      "    if (this.parent[x] !== x) {",
      "      this.parent[x] = this.find(this.parent[x])  // 路径压缩",
      "    }",
      "    return this.parent[x]",
      "  }",
      "  ",
      "  union(x, y) {",
      "    const rootX = this.find(x)",
      "    const rootY = this.find(y)",
      "    if (rootX === rootY) return false  // 已在同一集合",
      "    ",
      "    // 按秩合并",
      "    if (this.rank[rootX] < this.rank[rootY]) {",
      "      this.parent[rootX] = rootY",
      "    } else if (this.rank[rootX] > this.rank[rootY]) {",
      "      this.parent[rootY] = rootX",
      "    } else {",
      "      this.parent[rootY] = rootX",
      "      this.rank[rootX]++",
      "    }",
      "    return true",
      "  }",
      "}",
      "```",
      "",
      "## 路径压缩",
      "",
      "找根时，让每个节点直接指向根。这压缩了树，使未来操作更快。",
      "",
      "```",
      "之前：4 → 3 → 2 → 1（长路径）",
      "之后：4 → 1, 3 → 1, 2 → 1（压缩）",
      "```",
      "",
      "每个find现在遍历更少节点。这是近乎常数时间操作的关键。",
      "",
      "## 按秩合并",
      "",
      "合并两个集合时，在较大树下附加较小树。这保持树浅。",
      "",
      "没有按秩合并：最坏情况union创建链（O(n) find）。",
      "有按秩合并：始终保持深度~log(n)（O(log n) find，O(1)带压缩）。",
      "",
      "## 无向图中的循环检测",
      "",
      "如果添加边会连接两个已在同一集合中的节点，添加该边会创建循环。",
      "",
      "```javascript",
      "function hasCycle(edges, n) {",
      "  const uf = new UnionFind(n)",
      "  for (const [u, v] of edges) {",
      "    if (uf.find(u) === uf.find(v)) {",
      "      return true  // u和v已连接，边创建循环",
      "    }",
      "    uf.union(u, v)",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "## 连通分量",
      "",
      "计数不同的组。",
      "",
      "```javascript",
      "function countComponents(n, edges) {",
      "  const uf = new UnionFind(n)",
      "  for (const [u, v] of edges) {",
      "    uf.union(u, v)",
      "  }",
      "  ",
      "  const roots = new Set()",
      "  for (let i = 0; i < n; i++) {",
      "    roots.add(uf.find(i))",
      "  }",
      "  return roots.size",
      "}",
      "```",
      "",
      "## 连接点的最小成本",
      "",
      "用最小总成本连接所有点（本质上是Kruskal算法）。",
      "",
      "```javascript",
      "function minCostToConnectPoints(points) {",
      "  // 用距离构建所有边",
      "  const edges = []",
      "  for (let i = 0; i < points.length; i++) {",
      "    for (let j = i + 1; j < points.length; j++) {",
      "      const dist = Math.abs(points[i][0] - points[j][0]) +",
      "                   Math.abs(points[i][1] - points[j][1])",
      "      edges.push([dist, i, j])",
      "    }",
      "  }",
      "  ",
      "  // 按距离排序",
      "  edges.sort((a, b) => a[0] - b[0])",
      "  ",
      "  // 贪心添加边",
      "  const uf = new UnionFind(points.length)",
      "  let cost = 0",
      "  let edgesAdded = 0",
      "  for (const [dist, u, v] of edges) {",
      "    if (uf.find(u) !== uf.find(v)) {",
      "      uf.union(u, v)",
      "      cost += dist",
      "      edgesAdded++",
      "      if (edgesAdded === points.length - 1) break",
      "    }",
      "  }",
      "  return cost",
      "}",
      "```",
      "",
      "## 并查集vs DFS/BFS",
      "",
      "| 问题 | 并查集 | DFS/BFS |",
      "|------|---------|----------|",
      "| 循环检测 | ✅有效 | ✅有效 |",
      "| 连通分量 | ✅干净 | ✅有效 |",
      "| 找节点间路径 | ❌不追踪路径 | ✅追踪路径 |",
      "| 最小生成树 | ✅自然 | ❌不自然 |",
      "| 在线连通性 | ✅增量式 | ❌需完整图 |",
      "",
      "## 时间复杂度",
      "",
      "带路径压缩和按秩合并：",
      "- **Find**：O(α(n)) ≈ O(1)实际上",
      "- **Union**：O(α(n)) ≈ O(1)实际上",
      "- **α(n)**：逆Ackermann函数，实际上对任何现实输入永不超过4",
      "",
      "## 何时使用并查集",
      "",
      "- 连通性查询（x和y在同一分量中吗？）",
      "- 循环检测",
      "- 最小生成树（Kruskal算法）",
      "- 等价类",
      "- 在线并查集，其中图增量构建",
      "",
      "避免需要追踪节点间实际路径的问题 - 使用DFS/BFS代替。"
    ].join('\n'),
  },
  leetcode: [
    { id: 547, title: 'Number of Provinces', titleZh: '省份数量', difficulty: 'Medium' },
    { id: 684, title: 'Redundant Connection', titleZh: '冗余连接', difficulty: 'Medium' },
    { id: 1584, title: 'Min Cost to Connect All Points', titleZh: '连接所有点的最小费用', difficulty: 'Medium' },
  ],
}
