import type { TopicContent } from '../../types'

export const fibonacciContent: TopicContent = {
  id: 'dp-fibonacci',
  title: { en: 'Fibonacci & Coin Change', zh: 'Fibonacci与硬币兑换' },
  description: { en: 'Journey from O(2^n) to O(1) with Fibonacci. Then master Coin Change as canonical DP template.', zh: '用Fibonacci从O(2^n)优化到O(1)。然后掌握硬币兑换作为规范DP模板。' },
  timeEstimate: '45 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'fibonacci',
  content: {
    en: [
      "## The Fibonacci Journey: From Exponential to Constant",
      "",
      "Fibonacci perfectly illustrates how DP optimizes from terrible to great.",
      "",
      "### Step 1: Naive Recursion - O(2^n)",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  return fib(n - 1) + fib(n - 2)",
      "}",
      "```",
      "",
      "**Problem:** fib(5) calls fib(4) and fib(3). fib(4) calls fib(3) and fib(2). So fib(3) is computed twice. This redundancy explodes exponentially.",
      "",
      "For fib(50), we'd be doing quintillions of operations. Completely impractical.",
      "",
      "### Step 2: Memoization - O(n)",
      "",
      "Cache results to avoid recomputation.",
      "",
      "```javascript",
      "function fib(n, memo = {}) {",
      "  if (n in memo) return memo[n]",
      "  if (n <= 1) return n",
      "  memo[n] = fib(n - 1, memo) + fib(n - 2, memo)",
      "  return memo[n]",
      "}",
      "```",
      "",
      "**Key:** First time we compute fib(3), we store it. Next time, we return the stored value instantly.",
      "",
      "Now fib(50) is just 50 recursive calls (one per unique state), each O(1).",
      "",
      "**Time:** O(n)",
      "**Space:** O(n) for memo + O(n) for call stack",
      "",
      "### Step 3: Tabulation - O(n) time, O(n) space",
      "",
      "Build table iteratively instead of recursively.",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  const dp = [0, 1]",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "**Cleaner than memoization:** No recursion overhead, clearer logic.",
      "",
      "### Step 4: Space Optimization - O(n) time, O(1) space",
      "",
      "Notice we only need the last two values. Keep a rolling window.",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  let prev2 = 0, prev1 = 1",
      "  for (let i = 2; i <= n; i++) {",
      "    const current = prev1 + prev2",
      "    prev2 = prev1",
      "    prev1 = current",
      "  }",
      "  return prev1",
      "}",
      "```",
      "",
      "**The journey:** O(2^n) → O(n) → O(n) time, O(1) space. Fibonacci becomes instant for any n.",
      "",
      "## Coin Change: Canonical DP Problem",
      "",
      "**Problem:** Given coins [1, 2, 5] and amount 5, find minimum number of coins to make the amount.",
      "",
      "Answer for amount 5: [5] (1 coin) or [2, 2, 1] (3 coins). Minimum is 1.",
      "",
      "### Define State Clearly",
      "",
      "`dp[i]` = minimum number of coins to make amount i",
      "",
      "### Transition",
      "",
      "To make amount i, we can use any coin c, then solve for (i - c). Add 1 for the coin we used.",
      "",
      "`dp[i] = 1 + min(dp[i - coin] for all coins)`",
      "",
      "### Code",
      "",
      "```javascript",
      "function coinChange(coins, amount) {",
      "  const dp = Array(amount + 1).fill(Infinity)",
      "  dp[0] = 0  // Base case: 0 coins for amount 0",
      "  ",
      "  for (let i = 1; i <= amount; i++) {",
      "    for (const coin of coins) {",
      "      if (coin <= i) {",
      "        dp[i] = Math.min(dp[i], dp[i - coin] + 1)",
      "      }",
      "    }",
      "  }",
      "  return dp[amount] === Infinity ? -1 : dp[amount]",
      "}",
      "```",
      "",
      "**Walk through for coins=[1,2,5], amount=5:**",
      "- dp[0] = 0",
      "- dp[1] = min(dp[0] + 1) = 1  (use coin 1)",
      "- dp[2] = min(dp[1] + 1, dp[0] + 1) = 1  (use coin 2)",
      "- dp[3] = min(dp[2] + 1, dp[1] + 1) = 2  (use coin 2 then 1, or coin 1 three times)",
      "- dp[4] = min(dp[3] + 1, dp[2] + 1) = 2  (use coin 2 twice)",
      "- dp[5] = min(dp[4] + 1, dp[3] + 1, dp[0] + 1) = 1  (use coin 5)",
      "",
      "**Time:** O(amount × coins)",
      "**Space:** O(amount)",
      "",
      "## Why Coin Change is Canonical",
      "",
      "The structure teaches everything about DP:",
      "1. **Clear state:** dp[i] = answer for subproblem of size i",
      "2. **Clear transition:** Try all choices (coins), pick best",
      "3. **Base case:** dp[0] = 0 (empty amount needs 0 coins)",
      "4. **Building up:** Solve small amounts before large amounts",
      "",
      "Master this pattern, apply it everywhere: climbing stairs, house robber, longest palindrome, edit distance, etc.",
      "",
      "## Variation: Coin Change II (Count Ways)",
      "",
      "How many ways to make amount 5 with coins [1, 2, 5]?",
      "",
      "`dp[i]` = number of ways to make amount i",
      "",
      "```javascript",
      "function change(amount, coins) {",
      "  const dp = Array(amount + 1).fill(0)",
      "  dp[0] = 1  // One way: use no coins",
      "  ",
      "  for (const coin of coins) {",
      "    for (let i = coin; i <= amount; i++) {",
      "      dp[i] += dp[i - coin]",
      "    }",
      "  }",
      "  return dp[amount]",
      "}",
      "```",
      "",
      "**Key difference:** Iterate coins in outer loop (avoid counting same combination multiple times). Add instead of taking minimum."
    ].join('\n'),
    zh: [
      "## Fibonacci旅程：从指数到常数",
      "",
      "Fibonacci完美说明DP如何从可怕优化到伟大。",
      "",
      "### 第1步：幼稚递归 - O(2^n)",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  return fib(n - 1) + fib(n - 2)",
      "}",
      "```",
      "",
      "**问题：**fib(5)调用fib(4)和fib(3)。fib(4)调用fib(3)和fib(2)。所以fib(3)计算两次。这种冗余指数级爆炸。",
      "",
      "对于fib(50)，我们需做经验次的操作。完全不实际。",
      "",
      "### 第2步：记忆化 - O(n)",
      "",
      "缓存结果以避免重新计算。",
      "",
      "```javascript",
      "function fib(n, memo = {}) {",
      "  if (n in memo) return memo[n]",
      "  if (n <= 1) return n",
      "  memo[n] = fib(n - 1, memo) + fib(n - 2, memo)",
      "  return memo[n]",
      "}",
      "```",
      "",
      "**关键：**第一次计算fib(3)，我们存储它。下一次，我们立即返回存储的值。",
      "",
      "现在fib(50)只是50个递归调用（每个唯一状态一个），每个O(1)。",
      "",
      "**时间：**O(n)",
      "**空间：**O(n)用于memo + O(n)用于调用栈",
      "",
      "### 第3步：制表 - O(n)时间，O(n)空间",
      "",
      "迭代而非递归地构建表。",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  const dp = [0, 1]",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "**比记忆化更干净：**无递归开销，更清晰的逻辑。",
      "",
      "### 第4步：空间优化 - O(n)时间，O(1)空间",
      "",
      "注意我们仅需最后两个值。保持滚动窗口。",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  let prev2 = 0, prev1 = 1",
      "  for (let i = 2; i <= n; i++) {",
      "    const current = prev1 + prev2",
      "    prev2 = prev1",
      "    prev1 = current",
      "  }",
      "  return prev1",
      "}",
      "```",
      "",
      "**旅程：**O(2^n) → O(n) → O(n)时间，O(1)空间。Fibonacci对任何n都变即时。",
      "",
      "## 硬币兑换：规范DP问题",
      "",
      "**问题：**给定硬币[1, 2, 5]和金额5，找最少硬币数量兑换金额。",
      "",
      "金额5的答案：[5]（1个硬币）或[2, 2, 1]（3个硬币）。最少是1。",
      "",
      "### 清楚定义状态",
      "",
      "`dp[i]` = 兑换金额i的最少硬币数",
      "",
      "### 转移",
      "",
      "要兑换金额i，我们可用任何硬币c，然后解(i - c)。为使用的硬币添加1。",
      "",
      "`dp[i] = 1 + min(dp[i - coin]用于所有硬币)`",
      "",
      "### 代码",
      "",
      "```javascript",
      "function coinChange(coins, amount) {",
      "  const dp = Array(amount + 1).fill(Infinity)",
      "  dp[0] = 0  // 基本情况：金额0需0硬币",
      "  ",
      "  for (let i = 1; i <= amount; i++) {",
      "    for (const coin of coins) {",
      "      if (coin <= i) {",
      "        dp[i] = Math.min(dp[i], dp[i - coin] + 1)",
      "      }",
      "    }",
      "  }",
      "  return dp[amount] === Infinity ? -1 : dp[amount]",
      "}",
      "```",
      "",
      "**硬币=[1,2,5]，金额=5时：**",
      "- dp[0] = 0",
      "- dp[1] = min(dp[0] + 1) = 1  (用硬币1)",
      "- dp[2] = min(dp[1] + 1, dp[0] + 1) = 1  (用硬币2)",
      "- dp[3] = min(dp[2] + 1, dp[1] + 1) = 2  (用硬币2再1，或硬币1三次)",
      "- dp[4] = min(dp[3] + 1, dp[2] + 1) = 2  (用硬币2两次)",
      "- dp[5] = min(dp[4] + 1, dp[3] + 1, dp[0] + 1) = 1  (用硬币5)",
      "",
      "**时间：**O(金额 × 硬币)",
      "**空间：**O(金额)",
      "",
      "## 为什么硬币兑换是规范的",
      "",
      "结构教所有DP知识：",
      "1. **清楚状态：**dp[i] = 大小i子问题的答案",
      "2. **清楚转移：**尝试所有选择（硬币），选最好的",
      "3. **基本情况：**dp[0] = 0（空金额需0硬币）",
      "4. **往上构建：**解小金额先于大金额",
      "",
      "掌握这个模式，处处应用：爬楼梯、打家劫舍、最长回文、编辑距离等。",
      "",
      "## 变体：硬币兑换II（计数方式）",
      "",
      "有多少种方式用硬币[1, 2, 5]兑换金额5？",
      "",
      "`dp[i]` = 兑换金额i的方式数",
      "",
      "```javascript",
      "function change(amount, coins) {",
      "  const dp = Array(amount + 1).fill(0)",
      "  dp[0] = 1  // 一个方式：不用硬币",
      "  ",
      "  for (const coin of coins) {",
      "    for (let i = coin; i <= amount; i++) {",
      "      dp[i] += dp[i - coin]",
      "    }",
      "  }",
      "  return dp[amount]",
      "}",
      "```",
      "",
      "**关键区别：**在外循环迭代硬币（避免计数相同组合多次）。添加而非取最小值。"
    ].join('\n'),
  },
  leetcode: [
    { id: 509, title: 'Fibonacci Number', titleZh: 'Fibonacci 数', difficulty: 'Easy' },
    { id: 70, title: 'Climbing Stairs', titleZh: '爬楼梯', difficulty: 'Easy' },
    { id: 322, title: 'Coin Change', titleZh: '零钱兑换', difficulty: 'Medium' },
    { id: 518, title: 'Coin Change II', titleZh: '零钱兑换 II', difficulty: 'Medium' },
  ],
}
