import type { TopicContent } from '../../types'

export const dpIntroContent: TopicContent = {
  id: 'dp-intro',
  title: { en: 'Dynamic Programming Introduction', zh: '动态规划导论' },
  description: { en: 'Understand the 3 pillars of DP: optimal substructure, overlapping subproblems, and state definition', zh: '理解DP的3个支柱：最优子结构、重叠子问题、状态定义' },
  timeEstimate: '35 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      "## What Makes a Problem Solvable by DP?",
      "",
      "Dynamic Programming (DP) is about solving problems efficiently by avoiding redundant work. It applies when two conditions are met:",
      "",
      "**1. Optimal Substructure**",
      "The optimal solution to a problem can be built from optimal solutions to subproblems.",
      "",
      "Example: Longest increasing subsequence of [1, 3, 2, 4] is built from [1] + longest increasing subsequence of [3, 2, 4] starting after 1.",
      "",
      "**2. Overlapping Subproblems**",
      "The same subproblems are solved multiple times.",
      "",
      "Without DP (naive recursion): Computing fib(5) computes fib(3) twice, fib(2) three times.",
      "With DP (memoization): Compute each subproblem once, reuse results.",
      "",
      "## Top-Down vs Bottom-Up",
      "",
      "### Top-Down (Memoization - Recursion with Caching)",
      "",
      "```javascript",
      "function fib(n, memo = {}) {",
      "  if (n in memo) return memo[n]  // Return cached result",
      "  if (n <= 1) return n",
      "  ",
      "  memo[n] = fib(n - 1, memo) + fib(n - 2, memo)",
      "  return memo[n]",
      "}",
      "```",
      "",
      "**Pros:**",
      "- Natural, looks like the recursive solution",
      "- Only compute states you actually need",
      "- Easy to understand the problem structure",
      "",
      "**Cons:**",
      "- Recursion overhead (call stack)",
      "- Can hit stack overflow for very deep recursion",
      "",
      "### Bottom-Up (Tabulation - Iteration with Array)",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  ",
      "  const dp = [0, 1]",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "**Pros:**",
      "- No recursion overhead",
      "- Iterative, no stack issues",
      "- Can optimize space by keeping only necessary values",
      "",
      "**Cons:**",
      "- Need to figure out iteration order",
      "- Might compute states you don't need",
      "",
      "## State Definition - The Core of DP",
      "",
      "The hardest part of DP is defining what \"state\" represents. Clear state definition makes the problem solvable.",
      "",
      "**Example: Maximum Subarray Sum**",
      "",
      "Bad state: `dp[i]` = \"result for array i\" (unclear)",
      "",
      "Good state: `dp[i]` = \"maximum sum of subarray ending at index i\"",
      "",
      "Why? Because to find dp[i], we know we must include element at index i. We only ask: do we extend the subarray from i-1, or start fresh?",
      "",
      "```javascript",
      "function maxSubarray(nums) {",
      "  let dp = nums[0]        // Max ending at index 0",
      "  let maxSum = nums[0]",
      "  ",
      "  for (let i = 1; i < nums.length; i++) {",
      "    dp = Math.max(nums[i], dp + nums[i])  // Extend or start new",
      "    maxSum = Math.max(maxSum, dp)",
      "  }",
      "  return maxSum",
      "}",
      "```",
      "",
      "## Example: Climbing Stairs",
      "",
      "**Problem:** You can climb 1 or 2 stairs per step. How many ways to climb n stairs?",
      "",
      "**Optimal substructure:** Ways to reach stair n = ways to reach stair (n-1) + ways to reach stair (n-2). Because from stair (n-1), you climb 1 step to reach n. From stair (n-2), you climb 2 steps to reach n.",
      "",
      "**Overlapping subproblems:** Computing ways to reach stair 5 requires computing ways to reach stair 3 and 4. Computing ways to reach stair 4 also requires computing ways to reach stair 3.",
      "",
      "**State definition:** `dp[i]` = number of ways to reach stair i",
      "",
      "```javascript",
      "function climbStairs(n) {",
      "  if (n <= 1) return 1",
      "  const dp = [1, 1]  // dp[0]=1 (already at start), dp[1]=1 (one way: one step)",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "## When NOT to Use DP",
      "",
      "- Problems without overlapping subproblems (like simple traversal with no redundancy)",
      "- Problems optimally solved greedily (shortest path in DAG with careful thinking, but usually needs DP)",
      "- Problems that can be solved with basic math (some sequence problems)",
      "",
      "## DP Complexity Analysis",
      "",
      "Time = (Number of unique states) × (Work per state)",
      "",
      "Space = (Number of unique states) for memoization/DP table",
      "",
      "**Example: Fibonacci**",
      "- States: n (fib(0) to fib(n))",
      "- Work per state: O(1) (just two additions)",
      "- Time: O(n) × O(1) = O(n)",
      "- Space: O(n) for table",
      "",
      "## Key Insight",
      "",
      "DP is not about mathematical cleverness. It's about recognizing that you're solving the same subproblems repeatedly, and caching results to avoid redundant work. If you can describe the state clearly and define the transition, DP becomes systematic and solvable."
    ].join('\n'),
    zh: [
      "## 什么使问题可用DP解决？",
      "",
      "动态规划（DP）是通过避免冗余工作有效解决问题。当满足两个条件时适用：",
      "",
      "**1. 最优子结构**",
      "问题的最优解可以从子问题的最优解构建。",
      "",
      "示例：[1, 3, 2, 4]的最长递增子序列是从[1]构建的 + [3, 2, 4]在1之后的最长递增子序列。",
      "",
      "**2. 重叠子问题**",
      "相同子问题被多次解决。",
      "",
      "不用DP（幼稚递归）：计算fib(5)计算fib(3)两次，fib(2)三次。",
      "用DP（记忆化）：计算每个子问题一次，重用结果。",
      "",
      "## 自顶向下vs自底向上",
      "",
      "### 自顶向下（记忆化 - 带缓存的递归）",
      "",
      "```javascript",
      "function fib(n, memo = {}) {",
      "  if (n in memo) return memo[n]  // 返回缓存结果",
      "  if (n <= 1) return n",
      "  ",
      "  memo[n] = fib(n - 1, memo) + fib(n - 2, memo)",
      "  return memo[n]",
      "}",
      "```",
      "",
      "**优点：**",
      "- 自然，看起来像递归解",
      "- 仅计算你实际需要的状态",
      "- 易于理解问题结构",
      "",
      "**缺点：**",
      "- 递归开销（调用栈）",
      "- 很深的递归可能栈溢出",
      "",
      "### 自底向上（制表 - 用数组迭代）",
      "",
      "```javascript",
      "function fib(n) {",
      "  if (n <= 1) return n",
      "  ",
      "  const dp = [0, 1]",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "**优点：**",
      "- 无递归开销",
      "- 迭代式，无栈问题",
      "- 可通过仅保持必要值优化空间",
      "",
      "**缺点：**",
      "- 需弄清迭代顺序",
      "- 可能计算不需要的状态",
      "",
      "## 状态定义 - DP的核心",
      "",
      "DP最难的部分是定义\"状态\"代表什么。清晰的状态定义使问题可解。",
      "",
      "**示例：最大子数组和**",
      "",
      "坏状态：`dp[i]` = \"数组i的结果\"（不清楚）",
      "",
      "好状态：`dp[i]` = \"在索引i处结束的子数组的最大和\"",
      "",
      "为什么？因为找到dp[i]，我们知道必须包括索引i的元素。我们只问：我们是否从i-1扩展子数组，还是重新开始？",
      "",
      "```javascript",
      "function maxSubarray(nums) {",
      "  let dp = nums[0]        // 在索引0处结束的最大",
      "  let maxSum = nums[0]",
      "  ",
      "  for (let i = 1; i < nums.length; i++) {",
      "    dp = Math.max(nums[i], dp + nums[i])  // 扩展或开始新",
      "    maxSum = Math.max(maxSum, dp)",
      "  }",
      "  return maxSum",
      "}",
      "```",
      "",
      "## 示例：爬楼梯",
      "",
      "**问题：**你每步可以爬1或2个楼梯。爬n个楼梯有多少种方式？",
      "",
      "**最优子结构：**到达楼梯n的方式 = 到达楼梯(n-1)的方式 + 到达楼梯(n-2)的方式。因为从楼梯(n-1)，你爬1步到达n。从楼梯(n-2)，你爬2步到达n。",
      "",
      "**重叠子问题：**计算到达楼梯5的方式需要计算到达楼梯3和4的方式。计算到达楼梯4也需要计算到达楼梯3。",
      "",
      "**状态定义：**`dp[i]` = 到达楼梯i的方式数",
      "",
      "```javascript",
      "function climbStairs(n) {",
      "  if (n <= 1) return 1",
      "  const dp = [1, 1]  // dp[0]=1（已在开始），dp[1]=1（一个方式：一步）",
      "  for (let i = 2; i <= n; i++) {",
      "    dp[i] = dp[i - 1] + dp[i - 2]",
      "  }",
      "  return dp[n]",
      "}",
      "```",
      "",
      "## 何时不使用DP",
      "",
      "- 无重叠子问题的问题（如无冗余的简单遍历）",
      "- 最优用贪心解决的问题（DAG中最短路径，仔细思考，但通常需DP）",
      "- 可用基础数学解决的问题（某些序列问题）",
      "",
      "## DP复杂度分析",
      "",
      "时间 = （唯一状态数）×（每个状态的工作）",
      "",
      "空间 = （唯一状态数）用于记忆化/DP表",
      "",
      "**示例：Fibonacci**",
      "- 状态：n（fib(0)到fib(n)）",
      "- 每个状态的工作：O(1)（仅两个加法）",
      "- 时间：O(n) × O(1) = O(n)",
      "- 空间：O(n)用于表",
      "",
      "## 关键洞察",
      "",
      "DP不是关于数学聪明。它是关于认识到你重复解决相同子问题，并缓存结果以避免冗余工作。如果你能清楚地描述状态并定义转移，DP变成系统和可解。"
    ].join('\n'),
  },
  leetcode: [],
}
