import type { TopicContent } from '../../types'

export const knapsackContent: TopicContent = {
  id: 'dp-knapsack',
  title: { en: '0/1 Knapsack Problem', zh: '0/1背包问题' },
  description: { en: 'Master the mother of all DP problems. State, transition, and space optimization.', zh: '掌握所有DP问题之母。状态、转移和空间优化。' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## The 0/1 Knapsack Problem",
      "",
      "**Setup:** You have a knapsack with capacity W. You have n items, each with weight w[i] and value v[i]. You can take each item 0 or 1 times. Maximize the total value.",
      "",
      "This is called \"0/1\" because each item is either taken (1) or not taken (0).",
      "",
      "**Example:** Capacity = 5, items = [(weight: 2, value: 3), (weight: 3, value: 4), (weight: 4, value: 5)]",
      "",
      "Best solution: Take items 1 and 2 (weight 2+3=5, value 3+4=7). Can't fit item 3.",
      "",
      "## State Definition",
      "",
      "`dp[i][w]` = maximum value achievable using items 0...i-1 with capacity w",
      "",
      "Two dimensions because:",
      "- First dimension: \"up to item i\", decides which items we've considered",
      "- Second dimension: \"with capacity w\", respects the weight constraint",
      "",
      "## Transition Equation",
      "",
      "For each item i and capacity w, we have a choice:",
      "",
      "```",
      "If we DON'T take item i:",
      "  dp[i][w] = dp[i-1][w]  (value doesn't change)",
      "",
      "If we DO take item i (only if w[i] <= w):",
      "  dp[i][w] = v[i] + dp[i-1][w - w[i]]",
      "  (we get value v[i], plus best value from remaining capacity)",
      "",
      "Take the maximum of the two choices:",
      "  dp[i][w] = max(dp[i-1][w], v[i] + dp[i-1][w - w[i]])",
      "```",
      "",
      "## 2D Solution (Standard)",
      "",
      "```javascript",
      "function knapsack(capacity, weights, values) {",
      "  const n = weights.length",
      "  const dp = Array(n + 1).fill(null).map(() => Array(capacity + 1).fill(0))",
      "  ",
      "  // dp[0][w] = 0 for all w (base case: no items, no value)",
      "  ",
      "  for (let i = 1; i <= n; i++) {",
      "    for (let w = 0; w <= capacity; w++) {",
      "      if (weights[i - 1] <= w) {",
      "        // Can take item i-1",
      "        dp[i][w] = Math.max(",
      "          dp[i - 1][w],                              // Don't take",
      "          values[i - 1] + dp[i - 1][w - weights[i - 1]]  // Take",
      "        )",
      "      } else {",
      "        // Can't take item i-1 (too heavy)",
      "        dp[i][w] = dp[i - 1][w]",
      "      }",
      "    }",
      "  }",
      "  return dp[n][capacity]",
      "}",
      "```",
      "",
      "**Time:** O(n × W)",
      "**Space:** O(n × W)",
      "",
      "## 1D Solution (Space-Optimized)",
      "",
      "Notice we only need the previous row (i-1) to compute the current row (i). Use a 1D array and update it backward.",
      "",
      "```javascript",
      "function knapsack1D(capacity, weights, values) {",
      "  const n = weights.length",
      "  const dp = Array(capacity + 1).fill(0)",
      "  ",
      "  for (let i = 0; i < n; i++) {",
      "    // Iterate backward to avoid using updated values",
      "    for (let w = capacity; w >= weights[i]; w--) {",
      "      dp[w] = Math.max(",
      "        dp[w],                              // Don't take",
      "        values[i] + dp[w - weights[i]]      // Take",
      "      )",
      "    }",
      "  }",
      "  return dp[capacity]",
      "}",
      "```",
      "",
      "**Why iterate backward?** If we iterate forward and update dp[w], the value dp[w - weights[i]] is already updated, making it seem like we're using item i twice. By iterating backward, we ensure dp[w - weights[i]] still contains the old value (from the previous iteration).",
      "",
      "**Time:** O(n × W)",
      "**Space:** O(W)",
      "",
      "## Example: Capacity 5, Items [(w:2, v:3), (w:3, v:4), (w:4, v:5)]",
      "",
      "Using 1D DP, tracking backward iteration:",
      "",
      "```",
      "Initial: dp = [0, 0, 0, 0, 0, 0]",
      "",
      "After item 0 (w:2, v:3):",
      "  w=5: dp[5] = max(0, 3 + dp[3]) = max(0, 3 + 0) = 3",
      "  w=4: dp[4] = max(0, 3 + dp[2]) = max(0, 3 + 0) = 3",
      "  w=3: dp[3] = max(0, 3 + dp[1]) = max(0, 3 + 0) = 3",
      "  w=2: dp[2] = max(0, 3 + dp[0]) = max(0, 3 + 0) = 3",
      "  dp = [0, 0, 3, 3, 3, 3]",
      "",
      "After item 1 (w:3, v:4):",
      "  w=5: dp[5] = max(3, 4 + dp[2]) = max(3, 4 + 3) = 7",
      "  w=4: dp[4] = max(3, 4 + dp[1]) = max(3, 4 + 0) = 4",
      "  w=3: dp[3] = max(3, 4 + dp[0]) = max(3, 4 + 0) = 4",
      "  dp = [0, 0, 3, 4, 4, 7]",
      "",
      "After item 2 (w:4, v:5):",
      "  w=5: dp[5] = max(7, 5 + dp[1]) = max(7, 5 + 0) = 7",
      "  w=4: dp[4] = max(4, 5 + dp[0]) = max(4, 5 + 0) = 5",
      "  dp = [0, 0, 3, 4, 5, 7]",
      "",
      "Answer: 7 (take items 0 and 1)",
      "```",
      "",
      "## Variants Using Knapsack Pattern",
      "",
      "The knapsack template applies to many problems:",
      "",
      "- **Partition Equal Subset Sum:** Can we split array into two subsets with equal sum? (Weight = Value = element, capacity = sum/2)",
      "- **Target Sum:** Assign +/- to make target sum (similar transformation)",
      "- **Last Stone Weight II:** Similar to partition",
      "",
      "## Key Insights",
      "",
      "1. **2D DP is intuitive:** First dimension = item choice, second = capacity",
      "2. **1D DP saves space:** We only need the previous row, so use rolling array",
      "3. **Backward iteration matters:** Essential for avoiding double-counting items",
      "4. **Transition is the core:** Once you write the transition equation, the code flows naturally"
    ].join('\n'),
    zh: [
      "## 0/1背包问题",
      "",
      "**设置：**你有容量W的背包。你有n件物品，每件重量w[i]和价值v[i]。每件物品可取0或1次。最大化总价值。",
      "",
      "称为\"0/1\"因为每件物品要么取（1），要么不取（0）。",
      "",
      "**示例：**容量 = 5，物品 = [(重:2, 价:3), (重:3, 价:4), (重:4, 价:5)]",
      "",
      "最佳方案：取物品1和2（重2+3=5，价3+4=7）。装不下物品3。",
      "",
      "## 状态定义",
      "",
      "`dp[i][w]` = 用物品0...i-1在容量w下的最大可达值",
      "",
      "两个维度因为：",
      "- 第一维：\"到物品i\"，决定考虑哪些物品",
      "- 第二维：\"容量w\"，尊重重量约束",
      "",
      "## 转移方程",
      "",
      "对每件物品i和容量w，我们有选择：",
      "",
      "```",
      "如果我们不取物品i：",
      "  dp[i][w] = dp[i-1][w]  (价值不变)",
      "",
      "如果我们取物品i（仅如果w[i] <= w）：",
      "  dp[i][w] = v[i] + dp[i-1][w - w[i]]",
      "  (我们得到价值v[i]，加剩余容量的最佳价值)",
      "",
      "取两个选择的最大值：",
      "  dp[i][w] = max(dp[i-1][w], v[i] + dp[i-1][w - w[i]])",
      "```",
      "",
      "## 2D解（标准）",
      "",
      "```javascript",
      "function knapsack(capacity, weights, values) {",
      "  const n = weights.length",
      "  const dp = Array(n + 1).fill(null).map(() => Array(capacity + 1).fill(0))",
      "  ",
      "  // dp[0][w] = 0用于所有w（基本情况：无物品，无价值）",
      "  ",
      "  for (let i = 1; i <= n; i++) {",
      "    for (let w = 0; w <= capacity; w++) {",
      "      if (weights[i - 1] <= w) {",
      "        // 可取物品i-1",
      "        dp[i][w] = Math.max(",
      "          dp[i - 1][w],                              // 不取",
      "          values[i - 1] + dp[i - 1][w - weights[i - 1]]  // 取",
      "        )",
      "      } else {",
      "        // 不能取物品i-1（太重）",
      "        dp[i][w] = dp[i - 1][w]",
      "      }",
      "    }",
      "  }",
      "  return dp[n][capacity]",
      "}",
      "```",
      "",
      "**时间：**O(n × W)",
      "**空间：**O(n × W)",
      "",
      "## 1D解（空间优化）",
      "",
      "注意我们仅需前一行(i-1)来计算当前行(i)。使用1D数组并向后更新。",
      "",
      "```javascript",
      "function knapsack1D(capacity, weights, values) {",
      "  const n = weights.length",
      "  const dp = Array(capacity + 1).fill(0)",
      "  ",
      "  for (let i = 0; i < n; i++) {",
      "    // 向后迭代以避免使用已更新的值",
      "    for (let w = capacity; w >= weights[i]; w--) {",
      "      dp[w] = Math.max(",
      "        dp[w],                              // 不取",
      "        values[i] + dp[w - weights[i]]      // 取",
      "      )",
      "    }",
      "  }",
      "  return dp[capacity]",
      "}",
      "```",
      "",
      "**为什么向后迭代？**如果向前迭代并更新dp[w]，值dp[w - weights[i]]已更新，似乎我们用了物品i两次。向后迭代，我们确保dp[w - weights[i]]仍包含旧值（来自前一迭代）。",
      "",
      "**时间：**O(n × W)",
      "**空间：**O(W)",
      "",
      "## 示例：容量5，物品[(重:2, 价:3), (重:3, 价:4), (重:4, 价:5)]",
      "",
      "使用1D DP，追踪向后迭代：",
      "",
      "```",
      "初始：dp = [0, 0, 0, 0, 0, 0]",
      "",
      "物品0后(重:2, 价:3)：",
      "  w=5: dp[5] = max(0, 3 + dp[3]) = max(0, 3 + 0) = 3",
      "  w=4: dp[4] = max(0, 3 + dp[2]) = max(0, 3 + 0) = 3",
      "  w=3: dp[3] = max(0, 3 + dp[1]) = max(0, 3 + 0) = 3",
      "  w=2: dp[2] = max(0, 3 + dp[0]) = max(0, 3 + 0) = 3",
      "  dp = [0, 0, 3, 3, 3, 3]",
      "",
      "物品1后(重:3, 价:4)：",
      "  w=5: dp[5] = max(3, 4 + dp[2]) = max(3, 4 + 3) = 7",
      "  w=4: dp[4] = max(3, 4 + dp[1]) = max(3, 4 + 0) = 4",
      "  w=3: dp[3] = max(3, 4 + dp[0]) = max(3, 4 + 0) = 4",
      "  dp = [0, 0, 3, 4, 4, 7]",
      "",
      "物品2后(重:4, 价:5)：",
      "  w=5: dp[5] = max(7, 5 + dp[1]) = max(7, 5 + 0) = 7",
      "  w=4: dp[4] = max(4, 5 + dp[0]) = max(4, 5 + 0) = 5",
      "  dp = [0, 0, 3, 4, 5, 7]",
      "",
      "答案：7（取物品0和1）",
      "```",
      "",
      "## 使用背包模式的变体",
      "",
      "背包模板适用于许多问题：",
      "",
      "- **分割等和子集：**我们可以将数组分为两个等和子集吗？（重 = 价 = 元素，容量 = 和/2）",
      "- **目标和：**分配+/-来达到目标和（类似转化）",
      "- **最后石头重量II：**类似分割",
      "",
      "## 关键洞察",
      "",
      "1. **2D DP直观：**第一维 = 物品选择，第二维 = 容量",
      "2. **1D DP省空间：**我们仅需前一行，所以使用滚动数组",
      "3. **向后迭代重要：**防止双计物品的关键",
      "4. **转移是核心：**一旦写转移方程，代码自然流出"
    ].join('\n'),
  },
  leetcode: [
    { id: 416, title: 'Partition Equal Subset Sum', titleZh: '分割等和子集', difficulty: 'Medium' },
    { id: 494, title: 'Target Sum', titleZh: '目标和', difficulty: 'Medium' },
    { id: 1049, title: 'Last Stone Weight II', titleZh: '最后一块石头的重量 II', difficulty: 'Medium' },
  ],
}
