import type { TopicContent } from '../../types'

export const backtrackingFrameworkContent: TopicContent = {
  id: 'backtracking-framework',
  title: { en: 'Universal Backtracking Template', zh: '通用回溯模板' },
  description: { en: 'Master the universal framework: Choose-Explore-Unchoose. All backtracking problems follow this.', zh: '掌握通用框架：选择-探索-撤销。所有回溯问题都遵循这个。' },
  timeEstimate: '45 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## The Universal Backtracking Template",
      "",
      "Every backtracking problem follows the same structure:",
      "",
      "```",
      "1. Choose: Pick a choice from available options",
      "2. Explore: Recursively solve the subproblem with that choice",
      "3. Unchoose: Undo the choice (backtrack)",
      "```",
      "",
      "This 3-step pattern applies to permutations, combinations, subsets, Sudoku, N-queens - everything.",
      "",
      "## The Pattern in Code",
      "",
      "```javascript",
      "function backtrack(choices) {",
      "  if (baseCase) {",
      "    result.push(copy of current)",
      "    return",
      "  }",
      "  ",
      "  for (const choice of choices) {",
      "    // 1. Make choice",
      "    state.add(choice)  // or state[idx] = choice",
      "    ",
      "    // 2. Explore with that choice",
      "    backtrack(remainingChoices)",
      "    ",
      "    // 3. Undo choice",
      "    state.remove(choice)",
      "  }",
      "}",
      "```",
      "",
      "The mental model: explore a tree of decisions. Each path from root to leaf is a solution.",
      "",
      "## Decision Tree Example: [1, 2, 3]",
      "",
      "For permutations of [1, 2, 3], the decision tree looks like:",
      "",
      "```",
      "                 []",
      "            /    |    \\",
      "          [1]   [2]   [3]",
      "         / \\    / \\    / \\",
      "       [1,2] [1,3] [2,1] [2,3] [3,1] [3,2]",
      "        |      |      |      |      |      |",
      "      [1,2,3] [1,3,2] [2,1,3] [2,3,1] [3,1,2] [3,2,1]",
      "```",
      "",
      "At each level, we choose which element to add. When we've made 3 choices, we've built a complete permutation.",
      "",
      "## Permutations",
      "",
      "```javascript",
      "function permute(nums) {",
      "  const result = []",
      "  const used = new Set()",
      "  const current = []",
      "  ",
      "  function backtrack() {",
      "    if (current.length === nums.length) {",
      "      result.push([...current])  // Found a permutation",
      "      return",
      "    }",
      "    ",
      "    for (const num of nums) {",
      "      if (used.has(num)) continue",
      "      ",
      "      // Choose",
      "      current.push(num)",
      "      used.add(num)",
      "      ",
      "      // Explore",
      "      backtrack()",
      "      ",
      "      // Unchoose",
      "      current.pop()",
      "      used.delete(num)",
      "    }",
      "  }",
      "  ",
      "  backtrack()",
      "  return result",
      "}",
      "```",
      "",
      "## Combinations (n choose k)",
      "",
      "Unlike permutations, order doesn't matter, and we never revisit earlier elements.",
      "",
      "```javascript",
      "function combine(n, k) {",
      "  const result = []",
      "  const current = []",
      "  ",
      "  function backtrack(start) {",
      "    if (current.length === k) {",
      "      result.push([...current])",
      "      return",
      "    }",
      "    ",
      "    for (let i = start; i <= n; i++) {",
      "      // Choose",
      "      current.push(i)",
      "      ",
      "      // Explore with remaining elements after i",
      "      backtrack(i + 1)",
      "      ",
      "      // Unchoose",
      "      current.pop()",
      "    }",
      "  }",
      "  ",
      "  backtrack(1)",
      "  return result",
      "}",
      "```",
      "",
      "Key difference: pass `start = i + 1` to avoid duplicates. This ensures we consider combinations, not permutations.",
      "",
      "## Subsets",
      "",
      "All possible subsets (combinations of all sizes).",
      "",
      "```javascript",
      "function subsets(nums) {",
      "  const result = []",
      "  const current = []",
      "  ",
      "  function backtrack(start) {",
      "    result.push([...current])  // Every state is a valid subset",
      "    ",
      "    for (let i = start; i < nums.length; i++) {",
      "      current.push(nums[i])",
      "      backtrack(i + 1)",
      "      current.pop()",
      "    }",
      "  }",
      "  ",
      "  backtrack(0)",
      "  return result",
      "}",
      "```",
      "",
      "Notice: base case saves the result immediately (every subset is valid), not just at max depth.",
      "",
      "## Backtracking with Constraints",
      "",
      "Real problems add constraints. Prune branches early.",
      "",
      "**Example: N-Queens (place N queens on board, no conflicts)**",
      "",
      "```javascript",
      "function solveNQueens(n) {",
      "  const result = []",
      "  const board = Array(n).fill('.').map(() => Array(n).fill('.'))",
      "  const cols = new Set(), diag1 = new Set(), diag2 = new Set()",
      "  ",
      "  function backtrack(row) {",
      "    if (row === n) {",
      "      result.push(board.map(r => r.join('')))",
      "      return",
      "    }",
      "    ",
      "    for (let col = 0; col < n; col++) {",
      "      // Check if placing queen at (row, col) is safe",
      "      const d1 = row - col, d2 = row + col",
      "      if (cols.has(col) || diag1.has(d1) || diag2.has(d2)) continue",
      "      ",
      "      // Choose",
      "      board[row][col] = 'Q'",
      "      cols.add(col)",
      "      diag1.add(d1)",
      "      diag2.add(d2)",
      "      ",
      "      // Explore",
      "      backtrack(row + 1)",
      "      ",
      "      // Unchoose",
      "      board[row][col] = '.'",
      "      cols.delete(col)",
      "      diag1.delete(d1)",
      "      diag2.delete(d2)",
      "    }",
      "  }",
      "  ",
      "  backtrack(0)",
      "  return result",
      "}",
      "```",
      "",
      "The key optimization: only consider valid positions (early pruning).",
      "",
      "## Time Complexity of Backtracking",
      "",
      "The decision tree has exponential depth and branching. Worst case is O(b^d) where:",
      "- b = branching factor (choices at each step)",
      "- d = depth of tree",
      "",
      "For permutations: O(n!)",
      "For combinations: O(2^n)",
      "For subsets: O(2^n)",
      "",
      "This is unavoidable - the answer itself can have exponential size.",
      "",
      "## Backtracking Template Summary",
      "",
      "Every backtracking problem:",
      "1. **Identify choices** - what can you pick at each step?",
      "2. **Define base case** - when have you completed a solution?",
      "3. **Build decision tree** - at each step, try all choices, recurse, undo",
      "4. **Optimize with constraints** - skip invalid choices early (prune)"
    ].join('\n'),
    zh: [
      "## 通用回溯模板",
      "",
      "每个回溯问题遵循相同结构：",
      "",
      "```",
      "1. 选择：从可用选项中选一个",
      "2. 探索：用该选择递归解子问题",
      "3. 撤销：撤销选择（回溯）",
      "```",
      "",
      "这个3步模式适用于排列、组合、子集、数独、N皇后 - 所有东西。",
      "",
      "## 代码中的模式",
      "",
      "```javascript",
      "function backtrack(choices) {",
      "  if (baseCase) {",
      "    result.push(当前的副本)",
      "    return",
      "  }",
      "  ",
      "  for (const choice of choices) {",
      "    // 1. 做选择",
      "    state.add(choice)  // 或state[idx] = choice",
      "    ",
      "    // 2. 用该选择探索",
      "    backtrack(remainingChoices)",
      "    ",
      "    // 3. 撤销选择",
      "    state.remove(choice)",
      "  }",
      "}",
      "```",
      "",
      "心智模型：探索决策树。从根到叶的每条路径是一个解决方案。",
      "",
      "## 决策树示例：[1, 2, 3]",
      "",
      "[1, 2, 3]的排列，决策树看起来像：",
      "",
      "```",
      "                 []",
      "            /    |    \\",
      "          [1]   [2]   [3]",
      "         / \\    / \\    / \\",
      "       [1,2] [1,3] [2,1] [2,3] [3,1] [3,2]",
      "        |      |      |      |      |      |",
      "      [1,2,3] [1,3,2] [2,1,3] [2,3,1] [3,1,2] [3,2,1]",
      "```",
      "",
      "每个级别，我们选择添加哪个元素。当进行3个选择时，我们构建了完整排列。",
      "",
      "## 排列",
      "",
      "```javascript",
      "function permute(nums) {",
      "  const result = []",
      "  const used = new Set()",
      "  const current = []",
      "  ",
      "  function backtrack() {",
      "    if (current.length === nums.length) {",
      "      result.push([...current])  // 找到排列",
      "      return",
      "    }",
      "    ",
      "    for (const num of nums) {",
      "      if (used.has(num)) continue",
      "      ",
      "      // 选择",
      "      current.push(num)",
      "      used.add(num)",
      "      ",
      "      // 探索",
      "      backtrack()",
      "      ",
      "      // 撤销",
      "      current.pop()",
      "      used.delete(num)",
      "    }",
      "  }",
      "  ",
      "  backtrack()",
      "  return result",
      "}",
      "```",
      "",
      "## 组合（n选k）",
      "",
      "与排列不同，顺序无关，我们永不重访早期元素。",
      "",
      "```javascript",
      "function combine(n, k) {",
      "  const result = []",
      "  const current = []",
      "  ",
      "  function backtrack(start) {",
      "    if (current.length === k) {",
      "      result.push([...current])",
      "      return",
      "    }",
      "    ",
      "    for (let i = start; i <= n; i++) {",
      "      // 选择",
      "      current.push(i)",
      "      ",
      "      // 用i之后的剩余元素探索",
      "      backtrack(i + 1)",
      "      ",
      "      // 撤销",
      "      current.pop()",
      "    }",
      "  }",
      "  ",
      "  backtrack(1)",
      "  return result",
      "}",
      "```",
      "",
      "关键区别：传递`start = i + 1`以避免重复。这确保我们考虑组合，不是排列。",
      "",
      "## 子集",
      "",
      "所有可能的子集（所有大小的组合）。",
      "",
      "```javascript",
      "function subsets(nums) {",
      "  const result = []",
      "  const current = []",
      "  ",
      "  function backtrack(start) {",
      "    result.push([...current])  // 每个状态都是有效子集",
      "    ",
      "    for (let i = start; i < nums.length; i++) {",
      "      current.push(nums[i])",
      "      backtrack(i + 1)",
      "      current.pop()",
      "    }",
      "  }",
      "  ",
      "  backtrack(0)",
      "  return result",
      "}",
      "```",
      "",
      "注意：基本情况立即保存结果（每个子集都有效），不仅在最大深度。",
      "",
      "## 有约束的回溯",
      "",
      "真实问题添加约束。提前修剪分支。",
      "",
      "**示例：N皇后（在棋盘上放N个皇后，无冲突）**",
      "",
      "```javascript",
      "function solveNQueens(n) {",
      "  const result = []",
      "  const board = Array(n).fill('.').map(() => Array(n).fill('.'))",
      "  const cols = new Set(), diag1 = new Set(), diag2 = new Set()",
      "  ",
      "  function backtrack(row) {",
      "    if (row === n) {",
      "      result.push(board.map(r => r.join('')))",
      "      return",
      "    }",
      "    ",
      "    for (let col = 0; col < n; col++) {",
      "      // 检查在(row, col)放皇后是否安全",
      "      const d1 = row - col, d2 = row + col",
      "      if (cols.has(col) || diag1.has(d1) || diag2.has(d2)) continue",
      "      ",
      "      // 选择",
      "      board[row][col] = 'Q'",
      "      cols.add(col)",
      "      diag1.add(d1)",
      "      diag2.add(d2)",
      "      ",
      "      // 探索",
      "      backtrack(row + 1)",
      "      ",
      "      // 撤销",
      "      board[row][col] = '.'",
      "      cols.delete(col)",
      "      diag1.delete(d1)",
      "      diag2.delete(d2)",
      "    }",
      "  }",
      "  ",
      "  backtrack(0)",
      "  return result",
      "}",
      "```",
      "",
      "关键优化：仅考虑有效位置（提前修剪）。",
      "",
      "## 回溯的时间复杂度",
      "",
      "决策树有指数深度和分支。最坏情况是O(b^d)，其中：",
      "- b = 分支因子（每步选择）",
      "- d = 树深度",
      "",
      "排列：O(n!)",
      "组合：O(2^n)",
      "子集：O(2^n)",
      "",
      "这是不可避免的 - 答案本身可以有指数大小。",
      "",
      "## 回溯模板总结",
      "",
      "每个回溯问题：",
      "1. **识别选择** - 你在每步可以选什么？",
      "2. **定义基本情况** - 何时完成解决方案？",
      "3. **构建决策树** - 每步，尝试所有选择，递归，撤销",
      "4. **用约束优化** - 提前跳过无效选择（修剪）"
    ].join('\n'),
  },
  leetcode: [
    { id: 46, title: 'Permutations', titleZh: '排列', difficulty: 'Medium' },
    { id: 77, title: 'Combinations', titleZh: '组合', difficulty: 'Medium' },
    { id: 78, title: 'Subsets', titleZh: '子集', difficulty: 'Medium' },
    { id: 51, title: 'N-Queens', titleZh: 'N皇后', difficulty: 'Hard' },
  ],
}
