import type { TopicContent } from '../../types'

export const algoThinking: TopicContent = {
  id: 'intro-algo-thinking',
  title: { en: 'Algorithmic Thinking Framework', zh: '算法思维框架' },
  description: { en: 'Learn the core patterns and thinking frameworks that solve 90% of problems', zh: '学习解决90%问题的核心模式和思维框架' },
  timeEstimate: '45 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      "## Why Templates Beat Memorization",
      "",
      "Memorizing 300+ LeetCode solutions is impossible and pointless. Instead, successful problem-solving relies on recognizing patterns and applying proven templates. When you see a new problem, you should think: \"This is a variation of pattern X\" rather than \"I've never seen this before.\"",
      "",
      "The 10 core patterns cover 90% of technical interview problems. Learning these templates is like having a toolkit - once you understand when to use each tool, problem-solving becomes systematic, not mysterious.",
      "",
      "## The 10 Core Patterns",
      "",
      "**1. Two Pointers** - Used when you need to traverse or compare two parts of a sequence. Works on sorted arrays, linked lists, and finding pairs.",
      "",
      "**2. Sliding Window** - Fixed or variable-size window moving through data. Essential for substring, subarray, and range problems.",
      "",
      "**3. Binary Search** - Efficient search in sorted data or search space problems. Not just finding elements - used for optimization problems too.",
      "",
      "**4. Prefix Sum / Difference Array** - Transform range queries/updates into O(1) operations. Builds on array indexing cleverness.",
      "",
      "**5. Hash Table** - Trading space for speed. Frequency counting, lookups, and eliminating duplicates happen in O(1).",
      "",
      "**6. Tree Traversal** - DFS/BFS frameworks. Every tree problem is a traversal variation with different operations at each node.",
      "",
      "**7. Heap / Priority Queue** - Efficient access to min/max elements. Used in scheduling, merging, and top-K problems.",
      "",
      "**8. Graph DFS/BFS** - Component detection, pathfinding, topological sort. Often combined with Union-Find for connectivity.",
      "",
      "**9. Backtracking** - Systematic exploration of decision trees. All permutation, combination, and subset problems follow the Choose-Explore-Unchoose pattern.",
      "",
      "**10. Dynamic Programming** - Optimal substructure + overlapping subproblems. Define state, find transitions, use memoization or iteration.",
      "",
      "## How to Identify Which Pattern to Use",
      "",
      "**Problem asks for:**",
      "- \"Find a pair/element with property X\" → Two Pointers or Hash Table",
      "- \"Longest/shortest substring/subarray with property X\" → Sliding Window",
      "- \"Find element in sorted data\" → Binary Search",
      "- \"Count elements with property X\" → Frequency Map",
      "- \"Generate all combinations/permutations/subsets\" → Backtracking",
      "- \"Find optimal value (max/min)\" → Dynamic Programming or Greedy",
      "- \"Connected components, shortest path\" → Graph DFS/BFS or Union-Find",
      "- \"Traverse a tree\" → DFS (recursive or stack) or BFS (queue)",
      "",
      "## The Difference Between Pattern and Solution",
      "",
      "A **pattern** is the algorithm template and approach. A **solution** is implementing that pattern for a specific problem. The same pattern (e.g., two pointers) solves Container With Most Water, Valid Palindrome, and Merge Sorted Arrays differently.",
      "",
      "Master the pattern → Apply it flexibly → Problem-solving becomes systematic.",
      "",
      "## Learning Strategy",
      "",
      "1. **Learn the template** with a simple example",
      "2. **Understand the mental model** - why does this approach work?",
      "3. **Code it repeatedly** until muscle memory kicks in",
      "4. **Apply to variations** - same pattern, different problems",
      "5. **Combine patterns** - hard problems often need two patterns",
      "",
      "This course walks through each pattern with theory, code templates, and multiple practice problems. By the end, you'll recognize patterns instantly and solve problems systematically."
    ].join('\n'),
    zh: [
      "## 为什么模板优于死记硬背",
      "",
      "背诵300多道LeetCode题目解法是不可能也没有意义的。成功的问题解决依赖于识别模式并应用已验证的模板。当你看到新问题时，应该思考：「这是模式X的变体」而不是「我从未见过这种题目」。",
      "",
      "10个核心模式覆盖了90%的技术面试题。学习这些模板就像拥有一个工具箱——一旦你理解了何时使用每个工具，问题解决就变成了系统的过程，而不是神秘的。",
      "",
      "## 10个核心模式",
      "",
      "**1. 双指针** - 当你需要遍历或比较序列的两部分时使用。适用于排序数组、链表和查找配对问题。",
      "",
      "**2. 滑动窗口** - 固定或可变大小的窗口通过数据移动。对于子字符串、子数组和范围问题至关重要。",
      "",
      "**3. 二分查找** - 在排序数据或搜索空间问题中进行高效查找。不仅是查找元素——也用于优化问题。",
      "",
      "**4. 前缀和/差分数组** - 将范围查询/更新转化为O(1)操作。基于数组索引的巧妙性。",
      "",
      "**5. 哈希表** - 用空间换速度。频率计数、查找和消除重复在O(1)内完成。",
      "",
      "**6. 树的遍历** - DFS/BFS框架。每个树问题都是遍历的变体，在每个节点执行不同的操作。",
      "",
      "**7. 堆/优先队列** - 高效访问最小/最大元素。用于调度、合并和Top-K问题。",
      "",
      "**8. 图的DFS/BFS** - 连通分量检测、寻路、拓扑排序。通常与Union-Find结合用于连通性问题。",
      "",
      "**9. 回溯** - 系统地探索决策树。所有排列、组合和子集问题都遵循选择-探索-撤销模式。",
      "",
      "**10. 动态规划** - 最优子结构+重叠子问题。定义状态、找到转移、使用记忆化或迭代。",
      "",
      "## 如何识别使用哪种模式",
      "",
      "**问题要求：**",
      "- 「找具有属性X的配对/元素」→ 双指针或哈希表",
      "- 「最长/最短具有属性X的子字符串/子数组」→ 滑动窗口",
      "- 「在排序数据中查找元素」→ 二分查找",
      "- 「计算具有属性X的元素」→ 频率Map",
      "- 「生成所有组合/排列/子集」→ 回溯",
      "- 「找最优值（最大/最小）」→ 动态规划或贪心",
      "- 「连通分量、最短路径」→ 图DFS/BFS或Union-Find",
      "- 「遍历树」→ DFS（递归或栈）或BFS（队列）",
      "",
      "## 模式与解决方案的区别",
      "",
      "**模式**是算法模板和方法。**解决方案**是为特定问题实现该模式。相同的模式（如双指针）以不同方式解决盛水最多的容器、验证回文和合并排序数组。",
      "",
      "掌握模式 → 灵活应用 → 问题解决变得系统化。",
      "",
      "## 学习策略",
      "",
      "1. **学习模板** 用简单例子",
      "2. **理解心智模型** - 为什么这种方法有效？",
      "3. **反复编码** 直到肌肉记忆启动",
      "4. **应用变体** - 相同模式，不同问题",
      "5. **结合模式** - 难题通常需要两个模式",
      "",
      "这个课程通过理论、代码模板和多个练习问题来讲解每个模式。到最后，你将即时识别模式并系统地解决问题。"
    ].join('\n'),
  },
  leetcode: [],
}
