import type { TopicContent } from '../../types'

export const binaryHeapContent: TopicContent = {
  id: 'heaps-binary-heap',
  title: { en: 'Binary Heap & Priority Queue', zh: '二叉堆与优先队列' },
  description: { en: 'Master heap structure, heapify operation, and the Top-K pattern', zh: '掌握堆结构、堆化操作和Top-K模式' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## What is a Heap?",
      "",
      "A heap is a complete binary tree where each parent is larger (max heap) or smaller (min heap) than its children. The key insight: this is NOT a sorted array. It's a partial ordering that enables efficient min/max access.",
      "",
      "```",
      "Max Heap:         Min Heap:",
      "       9               1",
      "      / \\             / \\",
      "     7   8           2   3",
      "    / \\ /           / \\ /",
      "   3  5 2         8  9 4 5",
      "",
      "Parent >= children   Parent <= children",
      "```",
      "",
      "## Heap as Array",
      "",
      "Heaps are stored as arrays where the structure is implicit:",
      "- Node at index i has:",
      "  - Left child at index 2*i + 1",
      "  - Right child at index 2*i + 2",
      "  - Parent at index Math.floor((i - 1) / 2)",
      "",
      "This array representation avoids pointers and works perfectly with dynamic arrays.",
      "",
      "## Heapify Down (Bubble Down)",
      "",
      "When a node violates the heap property, swap it with the larger (max heap) or smaller (min heap) child recursively.",
      "",
      "```javascript",
      "function heapifyDown(arr, i) {",
      "  const size = arr.length",
      "  while (true) {",
      "    let largest = i",
      "    const left = 2 * i + 1",
      "    const right = 2 * i + 2",
      "    ",
      "    if (left < size && arr[left] > arr[largest]) {",
      "      largest = left",
      "    }",
      "    if (right < size && arr[right] > arr[largest]) {",
      "      largest = right",
      "    }",
      "    ",
      "    if (largest === i) break  // Heap property satisfied",
      "    ",
      "    [arr[i], arr[largest]] = [arr[largest], arr[i]]",
      "    i = largest",
      "  }",
      "}",
      "```",
      "",
      "**Time**: O(log n) - each swap goes down one level.",
      "",
      "## Heapify Up (Bubble Up)",
      "",
      "When inserting a new element, add at the end and bubble up.",
      "",
      "```javascript",
      "function heapifyUp(arr, i) {",
      "  while (i > 0) {",
      "    const parent = Math.floor((i - 1) / 2)",
      "    if (arr[i] <= arr[parent]) break",
      "    [arr[i], arr[parent]] = [arr[parent], arr[i]]",
      "    i = parent",
      "  }",
      "}",
      "```",
      "",
      "**Time**: O(log n) - moves up through parent links.",
      "",
      "## Building a Heap",
      "",
      "To build a heap from unsorted array, heapify down from the last non-leaf node.",
      "",
      "```javascript",
      "function buildHeap(arr) {",
      "  for (let i = Math.floor(arr.length / 2) - 1; i >= 0; i--) {",
      "    heapifyDown(arr, i)",
      "  }",
      "}",
      "```",
      "",
      "**Time**: O(n) - surprisingly efficient! Most nodes are leaves, only O(n) nodes to heapify.",
      "",
      "## Priority Queue Operations",
      "",
      "A priority queue is a heap interface for common operations:",
      "",
      "```javascript",
      "class MaxHeap {",
      "  constructor() { this.heap = [] }",
      "  ",
      "  push(val) {",
      "    this.heap.push(val)",
      "    this.heapifyUp(this.heap.length - 1)",
      "  }",
      "  ",
      "  pop() {",
      "    if (this.heap.length === 0) return null",
      "    const max = this.heap[0]",
      "    const last = this.heap.pop()",
      "    if (this.heap.length) {",
      "      this.heap[0] = last",
      "      this.heapifyDown(0)",
      "    }",
      "    return max",
      "  }",
      "  ",
      "  peek() { return this.heap[0] }",
      "  ",
      "  heapifyUp(i) {",
      "    while (i > 0) {",
      "      const parent = Math.floor((i - 1) / 2)",
      "      if (this.heap[i] <= this.heap[parent]) break",
      "      [this.heap[i], this.heap[parent]] = [this.heap[parent], this.heap[i]]",
      "      i = parent",
      "    }",
      "  }",
      "  ",
      "  heapifyDown(i) {",
      "    const size = this.heap.length",
      "    while (true) {",
      "      let largest = i",
      "      const left = 2 * i + 1",
      "      const right = 2 * i + 2",
      "      if (left < size && this.heap[left] > this.heap[largest]) largest = left",
      "      if (right < size && this.heap[right] > this.heap[largest]) largest = right",
      "      if (largest === i) break",
      "      [this.heap[i], this.heap[largest]] = [this.heap[largest], this.heap[i]]",
      "      i = largest",
      "    }",
      "  }",
      "}",
      "```",
      "",
      "| Operation | Time |",
      "|-----------|------|",
      "| Push | O(log n) |",
      "| Pop | O(log n) |",
      "| Peek | O(1) |",
      "",
      "## The Top-K Pattern",
      "",
      "Find the k largest (or smallest) elements. Heaps are perfect for this.",
      "",
      "**Approach 1: Max Heap, extract k times**",
      "```javascript",
      "function findKLargest(nums, k) {",
      "  const heap = new MaxHeap()",
      "  for (const num of nums) heap.push(num)",
      "  const result = []",
      "  for (let i = 0; i < k; i++) result.push(heap.pop())",
      "  return result",
      "}",
      "// Time: O(n log n) build + O(k log n) extraction = O(n log n)",
      "```",
      "",
      "**Approach 2: Min Heap of size k**",
      "```javascript",
      "function findKLargest(nums, k) {",
      "  const heap = new MinHeap()",
      "  for (const num of nums) {",
      "    heap.push(num)",
      "    if (heap.size() > k) heap.pop()  // Keep only k largest",
      "  }",
      "  return heap.heap",
      "}",
      "// Time: O(n log k) - better if k << n",
      "```",
      "",
      "In approach 2, we maintain a min heap of the k largest elements. The top of this heap is the k-th largest. When a new element is larger than the heap top, we pop the small element and insert the large one.",
      "",
      "## When to Use Heaps",
      "",
      "- **Scheduling**: priority queue for tasks",
      "- **Top-K problems**: most efficient for k << n",
      "- **Median finding**: combine min and max heaps",
      "- **Dijkstra's algorithm**: priority queue for edge weights",
      "- **Heap sort**: convert unsorted array to sorted in O(n log n)"
    ].join('\n'),
    zh: [
      "## 什么是堆？",
      "",
      "堆是一个完全二叉树，其中每个父节点大于（最大堆）或小于（最小堆）其子节点。关键洞察：这不是排序数组。它是一个部分排序，启用高效的最小/最大访问。",
      "",
      "```",
      "最大堆：          最小堆：",
      "       9               1",
      "      / \\             / \\",
      "     7   8           2   3",
      "    / \\ /           / \\ /",
      "   3  5 2         8  9 4 5",
      "",
      "父 >= 子          父 <= 子",
      "```",
      "",
      "## 堆作为数组",
      "",
      "堆作为数组存储，其中结构是隐式的：",
      "- 索引i处的节点有：",
      "  - 左子在索引2*i + 1",
      "  - 右子在索引2*i + 2",
      "  - 父在索引Math.floor((i - 1) / 2)",
      "",
      "这个数组表示避免指针且与动态数组完美工作。",
      "",
      "## 堆化下沉（下降冒泡）",
      "",
      "当节点违反堆属性时，递归地与较大（最大堆）或较小（最小堆）的孩子交换。",
      "",
      "```javascript",
      "function heapifyDown(arr, i) {",
      "  const size = arr.length",
      "  while (true) {",
      "    let largest = i",
      "    const left = 2 * i + 1",
      "    const right = 2 * i + 2",
      "    ",
      "    if (left < size && arr[left] > arr[largest]) {",
      "      largest = left",
      "    }",
      "    if (right < size && arr[right] > arr[largest]) {",
      "      largest = right",
      "    }",
      "    ",
      "    if (largest === i) break  // 堆属性满足",
      "    ",
      "    [arr[i], arr[largest]] = [arr[largest], arr[i]]",
      "    i = largest",
      "  }",
      "}",
      "```",
      "",
      "**时间**：O(log n) - 每次交换向下一个级别。",
      "",
      "## 堆化上升（上升冒泡）",
      "",
      "插入新元素时，添加在末尾并上升冒泡。",
      "",
      "```javascript",
      "function heapifyUp(arr, i) {",
      "  while (i > 0) {",
      "    const parent = Math.floor((i - 1) / 2)",
      "    if (arr[i] <= arr[parent]) break",
      "    [arr[i], arr[parent]] = [arr[parent], arr[i]]",
      "    i = parent",
      "  }",
      "}",
      "```",
      "",
      "**时间**：O(log n) - 通过父链接向上移动。",
      "",
      "## 构建堆",
      "",
      "要从无序数组构建堆，从最后一个非叶节点堆化下沉。",
      "",
      "```javascript",
      "function buildHeap(arr) {",
      "  for (let i = Math.floor(arr.length / 2) - 1; i >= 0; i--) {",
      "    heapifyDown(arr, i)",
      "  }",
      "}",
      "```",
      "",
      "**时间**：O(n) - 令人惊讶的高效！大多数节点是叶，仅O(n)个节点堆化。",
      "",
      "## 优先队列操作",
      "",
      "优先队列是堆接口用于常见操作：",
      "",
      "```javascript",
      "class MaxHeap {",
      "  constructor() { this.heap = [] }",
      "  ",
      "  push(val) {",
      "    this.heap.push(val)",
      "    this.heapifyUp(this.heap.length - 1)",
      "  }",
      "  ",
      "  pop() {",
      "    if (this.heap.length === 0) return null",
      "    const max = this.heap[0]",
      "    const last = this.heap.pop()",
      "    if (this.heap.length) {",
      "      this.heap[0] = last",
      "      this.heapifyDown(0)",
      "    }",
      "    return max",
      "  }",
      "  ",
      "  peek() { return this.heap[0] }",
      "  ",
      "  // heapifyUp和heapifyDown实现如上",
      "}",
      "```",
      "",
      "| 操作 | 时间 |",
      "|------|------|",
      "| 推入 | O(log n) |",
      "| 弹出 | O(log n) |",
      "| 窥视 | O(1) |",
      "",
      "## Top-K模式",
      "",
      "找k个最大（或最小）的元素。堆对此完美。",
      "",
      "**方法1：最大堆，提取k次**",
      "```javascript",
      "function findKLargest(nums, k) {",
      "  const heap = new MaxHeap()",
      "  for (const num of nums) heap.push(num)",
      "  const result = []",
      "  for (let i = 0; i < k; i++) result.push(heap.pop())",
      "  return result",
      "}",
      "// 时间：O(n log n)构建 + O(k log n)提取 = O(n log n)",
      "```",
      "",
      "**方法2：大小k的最小堆**",
      "```javascript",
      "function findKLargest(nums, k) {",
      "  const heap = new MinHeap()",
      "  for (const num of nums) {",
      "    heap.push(num)",
      "    if (heap.size() > k) heap.pop()  // 仅保留k个最大",
      "  }",
      "  return heap.heap",
      "}",
      "// 时间：O(n log k) - 如果k << n更好",
      "```",
      "",
      "在方法2中，我们维护k个最大元素的最小堆。这个堆的顶部是第k个最大。当新元素大于堆顶时，我们弹出小元素并插入大元素。",
      "",
      "## 何时使用堆",
      "",
      "- **调度**：任务的优先队列",
      "- **Top-K问题**：当k << n时最高效",
      "- **中位数查找**：结合最小和最大堆",
      "- **Dijkstra算法**：边权重的优先队列",
      "- **堆排序**：将无序数组转换为排序数组，O(n log n)"
    ].join('\n'),
  },
  leetcode: [
    { id: 215, title: 'Kth Largest Element in an Array', titleZh: '数组中的第K个最大元素', difficulty: 'Medium' },
    { id: 347, title: 'Top K Frequent Elements', titleZh: '前K个高频元素', difficulty: 'Medium' },
    { id: 295, title: 'Find Median from Data Stream', titleZh: '数据流的中位数', difficulty: 'Hard' },
  ],
}
