import type { TopicContent } from '../../types'

export const linkedListFundamentals: TopicContent = {
  id: 'linked-list-fundamentals',
  title: { en: 'Linked List Fundamentals', zh: '链表基础' },
  description: { en: 'Master node structure, common operations, dummy head, and two-pointer techniques', zh: '掌握节点结构、常见操作、虚拟头节点和双指针技巧' },
  timeEstimate: '40 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## Linked List vs Array",
      "",
      "Arrays provide fast random access but slow insertion/deletion in the middle. Linked lists are the opposite: slow access but fast modification if you're already at the target position.",
      "",
      "| Operation | Array | Linked List |",
      "|-----------|-------|-----------|",
      "| Access by index | O(1) | O(n) |",
      "| Append | O(1)* | O(1) if you have tail pointer |",
      "| Insert at position | O(n) | O(1) if you have the node before |",
      "| Delete at position | O(n) | O(1) if you have the node before |",
      "| Space | O(n) | O(n) (plus pointer overhead) |",
      "",
      "*Amortized - O(n) when full",
      "",
      "## The Node Structure",
      "",
      "A linked list node contains data and a pointer to the next node.",
      "",
      "```javascript",
      "class ListNode {",
      "  constructor(val = 0, next = null) {",
      "    this.val = val",
      "    this.next = next",
      "  }",
      "}",
      "```",
      "",
      "The head pointer points to the first node. The last node's next is null, marking the end.",
      "",
      "## The Dummy Head Trick",
      "",
      "When you need to modify the head of the list (remove it, insert before it), operations become awkward. If you insert at index 0, you need to update the head reference itself.",
      "",
      "The solution: create a dummy node that points to the real head. Now all insertions and deletions happen after a node, never replacing head itself.",
      "",
      "```javascript",
      "function removeElements(head, val) {",
      "  const dummy = new ListNode(0, head)",
      "  let current = dummy",
      "  while (current.next) {",
      "    if (current.next.val === val) {",
      "      current.next = current.next.next  // Skip the target node",
      "    } else {",
      "      current = current.next",
      "    }",
      "  }",
      "  return dummy.next  // Return the real head",
      "}",
      "```",
      "",
      "With the dummy head, we never modify head directly. We always operate on current.next, which is cleaner and handles edge cases automatically.",
      "",
      "## Two-Pointer Pattern: Find the Middle",
      "",
      "Use fast and slow pointers. Fast moves 2 steps per iteration, slow moves 1 step. When fast reaches the end, slow is at the middle.",
      "",
      "```javascript",
      "function findMiddle(head) {",
      "  let slow = head, fast = head",
      "  while (fast && fast.next) {",
      "    slow = slow.next",
      "    fast = fast.next.next",
      "  }",
      "  return slow  // Slow is at the middle",
      "}",
      "```",
      "",
      "For list [1, 2, 3, 4, 5]:",
      "- Slow ends up at node 3 (middle)",
      "- For even length [1, 2, 3, 4], slow ends up at node 3 (first of the two middle elements)",
      "",
      "Why it works: fast moves twice as fast, so when it finishes, slow is halfway through.",
      "",
      "## Two-Pointer Pattern: Detect Cycle",
      "",
      "If a linked list has a cycle, a fast pointer will eventually catch up to a slow pointer. If no cycle, fast reaches null.",
      "",
      "```javascript",
      "function hasCycle(head) {",
      "  let slow = head, fast = head",
      "  while (fast && fast.next) {",
      "    slow = slow.next",
      "    fast = fast.next.next",
      "    if (slow === fast) return true  // Cycle detected",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "This is the Floyd cycle detection algorithm. If they meet, there's a cycle. If fast exits the list, there's no cycle.",
      "",
      "## Two-Pointer Pattern: Find Nth From End",
      "",
      "Get the Nth node from the end without storing all nodes. Use two pointers: first pointer is N steps ahead. When the first reaches the end, the second is at position (length - N).",
      "",
      "```javascript",
      "function removeNthFromEnd(head, n) {",
      "  const dummy = new ListNode(0, head)",
      "  let first = dummy, second = dummy",
      "  ",
      "  // Move first n+1 steps ahead",
      "  for (let i = 0; i <= n; i++) {",
      "    first = first.next",
      "  }",
      "  ",
      "  // Move both pointers until first reaches null",
      "  while (first) {",
      "    first = first.next",
      "    second = second.next",
      "  }",
      "  ",
      "  // Remove the Nth node",
      "  second.next = second.next.next",
      "  return dummy.next",
      "}",
      "```",
      "",
      "Why start from dummy? So we can remove the head if needed (when n equals list length).",
      "",
      "## Common Linked List Operations",
      "",
      "**Reverse a list:**",
      "```javascript",
      "function reverse(head) {",
      "  let prev = null, current = head",
      "  while (current) {",
      "    const next = current.next  // Save next",
      "    current.next = prev        // Reverse the link",
      "    prev = current             // Move prev forward",
      "    current = next             // Move current forward",
      "  }",
      "  return prev",
      "}",
      "```",
      "",
      "**Merge two sorted lists:**",
      "```javascript",
      "function mergeTwoLists(list1, list2) {",
      "  const dummy = new ListNode(0)",
      "  let current = dummy",
      "  while (list1 && list2) {",
      "    if (list1.val < list2.val) {",
      "      current.next = list1",
      "      list1 = list1.next",
      "    } else {",
      "      current.next = list2",
      "      list2 = list2.next",
      "    }",
      "    current = current.next",
      "  }",
      "  current.next = list1 || list2",
      "  return dummy.next",
      "}",
      "```",
      "",
      "## Why Linked Lists Matter Less in Interviews",
      "",
      "Linked lists are less common in modern interviews because arrays with deques (double-ended queues) solve most problems as efficiently. However, linked lists teach pointer manipulation and help you understand how structures work under the hood. Master them once, recognize the patterns, then move on to more valuable topics."
    ].join('\n'),
    zh: [
      "## 链表vs数组",
      "",
      "数组提供快速随机访问但在中间插入/删除很慢。链表相反：访问慢但如果你已在目标位置修改快。",
      "",
      "| 操作 | 数组 | 链表 |",
      "|------|------|------|",
      "| 按索引访问 | O(1) | O(n) |",
      "| 追加 | O(1)* | O(1)如果有尾指针 |",
      "| 在位置插入 | O(n) | O(1)如果有前一个节点 |",
      "| 在位置删除 | O(n) | O(1)如果有前一个节点 |",
      "| 空间 | O(n) | O(n)（加指针开销） |",
      "",
      "*摊销 - 满时O(n)",
      "",
      "## 节点结构",
      "",
      "链表节点包含数据和指向下一个节点的指针。",
      "",
      "```javascript",
      "class ListNode {",
      "  constructor(val = 0, next = null) {",
      "    this.val = val",
      "    this.next = next",
      "  }",
      "}",
      "```",
      "",
      "head指针指向第一个节点。最后一个节点的next是null，标记结束。",
      "",
      "## 虚拟头节点技巧",
      "",
      "当你需要修改列表的头（删除它、在它前面插入），操作变得尴尬。如果在索引0插入，你需要更新head引用本身。",
      "",
      "解决方案：创建一个虚拟节点指向真实的头。现在所有插入和删除发生在节点后，永远不替换head本身。",
      "",
      "```javascript",
      "function removeElements(head, val) {",
      "  const dummy = new ListNode(0, head)",
      "  let current = dummy",
      "  while (current.next) {",
      "    if (current.next.val === val) {",
      "      current.next = current.next.next  // 跳过目标节点",
      "    } else {",
      "      current = current.next",
      "    }",
      "  }",
      "  return dummy.next  // 返回真实的头",
      "}",
      "```",
      "",
      "有虚拟头，我们永远不直接修改head。我们总在current.next操作，更干净且自动处理边界情况。",
      "",
      "## 双指针模式：找中间",
      "",
      "使用快慢指针。快每次迭代移动2步，慢移动1步。当快到达末尾，慢在中间。",
      "",
      "```javascript",
      "function findMiddle(head) {",
      "  let slow = head, fast = head",
      "  while (fast && fast.next) {",
      "    slow = slow.next",
      "    fast = fast.next.next",
      "  }",
      "  return slow  // 慢在中间",
      "}",
      "```",
      "",
      "对于列表[1, 2, 3, 4, 5]：",
      "- 慢到达节点3（中间）",
      "- 对于偶数长度[1, 2, 3, 4]，慢到达节点3（两个中间元素的第一个）",
      "",
      "为什么有效：快移动两倍快，所以完成时，慢在一半。",
      "",
      "## 双指针模式：检测循环",
      "",
      "如果链表有循环，快指针最终追上慢指针。如果无循环，快到达null。",
      "",
      "```javascript",
      "function hasCycle(head) {",
      "  let slow = head, fast = head",
      "  while (fast && fast.next) {",
      "    slow = slow.next",
      "    fast = fast.next.next",
      "    if (slow === fast) return true  // 检测到循环",
      "  }",
      "  return false",
      "}",
      "```",
      "",
      "这是Floyd循环检测算法。如果相遇，有循环。如果快离开列表，无循环。",
      "",
      "## 双指针模式：从末尾查找第N个",
      "",
      "获得末尾第N个节点而不存储所有节点。使用两个指针：第一个指针提前N步。第一个到达末尾时，第二个在位置（长度- N）。",
      "",
      "```javascript",
      "function removeNthFromEnd(head, n) {",
      "  const dummy = new ListNode(0, head)",
      "  let first = dummy, second = dummy",
      "  ",
      "  // 前移第一个n+1步",
      "  for (let i = 0; i <= n; i++) {",
      "    first = first.next",
      "  }",
      "  ",
      "  // 移动两个指针直到第一个到达null",
      "  while (first) {",
      "    first = first.next",
      "    second = second.next",
      "  }",
      "  ",
      "  // 删除第N个节点",
      "  second.next = second.next.next",
      "  return dummy.next",
      "}",
      "```",
      "",
      "为什么从虚拟开始？所以我们可以删除头如果需要（当n等于列表长度）。",
      "",
      "## 常见链表操作",
      "",
      "**反转列表：**",
      "```javascript",
      "function reverse(head) {",
      "  let prev = null, current = head",
      "  while (current) {",
      "    const next = current.next  // 保存next",
      "    current.next = prev        // 反转链接",
      "    prev = current             // prev前移",
      "    current = next             // current前移",
      "  }",
      "  return prev",
      "}",
      "```",
      "",
      "**合并两个排序列表：**",
      "```javascript",
      "function mergeTwoLists(list1, list2) {",
      "  const dummy = new ListNode(0)",
      "  let current = dummy",
      "  while (list1 && list2) {",
      "    if (list1.val < list2.val) {",
      "      current.next = list1",
      "      list1 = list1.next",
      "    } else {",
      "      current.next = list2",
      "      list2 = list2.next",
      "    }",
      "    current = current.next",
      "  }",
      "  current.next = list1 || list2",
      "  return dummy.next",
      "}",
      "```",
      "",
      "## 为什么链表在面试中不那么重要",
      "",
      "链表在现代面试中不太常见，因为带有deques（双端队列）的数组同样有效地解决大多数问题。然而，链表教指针操作并帮助理解结构如何工作的底层。掌握它们一次，识别模式，然后转向更有价值的主题。"
    ].join('\n'),
  },
  leetcode: [
    { id: 21, title: 'Merge Two Sorted Lists', titleZh: '合并两个有序链表', difficulty: 'Easy' },
    { id: 206, title: 'Reverse Linked List', titleZh: '反转链表', difficulty: 'Easy' },
    { id: 141, title: 'Linked List Cycle', titleZh: '环形链表', difficulty: 'Easy' },
    { id: 876, title: 'Middle of the Linked List', titleZh: '链表的中间结点', difficulty: 'Easy' },
    { id: 19, title: 'Remove Nth Node From End of List', titleZh: '删除链表的倒数第N个结点', difficulty: 'Medium' },
  ],
}
