import type { TopicContent } from '../../types'

export const bfsContent: TopicContent = {
  id: 'trees-bfs',
  title: { en: 'Level-Order Traversal (BFS)', zh: '层序遍历（BFS）' },
  description: { en: 'Master BFS patterns for level-order traversal, right side view, zigzag, and minimum depth', zh: '掌握层序遍历、右侧视图、之字形遍历和最小深度的BFS模式' },
  timeEstimate: '35 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## BFS vs DFS",
      "",
      "DFS (depth-first search) using recursion or stack goes deep into one branch before exploring others. BFS (breadth-first search) using a queue explores level by level. Different problems benefit from different approaches.",
      "",
      "| Property | DFS | BFS |",
      "|----------|-----|-----|",
      "| Data structure | Stack (implicit or explicit) | Queue |",
      "| Memory | Can be less if tree is very unbalanced | More uniform |",
      "| Best for | Checking deep properties | Level-by-level problems |",
      "",
      "## Level-Order Traversal Template",
      "",
      "The fundamental BFS template for trees: process all nodes at depth d before depth d+1.",
      "",
      "```javascript",
      "function levelOrder(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  while (queue.length) {",
      "    const levelSize = queue.length    // Key: number of nodes at this level",
      "    const currentLevel = []",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()      // Process current level",
      "      currentLevel.push(node.val)",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "    result.push(currentLevel)",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**Key insight**: Save `levelSize` at start of loop. This is how many nodes are currently at this level. Process exactly that many before moving to the next level.",
      "",
      "## Right Side View",
      "",
      "Given a tree, return the values you'd see if you looked from the right side. This is the last node at each level.",
      "",
      "```javascript",
      "function rightSideView(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      if (i === levelSize - 1) {          // Last node of this level",
      "        result.push(node.val)",
      "      }",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "By tracking `levelSize`, you know exactly which node is last. Capture its value.",
      "",
      "## Zigzag Level Order",
      "",
      "Same as level order, but alternate direction: level 0 left-to-right, level 1 right-to-left, level 2 left-to-right, etc.",
      "",
      "```javascript",
      "function zigzagLevelOrder(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  let leftToRight = true",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    const currentLevel = []",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      currentLevel.push(node.val)",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "    if (!leftToRight) {",
      "      currentLevel.reverse()              // Reverse for right-to-left",
      "    }",
      "    result.push(currentLevel)",
      "    leftToRight = !leftToRight",
      "}",
      "    return result",
      "}",
      "```",
      "",
      "Or collect in deque and use addFirst/addLast alternately for O(1) building.",
      "",
      "## Minimum Depth",
      "",
      "Find the shortest path from root to leaf. A leaf is a node with no children.",
      "",
      "```javascript",
      "function minDepth(root) {",
      "  if (!root) return 0",
      "  const queue = [root]",
      "  let depth = 0",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    depth++",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      if (!node.left && !node.right) {    // Leaf node found",
      "        return depth",
      "      }",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "  }",
      "  return depth",
      "}",
      "```",
      "",
      "BFS is perfect here! The first leaf you encounter is at minimum depth. With DFS, you'd have to explore the entire tree.",
      "",
      "## Why levelSize Matters",
      "",
      "Without tracking `levelSize`, you might mix nodes from different levels in your processing loop. This breaks level-based algorithms.",
      "",
      "```javascript",
      "// WRONG - might process next level's nodes",
      "while (queue.length) {",
      "  const node = queue.shift()",
      "  // Process node",
      "  if (node.left) queue.push(node.left)   // These are next level",
      "  if (node.right) queue.push(node.right)",
      "}",
      "",
      "// RIGHT - exactly control which level we process",
      "while (queue.length) {",
      "  const levelSize = queue.length  // Remember this level's size",
      "  for (let i = 0; i < levelSize; i++) {",
      "    const node = queue.shift()",
      "    // All nodes here are same level",
      "    if (node.left) queue.push(node.left)  // These go to next iteration",
      "    if (node.right) queue.push(node.right)",
      "  }",
      "}",
      "```",
      "",
      "## BFS for Shortest Path in Unweighted Graphs",
      "",
      "While this content focuses on trees, BFS is equally powerful for graphs. In unweighted graphs, the first time you reach a destination, you've found the shortest path.",
      "",
      "## Time and Space Complexity",
      "",
      "| Operation | Complexity | Note |",
      "|-----------|-----------|------|",
      "| Time | O(n) | Visit each node once |",
      "| Space | O(w) | w = maximum width (nodes at one level) |",
      "",
      "In a balanced tree, w ≈ n/2 (last level). In a skewed tree, w = 1 (queue only has one node at a time)."
    ].join('\n'),
    zh: [
      "## BFS vs DFS",
      "",
      "DFS（深度优先搜索）使用递归或栈深入一个分支后再探索其他。BFS（广度优先搜索）使用队列逐层探索。不同问题受益于不同方法。",
      "",
      "| 属性 | DFS | BFS |",
      "|------|-----|-----|",
      "| 数据结构 | 栈（隐式或显式） | 队列 |",
      "| 内存 | 如果树非常不平衡可能更少 | 更均匀 |",
      "| 最佳用途 | 检查深层属性 | 逐层问题 |",
      "",
      "## 层序遍历模板",
      "",
      "树的基本BFS模板：在深度d+1之前处理深度d的所有节点。",
      "",
      "```javascript",
      "function levelOrder(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  while (queue.length) {",
      "    const levelSize = queue.length    // 关键：此层的节点数",
      "    const currentLevel = []",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()      // 处理当前层",
      "      currentLevel.push(node.val)",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "    result.push(currentLevel)",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**关键洞察**：在循环开始保存`levelSize`。这是此层当前的节点数。在移到下一层之前处理确切这么多。",
      "",
      "## 右侧视图",
      "",
      "给定树，返回如果你从右侧看会看到的值。这是每层的最后一个节点。",
      "",
      "```javascript",
      "function rightSideView(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      if (i === levelSize - 1) {          // 这层的最后一个节点",
      "        result.push(node.val)",
      "      }",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "通过追踪`levelSize`，你知道哪个节点是最后的。捕获其值。",
      "",
      "## 之字形层序遍历",
      "",
      "与层序遍历相同，但交替方向：第0层左到右，第1层右到左，第2层左到右，等等。",
      "",
      "```javascript",
      "function zigzagLevelOrder(root) {",
      "  const result = []",
      "  const queue = [root]",
      "  let leftToRight = true",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    const currentLevel = []",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      currentLevel.push(node.val)",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "    if (!leftToRight) {",
      "      currentLevel.reverse()              // 为右到左反转",
      "    }",
      "    result.push(currentLevel)",
      "    leftToRight = !leftToRight",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "或用双端队列并交替使用addFirst/addLast以O(1)构建。",
      "",
      "## 最小深度",
      "",
      "找从根到叶的最短路径。叶是没有孩子的节点。",
      "",
      "```javascript",
      "function minDepth(root) {",
      "  if (!root) return 0",
      "  const queue = [root]",
      "  let depth = 0",
      "  while (queue.length) {",
      "    const levelSize = queue.length",
      "    depth++",
      "    for (let i = 0; i < levelSize; i++) {",
      "      const node = queue.shift()",
      "      if (!node.left && !node.right) {    // 叶节点找到",
      "        return depth",
      "      }",
      "      if (node.left) queue.push(node.left)",
      "      if (node.right) queue.push(node.right)",
      "    }",
      "  }",
      "  return depth",
      "}",
      "```",
      "",
      "BFS在这里完美！你遇到的第一个叶在最小深度。用DFS，你得探索整个树。",
      "",
      "## 为什么levelSize重要",
      "",
      "不追踪`levelSize`，你可能在处理循环中混合不同层的节点。这破坏了基于层的算法。",
      "",
      "```javascript",
      "// 错误 - 可能处理下一层的节点",
      "while (queue.length) {",
      "  const node = queue.shift()",
      "  // 处理节点",
      "  if (node.left) queue.push(node.left)   // 这些是下一层",
      "  if (node.right) queue.push(node.right)",
      "}",
      "",
      "// 正确 - 完全控制我们处理哪一层",
      "while (queue.length) {",
      "  const levelSize = queue.length  // 记住这层的大小",
      "  for (let i = 0; i < levelSize; i++) {",
      "    const node = queue.shift()",
      "    // 这里所有节点都是同层",
      "    if (node.left) queue.push(node.left)  // 这些去下一迭代",
      "    if (node.right) queue.push(node.right)",
      "  }",
      "}",
      "```",
      "",
      "## BFS用于无权图的最短路径",
      "",
      "虽然此内容关注树，BFS对图同样强大。在无权图中，你第一次到达目的地，你已找到最短路径。",
      "",
      "## 时间和空间复杂度",
      "",
      "| 操作 | 复杂度 | 注记 |",
      "|------|--------|------|",
      "| 时间 | O(n) | 访问每个节点一次 |",
      "| 空间 | O(w) | w = 最大宽度（一层的节点） |",
      "",
      "在平衡树中，w ≈ n/2（最后一层）。在倾斜树中，w = 1（队列一次只有一个节点）。"
    ].join('\n'),
  },
  leetcode: [
    { id: 102, title: 'Binary Tree Level Order Traversal', titleZh: '二叉树的层序遍历', difficulty: 'Medium' },
    { id: 103, title: 'Binary Tree Zigzag Level Order Traversal', titleZh: '二叉树的锯齿形层序遍历', difficulty: 'Medium' },
    { id: 199, title: 'Binary Tree Right Side View', titleZh: '二叉树的右视图', difficulty: 'Medium' },
    { id: 111, title: 'Minimum Depth of Binary Tree', titleZh: '二叉树的最小深度', difficulty: 'Easy' },
  ],
}
