import type { TopicContent } from '../../types'

export const traversalContent: TopicContent = {
  id: 'trees-traversal',
  title: { en: 'Tree Traversal Patterns', zh: '树的遍历模式' },
  description: { en: 'Master preorder, inorder, postorder in recursive and iterative forms. All tree problems are traversals.', zh: '掌握前序、中序、后序的递归和迭代形式。所有树问题都是遍历。' },
  timeEstimate: '45 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'treeTraversal',
  content: {
    en: [
      "## The Core Insight: Trees = Traversals",
      "",
      "Every single tree problem is fundamentally a tree traversal with some operation at each node. Want to find max depth? Traverse and track depth. Want to sum all values? Traverse and accumulate. Want to check if balanced? Traverse and validate.",
      "",
      "Master three traversals - preorder, inorder, postorder - and you've got 80% of tree problems solved.",
      "",
      "## The Three Traversals",
      "",
      "For a tree node, you have three moments: before visiting children, after the left child, and after all children. These correspond to the three traversals.",
      "",
      "```",
      "     1",
      "    / \\",
      "   2   3",
      "",
      "Preorder (root, left, right):   1, 2, 3",
      "Inorder (left, root, right):    2, 1, 3",
      "Postorder (left, right, root):  2, 3, 1",
      "```",
      "",
      "**Preorder**: Visit root first. Used when you need to process parent before children (like serialization).",
      "",
      "**Inorder**: Visit root between children. For binary search trees, inorder gives elements in sorted order!",
      "",
      "**Postorder**: Visit root last. Used when you need results from children first (like calculating tree height).",
      "",
      "## Recursive Traversals (Simple and Clean)",
      "",
      "```javascript",
      "function preorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    result.push(node.val)      // Process root",
      "    traverse(node.left)        // Traverse left",
      "    traverse(node.right)       // Traverse right",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "",
      "function inorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    traverse(node.left)        // Traverse left",
      "    result.push(node.val)      // Process root",
      "    traverse(node.right)       // Traverse right",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "",
      "function postorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    traverse(node.left)        // Traverse left",
      "    traverse(node.right)       // Traverse right",
      "    result.push(node.val)      // Process root",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "```",
      "",
      "## Iterative Traversals (Using Stack)",
      "",
      "Recursion uses the call stack implicitly. For iterative versions, use an explicit stack.",
      "",
      "**Preorder Iterative:**",
      "```javascript",
      "function preorderIterative(root) {",
      "  const result = []",
      "  const stack = [root]",
      "  while (stack.length) {",
      "    const node = stack.pop()",
      "    result.push(node.val)",
      "    if (node.right) stack.push(node.right)   // Push right first (LIFO)",
      "    if (node.left) stack.push(node.left)     // Then left",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "Key insight: push right first because stack is LIFO. We want left processed before right.",
      "",
      "**Inorder Iterative:**",
      "```javascript",
      "function inorderIterative(root) {",
      "  const result = []",
      "  const stack = []",
      "  let current = root",
      "  while (current || stack.length) {",
      "    while (current) {",
      "      stack.push(current)",
      "      current = current.left",
      "    }",
      "    current = stack.pop()",
      "    result.push(current.val)",
      "    current = current.right",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "Go left until you can't, then process the node, then go right.",
      "",
      "**Postorder Iterative:**",
      "```javascript",
      "function postorderIterative(root) {",
      "  const result = []",
      "  const stack = [root]",
      "  let last = null",
      "  while (stack.length) {",
      "    const current = stack[stack.length - 1]",
      "    if (!current.left && !current.right) {",
      "      // Leaf node",
      "      result.push(current.val)",
      "      stack.pop()",
      "    } else if (last === current.right || (!current.right && last === current.left)) {",
      "      // Both children processed (or no right child)",
      "      result.push(current.val)",
      "      stack.pop()",
      "      last = current",
      "    } else {",
      "      // Push children",
      "      if (current.right) stack.push(current.right)",
      "      if (current.left) stack.push(current.left)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "Postorder is trickiest: track which node was last processed to know when to process parent.",
      "",
      "## Real Problem: Maximum Depth",
      "",
      "Find the height of the tree. Must process children first.",
      "",
      "```javascript",
      "function maxDepth(root) {",
      "  if (!root) return 0",
      "  const leftDepth = maxDepth(root.left)",
      "  const rightDepth = maxDepth(root.right)",
      "  return Math.max(leftDepth, rightDepth) + 1",
      "}",
      "```",
      "",
      "This is postorder traversal! Process children, then use their results for parent.",
      "",
      "## Real Problem: Invert Binary Tree",
      "",
      "Swap left and right subtrees at every node.",
      "",
      "```javascript",
      "function invertTree(root) {",
      "  if (!root) return null",
      "  const temp = root.left",
      "  root.left = invertTree(root.right)",
      "  root.right = invertTree(temp)",
      "  return root",
      "}",
      "```",
      "",
      "Process children first (postorder), then swap at each node.",
      "",
      "## Traversal Decision Tree",
      "",
      "**Preorder** if:",
      "- You need parent's value before children",
      "- Serialization/creating copy",
      "- Expression trees",
      "",
      "**Inorder** if:",
      "- You need sorted order (BST problem)",
      "- Validating BST structure",
      "",
      "**Postorder** if:",
      "- You need results from children first",
      "- Calculating tree metrics (height, size)",
      "- Dependency resolution",
      "",
      "## Common Pattern: DFS with Accumulator",
      "",
      "Many problems traverse while accumulating state (sum, count, etc).",
      "",
      "```javascript",
      "function sumTree(root) {",
      "  function dfs(node) {",
      "    if (!node) return 0",
      "    return node.val + dfs(node.left) + dfs(node.right)",
      "  }",
      "  return dfs(root)",
      "}",
      "```",
      "",
      "The pattern: process current node, combine with children's results."
    ].join('\n'),
    zh: [
      "## 核心洞察：树 = 遍历",
      "",
      "每个树问题根本上是一个树遍历，在每个节点进行某些操作。想找最大深度？遍历并追踪深度。想对所有值求和？遍历并累积。想检查是否平衡？遍历并验证。",
      "",
      "掌握三种遍历 - 前序、中序、后序 - 你已解决80%的树问题。",
      "",
      "## 三种遍历",
      "",
      "对于树节点，你有三个时刻：访问子节点前、左子节点后、所有子节点后。这些对应三种遍历。",
      "",
      "```",
      "     1",
      "    / \\",
      "   2   3",
      "",
      "前序（根、左、右）：    1, 2, 3",
      "中序（左、根、右）：    2, 1, 3",
      "后序（左、右、根）：    2, 3, 1",
      "```",
      "",
      "**前序**：先访问根。当你需在孩子之前处理父节点时使用（像序列化）。",
      "",
      "**中序**：根在子节点之间访问。对于二叉搜索树，中序给出排序顺序！",
      "",
      "**后序**：最后访问根。当你需要先从孩子获得结果时使用（像计算树高）。",
      "",
      "## 递归遍历（简单干净）",
      "",
      "```javascript",
      "function preorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    result.push(node.val)      // 处理根",
      "    traverse(node.left)        // 遍历左",
      "    traverse(node.right)       // 遍历右",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "",
      "function inorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    traverse(node.left)        // 遍历左",
      "    result.push(node.val)      // 处理根",
      "    traverse(node.right)       // 遍历右",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "",
      "function postorder(root) {",
      "  const result = []",
      "  function traverse(node) {",
      "    if (!node) return",
      "    traverse(node.left)        // 遍历左",
      "    traverse(node.right)       // 遍历右",
      "    result.push(node.val)      // 处理根",
      "  }",
      "  traverse(root)",
      "  return result",
      "}",
      "```",
      "",
      "## 迭代遍历（使用栈）",
      "",
      "递归隐式使用调用栈。对于迭代版本，使用显式栈。",
      "",
      "**前序迭代：**",
      "```javascript",
      "function preorderIterative(root) {",
      "  const result = []",
      "  const stack = [root]",
      "  while (stack.length) {",
      "    const node = stack.pop()",
      "    result.push(node.val)",
      "    if (node.right) stack.push(node.right)   // 先push右（LIFO）",
      "    if (node.left) stack.push(node.left)     // 再push左",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "关键洞察：先push右是因为栈是LIFO。我们想左在右之前被处理。",
      "",
      "**中序迭代：**",
      "```javascript",
      "function inorderIterative(root) {",
      "  const result = []",
      "  const stack = []",
      "  let current = root",
      "  while (current || stack.length) {",
      "    while (current) {",
      "      stack.push(current)",
      "      current = current.left",
      "    }",
      "    current = stack.pop()",
      "    result.push(current.val)",
      "    current = current.right",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "向左走直到不能，然后处理节点，然后向右走。",
      "",
      "**后序迭代：**",
      "```javascript",
      "function postorderIterative(root) {",
      "  const result = []",
      "  const stack = [root]",
      "  let last = null",
      "  while (stack.length) {",
      "    const current = stack[stack.length - 1]",
      "    if (!current.left && !current.right) {",
      "      // 叶节点",
      "      result.push(current.val)",
      "      stack.pop()",
      "    } else if (last === current.right || (!current.right && last === current.left)) {",
      "      // 两个孩子都被处理（或没有右孩子）",
      "      result.push(current.val)",
      "      stack.pop()",
      "      last = current",
      "    } else {",
      "      // push孩子",
      "      if (current.right) stack.push(current.right)",
      "      if (current.left) stack.push(current.left)",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "后序最复杂：追踪最后被处理的节点以知道何时处理父节点。",
      "",
      "## 真实问题：最大深度",
      "",
      "找树的高度。必须先处理孩子。",
      "",
      "```javascript",
      "function maxDepth(root) {",
      "  if (!root) return 0",
      "  const leftDepth = maxDepth(root.left)",
      "  const rightDepth = maxDepth(root.right)",
      "  return Math.max(leftDepth, rightDepth) + 1",
      "}",
      "```",
      "",
      "这是后序遍历！处理孩子，然后用他们的结果用于父节点。",
      "",
      "## 真实问题：反转二叉树",
      "",
      "交换每个节点的左右子树。",
      "",
      "```javascript",
      "function invertTree(root) {",
      "  if (!root) return null",
      "  const temp = root.left",
      "  root.left = invertTree(root.right)",
      "  root.right = invertTree(temp)",
      "  return root",
      "}",
      "```",
      "",
      "先处理孩子（后序），然后在每个节点交换。",
      "",
      "## 遍历决策树",
      "",
      "**前序** 如果：",
      "- 你需要父的值在孩子之前",
      "- 序列化/创建副本",
      "- 表达式树",
      "",
      "**中序** 如果：",
      "- 你需要排序顺序（BST问题）",
      "- 验证BST结构",
      "",
      "**后序** 如果：",
      "- 你需要先从孩子获得结果",
      "- 计算树指标（高度、大小）",
      "- 依赖解析",
      "",
      "## 常见模式：带累积器的DFS",
      "",
      "许多问题遍历同时累积状态（和、计数等）。",
      "",
      "```javascript",
      "function sumTree(root) {",
      "  function dfs(node) {",
      "    if (!node) return 0",
      "    return node.val + dfs(node.left) + dfs(node.right)",
      "  }",
      "  return dfs(root)",
      "}",
      "```",
      "",
      "模式：处理当前节点，与孩子的结果结合。"
    ].join('\n'),
  },
  leetcode: [
    { id: 144, title: 'Binary Tree Preorder Traversal', titleZh: '二叉树前序遍历', difficulty: 'Easy' },
    { id: 94, title: 'Binary Tree Inorder Traversal', titleZh: '二叉树中序遍历', difficulty: 'Easy' },
    { id: 104, title: 'Maximum Depth of Binary Tree', titleZh: '二叉树的最大深度', difficulty: 'Easy' },
    { id: 226, title: 'Invert Binary Tree', titleZh: '翻转二叉树', difficulty: 'Easy' },
  ],
}
