import type { TopicContent } from '../../types'

export const sqlAggregation: TopicContent = {
  id: 'sql-aggregation',
  title: { en: 'Aggregation & GROUP BY', zh: '聚合函数与 GROUP BY' },
  description: {
    en: 'Learn COUNT, SUM, AVG, MIN, MAX, GROUP BY, and HAVING to summarize data',
    zh: '学习 COUNT、SUM、AVG、MIN、MAX、GROUP BY 和 HAVING 来汇总数据',
  },
  timeEstimate: '45 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## Aggregate Functions — Summarizing Data',
      '',
      'Aggregate functions collapse multiple rows into a single value. They are the backbone of reporting queries.',
      '',
      '```sql',
      '-- COUNT: number of rows (or non-NULL values)',
      'SELECT COUNT(*)         AS total_rows,',
      '       COUNT(manager_id) AS rows_with_manager   -- ignores NULLs',
      'FROM employees;',
      '',
      '-- SUM: total of a numeric column',
      'SELECT SUM(salary) AS total_payroll',
      'FROM employees;',
      '',
      '-- AVG: average value',
      'SELECT AVG(salary) AS avg_salary',
      'FROM employees;',
      '',
      '-- MIN / MAX: smallest and largest value',
      'SELECT MIN(hire_date) AS first_hire,',
      '       MAX(hire_date) AS latest_hire',
      'FROM employees;',
      '```',
      '',
      '**NULL behavior:** All aggregate functions ignore NULLs except `COUNT(*)`. This is a common source of bugs.',
      '',
      '```sql',
      '-- Table has 5 rows: salaries = [100, 200, NULL, 300, NULL]',
      'SELECT COUNT(*)         -- returns 5  (counts all rows)',
      '       COUNT(salary),   -- returns 3  (ignores NULLs)',
      '       SUM(salary),     -- returns 600 (ignores NULLs)',
      '       AVG(salary)      -- returns 200 (600/3, not 600/5!)',
      'FROM payroll;',
      '```',
      '',
      '## GROUP BY — Aggregate Per Group',
      '',
      'GROUP BY splits rows into groups and applies an aggregate function to each group.',
      '',
      '```sql',
      '-- How many employees are in each department?',
      'SELECT department,',
      '       COUNT(*) AS headcount',
      'FROM employees',
      'GROUP BY department',
      'ORDER BY headcount DESC;',
      '',
      '-- Average salary per department',
      'SELECT department,',
      '       AVG(salary) AS avg_salary,',
      '       MIN(salary) AS min_salary,',
      '       MAX(salary) AS max_salary',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '**Critical rule:** Every column in SELECT must either be:',
      '1. Listed in GROUP BY, OR',
      '2. Inside an aggregate function.',
      '',
      '```sql',
      '-- WRONG: name is neither in GROUP BY nor aggregated',
      'SELECT name, department, COUNT(*)',
      'FROM employees',
      'GROUP BY department;   -- ERROR in most databases',
      '',
      '-- CORRECT',
      'SELECT department, COUNT(*)',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '## HAVING — Filter After Grouping',
      '',
      'WHERE filters individual rows before grouping. HAVING filters groups after aggregation.',
      '',
      '```sql',
      '-- Find departments with more than 5 employees',
      'SELECT department, COUNT(*) AS headcount',
      'FROM employees',
      'GROUP BY department',
      'HAVING COUNT(*) > 5;',
      '',
      '-- Find departments where average salary exceeds $90,000',
      'SELECT department, AVG(salary) AS avg_salary',
      'FROM employees',
      'GROUP BY department',
      'HAVING AVG(salary) > 90000',
      'ORDER BY avg_salary DESC;',
      '```',
      '',
      '**WHERE vs HAVING:**',
      '',
      '```sql',
      '-- WHERE: filters rows BEFORE grouping (cannot reference aggregates)',
      '-- HAVING: filters groups AFTER aggregation (can reference aggregates)',
      '',
      '-- Example: average salary of Engineering employees, but only',
      '-- report the result if that average exceeds $80,000',
      'SELECT department, AVG(salary)',
      'FROM employees',
      "WHERE department = 'Engineering'   -- filter rows first",
      'GROUP BY department',
      'HAVING AVG(salary) > 80000;        -- then filter the group',
      '```',
      '',
      '## Grouping by Multiple Columns',
      '',
      '```sql',
      '-- Count employees per department per year',
      'SELECT department,',
      '       YEAR(hire_date) AS hire_year,',
      '       COUNT(*) AS hires',
      'FROM employees',
      'GROUP BY department, YEAR(hire_date)',
      'ORDER BY department, hire_year;',
      '```',
      '',
      '## COUNT DISTINCT — Unique Values',
      '',
      '```sql',
      '-- How many distinct departments exist?',
      'SELECT COUNT(DISTINCT department) AS dept_count',
      'FROM employees;',
      '',
      '-- How many distinct products did each customer buy?',
      'SELECT customer_id,',
      '       COUNT(DISTINCT product_id) AS unique_products',
      'FROM orders',
      'GROUP BY customer_id;',
      '```',
      '',
      '## Conditional Aggregation with CASE',
      '',
      'Aggregate only a subset of rows without a subquery.',
      '',
      '```sql',
      '-- Count employees by department in a single row (pivot-style)',
      "SELECT COUNT(CASE WHEN department = 'Engineering' THEN 1 END) AS eng_count,",
      "       COUNT(CASE WHEN department = 'Product'     THEN 1 END) AS prod_count,",
      "       COUNT(CASE WHEN department = 'Design'      THEN 1 END) AS design_count",
      'FROM employees;',
      '',
      '-- Sum of salaries only for active employees',
      "SELECT SUM(CASE WHEN status = 'active' THEN salary ELSE 0 END) AS active_payroll",
      'FROM employees;',
      '```',
      '',
      '## GROUP BY ROLLUP and CUBE (Advanced)',
      '',
      '```sql',
      '-- ROLLUP: subtotals + grand total',
      'SELECT department, job_title, SUM(salary)',
      'FROM employees',
      'GROUP BY ROLLUP(department, job_title);',
      '-- Produces: group by (dept, job), group by (dept), grand total',
      '',
      '-- CUBE: all possible grouping combinations',
      'SELECT department, job_title, SUM(salary)',
      'FROM employees',
      'GROUP BY CUBE(department, job_title);',
      '```',
      '',
      '## Exercise Set 3 — Aggregation',
      '',
      '```sql',
      '-- Schema',
      'CREATE TABLE employees (',
      '  emp_id     INT, name VARCHAR(100), department VARCHAR(50),',
      '  salary DECIMAL(10,2), hire_date DATE, status VARCHAR(10)',
      ');',
      'CREATE TABLE orders (',
      '  order_id INT, customer_id INT, amount DECIMAL(10,2), order_date DATE',
      ');',
      '```',
      '',
      '**Exercise 1 (Easy):** How many employees are in each department? Sort by count descending.',
      '',
      '```sql',
      'SELECT department, COUNT(*) AS headcount',
      'FROM employees',
      'GROUP BY department',
      'ORDER BY headcount DESC;',
      '```',
      '',
      '**Exercise 2 (Easy):** Find the total, average, min, and max salary across all employees.',
      '',
      '```sql',
      'SELECT SUM(salary)  AS total_payroll,',
      '       AVG(salary)  AS avg_salary,',
      '       MIN(salary)  AS min_salary,',
      '       MAX(salary)  AS max_salary',
      'FROM employees;',
      '```',
      '',
      '**Exercise 3 (Medium):** List departments where the average salary is above $75,000, showing department name and average salary.',
      '',
      '```sql',
      'SELECT department, AVG(salary) AS avg_salary',
      'FROM employees',
      'GROUP BY department',
      'HAVING AVG(salary) > 75000',
      'ORDER BY avg_salary DESC;',
      '```',
      '',
      '**Exercise 4 (Medium):** Find customers who have placed more than 3 orders AND whose total order amount exceeds $1,000.',
      '',
      '```sql',
      'SELECT customer_id,',
      '       COUNT(*)      AS order_count,',
      '       SUM(amount)   AS total_spent',
      'FROM orders',
      'GROUP BY customer_id',
      'HAVING COUNT(*) > 3',
      '   AND SUM(amount) > 1000',
      'ORDER BY total_spent DESC;',
      '```',
      '',
      '**Exercise 5 (Medium — LeetCode 182 style):** Find all email addresses that appear more than once in a users table.',
      '',
      '```sql',
      'SELECT email, COUNT(*) AS cnt',
      'FROM users',
      'GROUP BY email',
      'HAVING COUNT(*) > 1;',
      '```',
    ].join('\n'),
    zh: [
      '## 聚合函数——汇总数据',
      '',
      '聚合函数将多行压缩为一个值。它们是报表查询的核心。',
      '',
      '```sql',
      '-- COUNT：行数（或非 NULL 值的个数）',
      'SELECT COUNT(*)          AS 总行数,',
      '       COUNT(manager_id) AS 有经理的行数   -- 忽略 NULL',
      'FROM employees;',
      '',
      '-- SUM：数值列的总和',
      'SELECT SUM(salary) AS 工资总额',
      'FROM employees;',
      '',
      '-- AVG：平均值',
      'SELECT AVG(salary) AS 平均工资',
      'FROM employees;',
      '',
      '-- MIN / MAX：最小值和最大值',
      'SELECT MIN(hire_date) AS 最早入职,',
      '       MAX(hire_date) AS 最近入职',
      'FROM employees;',
      '```',
      '',
      '**NULL 的行为：** 除 `COUNT(*)` 外，所有聚合函数都忽略 NULL。这是常见的 bug 来源。',
      '',
      '```sql',
      '-- 表有 5 行：工资 = [100, 200, NULL, 300, NULL]',
      'SELECT COUNT(*),     -- 返回 5  （计算所有行）',
      '       COUNT(salary), -- 返回 3  （忽略 NULL）',
      '       SUM(salary),  -- 返回 600（忽略 NULL）',
      '       AVG(salary)   -- 返回 200（600/3，而不是 600/5！）',
      'FROM payroll;',
      '```',
      '',
      '## GROUP BY——按组聚合',
      '',
      'GROUP BY 将行分成组，并对每组应用聚合函数。',
      '',
      '```sql',
      '-- 每个部门有多少员工？',
      'SELECT department,',
      '       COUNT(*) AS 人数',
      'FROM employees',
      'GROUP BY department',
      'ORDER BY 人数 DESC;',
      '',
      '-- 每个部门的平均薪资',
      'SELECT department,',
      '       AVG(salary) AS 平均薪资,',
      '       MIN(salary) AS 最低薪资,',
      '       MAX(salary) AS 最高薪资',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '**关键规则：** SELECT 中的每个列必须：',
      '1. 在 GROUP BY 中列出，或者',
      '2. 在聚合函数内部。',
      '',
      '## HAVING——分组后过滤',
      '',
      'WHERE 在分组**之前**过滤单行。HAVING 在聚合**之后**过滤组。',
      '',
      '```sql',
      '-- 找出员工超过 5 人的部门',
      'SELECT department, COUNT(*) AS 人数',
      'FROM employees',
      'GROUP BY department',
      'HAVING COUNT(*) > 5;',
      '',
      '-- 找出平均薪资超过 $90,000 的部门',
      'SELECT department, AVG(salary) AS 平均薪资',
      'FROM employees',
      'GROUP BY department',
      'HAVING AVG(salary) > 90000',
      'ORDER BY 平均薪资 DESC;',
      '```',
      '',
      '**WHERE vs HAVING：**',
      '',
      '```',
      'WHERE:  在分组之前过滤行（不能引用聚合函数）',
      'HAVING: 在聚合之后过滤组（可以引用聚合函数）',
      '```',
      '',
      '## 条件聚合与 CASE',
      '',
      '不用子查询，只聚合部分行。',
      '',
      '```sql',
      '-- 单行统计各部门人数（透视风格）',
      "SELECT COUNT(CASE WHEN department = 'Engineering' THEN 1 END) AS 工程部人数,",
      "       COUNT(CASE WHEN department = 'Product'     THEN 1 END) AS 产品部人数,",
      "       COUNT(CASE WHEN department = 'Design'      THEN 1 END) AS 设计部人数",
      'FROM employees;',
      '```',
      '',
      '## 练习题 3——聚合',
      '',
      '**练习 1（简单）：** 每个部门有多少员工？按数量降序排列。',
      '',
      '```sql',
      'SELECT department, COUNT(*) AS 人数',
      'FROM employees',
      'GROUP BY department',
      'ORDER BY 人数 DESC;',
      '```',
      '',
      '**练习 2（中等）：** 列出平均薪资超过 $75,000 的部门。',
      '',
      '```sql',
      'SELECT department, AVG(salary) AS 平均薪资',
      'FROM employees',
      'GROUP BY department',
      'HAVING AVG(salary) > 75000',
      'ORDER BY 平均薪资 DESC;',
      '```',
      '',
      '**练习 3（中等）：** 找出下单超过 3 次且总金额超过 $1,000 的客户。',
      '',
      '```sql',
      'SELECT customer_id,',
      '       COUNT(*)    AS 订单数,',
      '       SUM(amount) AS 总消费',
      'FROM orders',
      'GROUP BY customer_id',
      'HAVING COUNT(*) > 3',
      '   AND SUM(amount) > 1000',
      'ORDER BY 总消费 DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 182, title: 'Duplicate Emails', titleZh: '查找重复的电子邮箱', difficulty: 'Easy' },
    { id: 596, title: 'Classes More Than 5 Students', titleZh: '超过5名学生的课', difficulty: 'Easy' },
    { id: 586, title: 'Customer Placing the Largest Number of Orders', titleZh: '订单最多的客户', difficulty: 'Easy' },
    { id: 570, title: 'Managers with at Least 5 Direct Reports', titleZh: '至少有5名直接下属的经理', difficulty: 'Medium' },
  ],
}
