import type { TopicContent } from '../../types'

export const sqlBasics: TopicContent = {
  id: 'sql-basics',
  title: { en: 'SQL Fundamentals', zh: 'SQL 基础' },
  description: {
    en: 'Master SELECT, WHERE, ORDER BY, and LIMIT — the building blocks of every SQL query',
    zh: '掌握 SELECT、WHERE、ORDER BY 和 LIMIT——每条 SQL 查询的基石',
  },
  timeEstimate: '45 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## What Is SQL?',
      '',
      'SQL (Structured Query Language) is a language for working with relational databases. A relational database stores data in **tables** — rows and columns, like a spreadsheet. You query those tables with SQL to retrieve, filter, sort, and transform data.',
      '',
      'Every query starts with a simple mental model: "I want **which columns** FROM **which table** WHERE **some condition is true**."',
      '',
      '## The SELECT Statement',
      '',
      'The most fundamental SQL statement retrieves data from a table.',
      '',
      '```sql',
      '-- Select specific columns',
      'SELECT first_name, last_name, salary',
      'FROM employees;',
      '',
      '-- Select all columns (use sparingly in production)',
      'SELECT *',
      'FROM employees;',
      '',
      '-- Give columns aliases for readability',
      'SELECT first_name AS name, salary AS annual_pay',
      'FROM employees;',
      '```',
      '',
      '**Key rule:** SQL keywords are case-insensitive (`SELECT` = `select`), but by convention keywords are uppercase and table/column names are lowercase.',
      '',
      '## Filtering with WHERE',
      '',
      'WHERE narrows down which rows are returned. Think of it as a row-level filter applied before any aggregation.',
      '',
      '```sql',
      '-- Comparison operators: =, <>, !=, <, >, <=, >=',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = 'Engineering';",
      '',
      '-- Multiple conditions with AND / OR',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = 'Engineering'",
      '  AND salary > 80000;',
      '',
      '-- IN: shorthand for multiple OR conditions',
      'SELECT name, department',
      'FROM employees',
      "WHERE department IN ('Engineering', 'Product', 'Design');",
      '',
      '-- BETWEEN: inclusive range check',
      'SELECT name, hire_date',
      'FROM employees',
      "WHERE hire_date BETWEEN '2020-01-01' AND '2022-12-31';",
      '',
      '-- LIKE: pattern matching',
      "-- % matches any sequence of characters, _ matches exactly one character",
      'SELECT name',
      'FROM employees',
      "WHERE name LIKE 'A%';    -- starts with A",
      "-- WHERE name LIKE '%son'; -- ends with son",
      "-- WHERE name LIKE '_a%'; -- second character is 'a'",
      '',
      '-- IS NULL / IS NOT NULL',
      'SELECT name',
      'FROM employees',
      'WHERE manager_id IS NULL;  -- top-level managers',
      '```',
      '',
      '## Sorting with ORDER BY',
      '',
      'ORDER BY controls the sequence of returned rows. Without it, row order is undefined.',
      '',
      '```sql',
      '-- Ascending (default)',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary;         -- lowest first',
      '',
      '-- Descending',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC;    -- highest first',
      '',
      '-- Multi-column sort: sort by department A-Z, then salary high-to-low within each dept',
      'SELECT name, department, salary',
      'FROM employees',
      'ORDER BY department ASC, salary DESC;',
      '',
      '-- You can ORDER BY column position (not recommended but valid)',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY 2 DESC;   -- 2nd selected column = salary',
      '```',
      '',
      '## Limiting Results',
      '',
      'Different databases have different syntax for limiting rows returned.',
      '',
      '```sql',
      '-- Standard SQL (PostgreSQL, MySQL 8+, SQLite)',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'LIMIT 10;             -- top 10 earners',
      '',
      '-- With offset: skip first N rows',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'LIMIT 10 OFFSET 20;   -- rows 21-30',
      '',
      '-- SQL Server / MS Access syntax',
      'SELECT TOP 10 name, salary',
      'FROM employees',
      'ORDER BY salary DESC;',
      '',
      '-- Oracle SQL syntax (see Oracle SQL chapter for modern ROW_NUMBER approach)',
      'SELECT name, salary',
      'FROM employees',
      'WHERE ROWNUM <= 10',
      'ORDER BY salary DESC;  -- WARNING: ROWNUM applied before ORDER BY in Oracle!',
      '```',
      '',
      '## Removing Duplicates with DISTINCT',
      '',
      '```sql',
      '-- Without DISTINCT: may return duplicates',
      'SELECT department FROM employees;',
      '',
      '-- With DISTINCT: unique departments only',
      'SELECT DISTINCT department FROM employees;',
      '',
      '-- DISTINCT across multiple columns: unique combinations',
      'SELECT DISTINCT department, job_title FROM employees;',
      '```',
      '',
      '## Column Expressions and Calculations',
      '',
      'You can compute values directly in SELECT.',
      '',
      '```sql',
      '-- Arithmetic',
      'SELECT name,',
      '       salary,',
      '       salary * 1.10 AS salary_after_raise,',
      '       salary * 12   AS annual_salary',
      'FROM employees;',
      '',
      '-- String concatenation',
      "SELECT first_name || ' ' || last_name AS full_name  -- Standard SQL / Oracle",
      'FROM employees;',
      '',
      "-- MySQL / SQL Server use CONCAT()",
      "SELECT CONCAT(first_name, ' ', last_name) AS full_name",
      'FROM employees;',
      '',
      '-- CASE expression: conditional logic inline',
      'SELECT name,',
      '       salary,',
      '       CASE',
      "         WHEN salary >= 100000 THEN 'Senior'",
      "         WHEN salary >= 70000  THEN 'Mid'",
      "         ELSE                       'Junior'",
      '       END AS level',
      'FROM employees;',
      '```',
      '',
      '## Exercise Set 1 — SQL Basics',
      '',
      'Use this schema to practice:',
      '',
      '```sql',
      '-- Schema',
      'CREATE TABLE employees (',
      '  emp_id     INT PRIMARY KEY,',
      '  name       VARCHAR(100),',
      '  department VARCHAR(50),',
      '  salary     DECIMAL(10,2),',
      '  hire_date  DATE,',
      '  manager_id INT',
      ');',
      '```',
      '',
      '**Exercise 1 (Easy):** List the names and salaries of all employees in the Engineering department, sorted by salary from highest to lowest.',
      '',
      '```sql',
      '-- Your answer:',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = 'Engineering'",
      'ORDER BY salary DESC;',
      '```',
      '',
      '**Exercise 2 (Easy):** Find all employees hired in 2021 or 2022.',
      '',
      '```sql',
      'SELECT name, hire_date',
      'FROM employees',
      "WHERE hire_date BETWEEN '2021-01-01' AND '2022-12-31'",
      'ORDER BY hire_date;',
      '```',
      '',
      '**Exercise 3 (Medium):** Show each employee\'s name, their salary, and a "Pay Grade" column: "High" if salary >= 100000, "Mid" if >= 60000, otherwise "Low". Sort by Pay Grade then salary descending.',
      '',
      '```sql',
      'SELECT name,',
      '       salary,',
      '       CASE',
      "         WHEN salary >= 100000 THEN 'High'",
      "         WHEN salary >= 60000  THEN 'Mid'",
      "         ELSE 'Low'",
      '       END AS pay_grade',
      'FROM employees',
      "ORDER BY pay_grade, salary DESC;",
      '```',
      '',
      '**Exercise 4 (Medium):** List employees whose names start with "J" or end with "son", but exclude anyone in the HR department.',
      '',
      '```sql',
      'SELECT name, department',
      'FROM employees',
      "WHERE (name LIKE 'J%' OR name LIKE '%son')",
      "  AND department <> 'HR'",
      'ORDER BY name;',
      '```',
      '',
      '## Execution Order — What Runs When',
      '',
      'SQL has a logical execution order different from the written order. Understanding this prevents confusion:',
      '',
      '```',
      '1. FROM        — identify source table(s)',
      '2. WHERE       — filter rows',
      '3. GROUP BY    — group rows (covered in Aggregation chapter)',
      '4. HAVING      — filter groups',
      '5. SELECT      — compute output columns',
      '6. DISTINCT    — remove duplicates',
      '7. ORDER BY    — sort results',
      '8. LIMIT       — cut down row count',
      '```',
      '',
      'This is why you **cannot use a SELECT alias in a WHERE clause** — WHERE runs before SELECT!',
      '',
      '```sql',
      '-- WRONG: annual_pay is not yet defined when WHERE runs',
      'SELECT salary * 12 AS annual_pay',
      'FROM employees',
      'WHERE annual_pay > 100000;   -- ERROR',
      '',
      '-- CORRECT: repeat the expression, or wrap in a subquery',
      'SELECT salary * 12 AS annual_pay',
      'FROM employees',
      'WHERE salary * 12 > 100000;',
      '```',
    ].join('\n'),
    zh: [
      '## 什么是 SQL？',
      '',
      'SQL（结构化查询语言）是操作关系型数据库的语言。关系型数据库将数据存储在**表**中——行和列，就像电子表格。你用 SQL 查询这些表，以检索、筛选、排序和转换数据。',
      '',
      '每个查询都从一个简单的心理模型开始："我想要**哪些列** FROM **哪个表** WHERE **某个条件为真**。"',
      '',
      '## SELECT 语句',
      '',
      '最基本的 SQL 语句，从表中检索数据。',
      '',
      '```sql',
      '-- 选择特定列',
      'SELECT first_name, last_name, salary',
      'FROM employees;',
      '',
      '-- 选择所有列（生产环境慎用）',
      'SELECT *',
      'FROM employees;',
      '',
      '-- 给列设置别名以提高可读性',
      'SELECT first_name AS 姓名, salary AS 年薪',
      'FROM employees;',
      '```',
      '',
      '**关键规则：** SQL 关键字不区分大小写（`SELECT` = `select`），但按惯例关键字大写，表名/列名小写。',
      '',
      '## 用 WHERE 过滤',
      '',
      'WHERE 缩小返回哪些行的范围。把它理解为在任何聚合之前应用的行级过滤器。',
      '',
      '```sql',
      '-- 比较运算符：=, <>, !=, <, >, <=, >=',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = '工程部';",
      '',
      '-- 多个条件用 AND / OR',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = '工程部'",
      '  AND salary > 80000;',
      '',
      '-- IN：多个 OR 条件的简写',
      'SELECT name, department',
      'FROM employees',
      "WHERE department IN ('工程部', '产品部', '设计部');",
      '',
      '-- BETWEEN：包含边界的范围检查',
      'SELECT name, hire_date',
      'FROM employees',
      "WHERE hire_date BETWEEN '2020-01-01' AND '2022-12-31';",
      '',
      '-- LIKE：模式匹配',
      '-- % 匹配任意字符序列，_ 精确匹配一个字符',
      'SELECT name',
      'FROM employees',
      "WHERE name LIKE 'A%';    -- 以 A 开头",
      '',
      '-- IS NULL / IS NOT NULL',
      'SELECT name',
      'FROM employees',
      'WHERE manager_id IS NULL;  -- 顶级管理者',
      '```',
      '',
      '## 用 ORDER BY 排序',
      '',
      'ORDER BY 控制返回行的顺序。没有它，行的顺序是未定义的。',
      '',
      '```sql',
      '-- 升序（默认）',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary;         -- 最低在前',
      '',
      '-- 降序',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC;    -- 最高在前',
      '',
      '-- 多列排序：按部门 A-Z 排序，然后在每个部门内按薪资从高到低',
      'SELECT name, department, salary',
      'FROM employees',
      'ORDER BY department ASC, salary DESC;',
      '```',
      '',
      '## 限制结果行数',
      '',
      '不同数据库有不同的限制返回行数的语法。',
      '',
      '```sql',
      '-- 标准 SQL（PostgreSQL、MySQL 8+、SQLite）',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'LIMIT 10;             -- 薪资最高的 10 人',
      '',
      '-- 带偏移量：跳过前 N 行',
      'LIMIT 10 OFFSET 20;   -- 第 21-30 行',
      '',
      '-- Oracle SQL 语法（Oracle 章节会介绍现代 ROW_NUMBER 方法）',
      'SELECT name, salary FROM employees',
      'WHERE ROWNUM <= 10 ORDER BY salary DESC;  -- 警告：Oracle 中 ROWNUM 在 ORDER BY 之前执行！',
      '```',
      '',
      '## 用 DISTINCT 去重',
      '',
      '```sql',
      '-- 不加 DISTINCT：可能返回重复',
      'SELECT department FROM employees;',
      '',
      '-- 加 DISTINCT：只返回唯一部门',
      'SELECT DISTINCT department FROM employees;',
      '```',
      '',
      '## 列表达式和计算',
      '',
      '```sql',
      '-- 算术运算',
      'SELECT name,',
      '       salary,',
      '       salary * 1.10 AS 加薪后薪资,',
      '       salary * 12   AS 年薪',
      'FROM employees;',
      '',
      '-- CASE 表达式：内联条件逻辑',
      'SELECT name,',
      '       salary,',
      '       CASE',
      "         WHEN salary >= 100000 THEN '高级'",
      "         WHEN salary >= 70000  THEN '中级'",
      "         ELSE                       '初级'",
      '       END AS 级别',
      'FROM employees;',
      '```',
      '',
      '## 练习题 1 — SQL 基础',
      '',
      '使用以下表结构练习：',
      '',
      '```sql',
      'CREATE TABLE employees (',
      '  emp_id     INT PRIMARY KEY,',
      '  name       VARCHAR(100),',
      '  department VARCHAR(50),',
      '  salary     DECIMAL(10,2),',
      '  hire_date  DATE,',
      '  manager_id INT',
      ');',
      '```',
      '',
      '**练习 1（简单）：** 列出工程部所有员工的姓名和薪资，按薪资从高到低排序。',
      '',
      '```sql',
      'SELECT name, salary',
      'FROM employees',
      "WHERE department = 'Engineering'",
      'ORDER BY salary DESC;',
      '```',
      '',
      '**练习 2（简单）：** 查找 2021 年或 2022 年入职的所有员工。',
      '',
      '```sql',
      'SELECT name, hire_date',
      'FROM employees',
      "WHERE hire_date BETWEEN '2021-01-01' AND '2022-12-31'",
      'ORDER BY hire_date;',
      '```',
      '',
      '**练习 3（中等）：** 显示每位员工的姓名、薪资和"薪资级别"列：薪资 >= 100000 为"高"，>= 60000 为"中"，否则为"低"。',
      '',
      '```sql',
      'SELECT name,',
      '       salary,',
      '       CASE',
      "         WHEN salary >= 100000 THEN '高'",
      "         WHEN salary >= 60000  THEN '中'",
      "         ELSE '低'",
      '       END AS 薪资级别',
      'FROM employees',
      'ORDER BY 薪资级别, salary DESC;',
      '```',
      '',
      '## 执行顺序——谁先执行',
      '',
      'SQL 的逻辑执行顺序与书写顺序不同。理解这一点可以避免困惑：',
      '',
      '```',
      '1. FROM        — 确定源表',
      '2. WHERE       — 过滤行',
      '3. GROUP BY    — 对行分组（聚合章节介绍）',
      '4. HAVING      — 过滤组',
      '5. SELECT      — 计算输出列',
      '6. DISTINCT    — 去重',
      '7. ORDER BY    — 排序结果',
      '8. LIMIT       — 减少行数',
      '```',
      '',
      '这就是为什么**不能在 WHERE 子句中使用 SELECT 别名**——WHERE 在 SELECT 之前运行！',
      '',
      '```sql',
      '-- 错误：WHERE 运行时 annual_pay 还未定义',
      'SELECT salary * 12 AS annual_pay',
      'FROM employees',
      'WHERE annual_pay > 100000;   -- 报错',
      '',
      '-- 正确：重复表达式，或包装在子查询中',
      'SELECT salary * 12 AS annual_pay',
      'FROM employees',
      'WHERE salary * 12 > 100000;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 595, title: 'Big Countries', titleZh: '大的国家', difficulty: 'Easy' },
    { id: 620, title: 'Not Boring Movies', titleZh: '有趣的电影', difficulty: 'Easy' },
    { id: 584, title: 'Find Customer Referee', titleZh: '寻找用户推荐人', difficulty: 'Easy' },
    { id: 627, title: 'Swap Salary', titleZh: '变更性别', difficulty: 'Easy' },
  ],
}
