import type { TopicContent } from '../../types'

export const sqlJoins: TopicContent = {
  id: 'sql-joins',
  title: { en: 'JOINs — Combining Tables', zh: 'JOIN——合并多表' },
  description: {
    en: 'Understand INNER, LEFT, RIGHT, FULL OUTER, and self JOINs with visual examples',
    zh: '通过可视化示例理解 INNER、LEFT、RIGHT、FULL OUTER 和自连接',
  },
  timeEstimate: '50 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## Why JOINs Exist',
      '',
      'Relational databases store data in separate tables to avoid duplication. An **employees** table stores employee info; an **orders** table stores orders. A JOIN combines rows from two or more tables based on a related column — usually a foreign key relationship.',
      '',
      '```',
      'employees table          orders table',
      '┌────┬────────┐          ┌────┬────────┬──────────┐',
      '│ id │ name   │          │ id │ emp_id │ amount   │',
      '├────┼────────┤          ├────┼────────┼──────────┤',
      '│  1 │ Alice  │          │101 │   1    │  500.00  │',
      '│  2 │ Bob    │          │102 │   1    │  200.00  │',
      '│  3 │ Carol  │          │103 │   2    │  800.00  │',
      '│  4 │ Dave   │          └────┴────────┴──────────┘',
      '└────┴────────┘          (Dave has no orders)',
      '```',
      '',
      '## INNER JOIN — Only Matching Rows',
      '',
      'Returns rows where the join condition matches in **both** tables. Non-matching rows are excluded.',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'INNER JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- Result:',
      '-- name   | amount',
      '-- -------+--------',
      '-- Alice  | 500.00',
      '-- Alice  | 200.00',
      '-- Bob    | 800.00',
      '-- (Carol and Dave are excluded — no matching orders)',
      '```',
      '',
      'The keyword `INNER` is optional — `JOIN` alone means INNER JOIN.',
      '',
      '## LEFT JOIN — Keep All Left Rows',
      '',
      'Returns ALL rows from the left table, plus matching rows from the right. Where there is no match, right-side columns are NULL.',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'LEFT JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- Result:',
      '-- name   | amount',
      '-- -------+--------',
      '-- Alice  | 500.00',
      '-- Alice  | 200.00',
      '-- Bob    | 800.00',
      '-- Carol  | NULL    ← Carol has no orders, but still appears',
      '-- Dave   | NULL    ← Dave has no orders, but still appears',
      '```',
      '',
      '**Classic use case:** Find employees who have never placed an order.',
      '',
      '```sql',
      'SELECT e.name',
      'FROM employees e',
      'LEFT JOIN orders o ON e.id = o.emp_id',
      'WHERE o.emp_id IS NULL;   -- NULL means no match found',
      '',
      '-- Result: Carol, Dave',
      '```',
      '',
      '## RIGHT JOIN — Keep All Right Rows',
      '',
      'Mirror of LEFT JOIN — keeps all rows from the right table. Rarely used in practice; most developers rewrite as a LEFT JOIN by swapping table order.',
      '',
      '```sql',
      '-- These two queries return identical results:',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'RIGHT JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- Equivalent LEFT JOIN (preferred style):',
      'SELECT e.name, o.amount',
      'FROM orders o',
      'LEFT JOIN employees e ON e.id = o.emp_id;',
      '```',
      '',
      '## FULL OUTER JOIN — Keep All Rows from Both',
      '',
      'Returns all rows from both tables. Where there is no match, the non-matching side shows NULL.',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'FULL OUTER JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- Result includes all employees AND all orders,',
      '-- with NULLs where there is no match on either side.',
      '```',
      '',
      '**Note:** MySQL does not support FULL OUTER JOIN natively. Simulate it:',
      '',
      '```sql',
      '-- MySQL: FULL OUTER JOIN simulation',
      'SELECT e.name, o.amount FROM employees e LEFT JOIN orders o ON e.id = o.emp_id',
      'UNION',
      'SELECT e.name, o.amount FROM employees e RIGHT JOIN orders o ON e.id = o.emp_id;',
      '```',
      '',
      '## CROSS JOIN — Cartesian Product',
      '',
      'Returns every combination of rows from both tables. No ON condition.',
      '',
      '```sql',
      'SELECT e.name, p.product_name',
      'FROM employees e',
      'CROSS JOIN products p;',
      '-- If employees has 100 rows and products has 50 rows → 5,000 result rows!',
      '```',
      '',
      'Use cases: generating test data, building combination matrices.',
      '',
      '## Self JOIN — Joining a Table to Itself',
      '',
      'Use aliases to treat one table as two different tables. Common for hierarchical data (employees and their managers).',
      '',
      '```sql',
      '-- Find each employee and their manager\'s name',
      'SELECT e.name   AS employee,',
      '       m.name   AS manager',
      'FROM   employees e',
      'LEFT JOIN employees m ON e.manager_id = m.id;',
      '',
      '-- Result:',
      '-- employee | manager',
      '-- ---------+---------',
      '-- Alice    | Bob',
      '-- Bob      | NULL   ← Bob is the top manager',
      '-- Carol    | Alice',
      '```',
      '',
      '## Joining Three or More Tables',
      '',
      '```sql',
      '-- employees → departments → locations',
      'SELECT e.name,',
      '       d.dept_name,',
      '       l.city',
      'FROM   employees e',
      'JOIN   departments d ON e.dept_id = d.id',
      'JOIN   locations   l ON d.location_id = l.id',
      "WHERE  l.country = 'USA';",
      '```',
      '',
      '## JOIN Performance Tips',
      '',
      '- Always JOIN on **indexed columns** (primary keys, foreign keys). Missing index = full table scan.',
      '- Filter early with WHERE to reduce the number of rows before the join.',
      '- SELECT only the columns you need — avoid `SELECT *` across joins.',
      '- Use EXPLAIN / EXPLAIN PLAN to see how the database executes your query.',
      '',
      '## Exercise Set 2 — JOINs',
      '',
      '```sql',
      '-- Schema',
      'CREATE TABLE employees (emp_id INT, name VARCHAR(100), dept_id INT, salary DECIMAL(10,2), manager_id INT);',
      'CREATE TABLE departments (dept_id INT, dept_name VARCHAR(100), location VARCHAR(100));',
      'CREATE TABLE projects (proj_id INT, proj_name VARCHAR(100));',
      'CREATE TABLE assignments (emp_id INT, proj_id INT, hours INT);',
      '```',
      '',
      '**Exercise 1 (Easy):** List every employee\'s name and their department name.',
      '',
      '```sql',
      'SELECT e.name, d.dept_name',
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id;',
      '```',
      '',
      '**Exercise 2 (Easy):** Find employees who are NOT assigned to any project.',
      '',
      '```sql',
      'SELECT e.name',
      'FROM employees e',
      'LEFT JOIN assignments a ON e.emp_id = a.emp_id',
      'WHERE a.emp_id IS NULL;',
      '```',
      '',
      '**Exercise 3 (Medium):** For each project, show the project name and the total hours worked across all employees. Include projects with zero hours.',
      '',
      '```sql',
      'SELECT p.proj_name,',
      '       COALESCE(SUM(a.hours), 0) AS total_hours',
      'FROM projects p',
      'LEFT JOIN assignments a ON p.proj_id = a.proj_id',
      'GROUP BY p.proj_id, p.proj_name',
      'ORDER BY total_hours DESC;',
      '```',
      '',
      '**Exercise 4 (Medium):** Show each employee\'s name alongside their manager\'s name. Employees with no manager should still appear, with "No Manager" shown instead of NULL.',
      '',
      '```sql',
      'SELECT e.name                            AS employee,',
      "       COALESCE(m.name, 'No Manager')    AS manager",
      'FROM employees e',
      'LEFT JOIN employees m ON e.manager_id = m.emp_id;',
      '```',
      '',
      '**Exercise 5 (Hard — LeetCode 185 style):** List all employees whose salary is above the average salary in their own department.',
      '',
      '```sql',
      'SELECT e.name, e.salary, d.dept_name',
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id',
      'JOIN (',
      '  SELECT dept_id, AVG(salary) AS avg_salary',
      '  FROM employees',
      '  GROUP BY dept_id',
      ') dept_avg ON e.dept_id = dept_avg.dept_id',
      'WHERE e.salary > dept_avg.avg_salary',
      'ORDER BY d.dept_name, e.salary DESC;',
      '```',
    ].join('\n'),
    zh: [
      '## 为什么需要 JOIN',
      '',
      '关系型数据库将数据存储在不同的表中以避免重复。**employees** 表存储员工信息；**orders** 表存储订单。JOIN 根据相关列（通常是外键关系）将两个或多个表的行组合起来。',
      '',
      '```',
      'employees 表             orders 表',
      '┌────┬────────┐          ┌────┬────────┬──────────┐',
      '│ id │ name   │          │ id │ emp_id │ amount   │',
      '├────┼────────┤          ├────┼────────┼──────────┤',
      '│  1 │ Alice  │          │101 │   1    │  500.00  │',
      '│  2 │ Bob    │          │102 │   1    │  200.00  │',
      '│  3 │ Carol  │          │103 │   2    │  800.00  │',
      '│  4 │ Dave   │          └────┴────────┴──────────┘',
      '└────┴────────┘          （Dave 没有订单）',
      '```',
      '',
      '## INNER JOIN——只返回匹配行',
      '',
      '返回**两个**表中连接条件都匹配的行。不匹配的行被排除。',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'INNER JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- 结果：',
      '-- Alice  | 500.00',
      '-- Alice  | 200.00',
      '-- Bob    | 800.00',
      '-- （Carol 和 Dave 被排除——没有匹配订单）',
      '```',
      '',
      '## LEFT JOIN——保留左表所有行',
      '',
      '返回左表的**所有**行，加上右表的匹配行。没有匹配时，右侧列为 NULL。',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'LEFT JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- 结果：',
      '-- Alice  | 500.00',
      '-- Alice  | 200.00',
      '-- Bob    | 800.00',
      '-- Carol  | NULL    ← Carol 没有订单，但仍然出现',
      '-- Dave   | NULL    ← Dave 没有订单，但仍然出现',
      '```',
      '',
      '**经典使用场景：** 找出从未下过订单的员工。',
      '',
      '```sql',
      'SELECT e.name',
      'FROM employees e',
      'LEFT JOIN orders o ON e.id = o.emp_id',
      'WHERE o.emp_id IS NULL;   -- NULL 表示没有找到匹配',
      '',
      '-- 结果：Carol、Dave',
      '```',
      '',
      '## FULL OUTER JOIN——保留两边所有行',
      '',
      '返回两个表的所有行。没有匹配的一侧显示 NULL。',
      '',
      '```sql',
      'SELECT e.name, o.amount',
      'FROM employees e',
      'FULL OUTER JOIN orders o ON e.id = o.emp_id;',
      '',
      '-- 结果包含所有员工和所有订单，',
      '-- 任一侧没有匹配时显示 NULL。',
      '```',
      '',
      '## 自连接——表与自身连接',
      '',
      '用别名将一张表当作两张不同的表。常用于层次数据（员工和他们的经理）。',
      '',
      '```sql',
      '-- 查找每个员工及其经理姓名',
      'SELECT e.name   AS 员工,',
      '       m.name   AS 经理',
      'FROM   employees e',
      'LEFT JOIN employees m ON e.manager_id = m.id;',
      '',
      '-- 结果：',
      '-- Alice  | Bob',
      '-- Bob    | NULL   ← Bob 是最高级别管理者',
      '-- Carol  | Alice',
      '```',
      '',
      '## JOIN 性能技巧',
      '',
      '- 始终在**索引列**（主键、外键）上做 JOIN。缺少索引 = 全表扫描。',
      '- 用 WHERE 提前过滤，减少 JOIN 前的行数。',
      '- 只 SELECT 你需要的列——避免跨 JOIN 用 `SELECT *`。',
      '- 使用 EXPLAIN / EXPLAIN PLAN 查看数据库如何执行查询。',
      '',
      '## 练习题 2——JOIN',
      '',
      '```sql',
      'CREATE TABLE employees (emp_id INT, name VARCHAR(100), dept_id INT, salary DECIMAL(10,2), manager_id INT);',
      'CREATE TABLE departments (dept_id INT, dept_name VARCHAR(100), location VARCHAR(100));',
      'CREATE TABLE projects (proj_id INT, proj_name VARCHAR(100));',
      'CREATE TABLE assignments (emp_id INT, proj_id INT, hours INT);',
      '```',
      '',
      '**练习 1（简单）：** 列出每位员工的姓名及其部门名称。',
      '',
      '```sql',
      'SELECT e.name, d.dept_name',
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id;',
      '```',
      '',
      '**练习 2（简单）：** 找出没有分配任何项目的员工。',
      '',
      '```sql',
      'SELECT e.name',
      'FROM employees e',
      'LEFT JOIN assignments a ON e.emp_id = a.emp_id',
      'WHERE a.emp_id IS NULL;',
      '```',
      '',
      '**练习 3（中等）：** 对每个项目，显示项目名称和所有员工累计工作小时数。包含零小时的项目。',
      '',
      '```sql',
      'SELECT p.proj_name,',
      '       COALESCE(SUM(a.hours), 0) AS 总小时数',
      'FROM projects p',
      'LEFT JOIN assignments a ON p.proj_id = a.proj_id',
      'GROUP BY p.proj_id, p.proj_name',
      'ORDER BY 总小时数 DESC;',
      '```',
      '',
      '**练习 4（困难）：** 列出薪资高于本部门平均薪资的所有员工。',
      '',
      '```sql',
      'SELECT e.name, e.salary, d.dept_name',
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id',
      'JOIN (',
      '  SELECT dept_id, AVG(salary) AS avg_salary',
      '  FROM employees',
      '  GROUP BY dept_id',
      ') dept_avg ON e.dept_id = dept_avg.dept_id',
      'WHERE e.salary > dept_avg.avg_salary',
      'ORDER BY d.dept_name, e.salary DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 175, title: 'Combine Two Tables', titleZh: '组合两个表', difficulty: 'Easy' },
    { id: 181, title: 'Employees Earning More Than Their Managers', titleZh: '超过经理收入的员工', difficulty: 'Easy' },
    { id: 183, title: 'Customers Who Never Order', titleZh: '从不订购的客户', difficulty: 'Easy' },
    { id: 184, title: 'Department Highest Salary', titleZh: '部门工资最高的员工', difficulty: 'Medium' },
    { id: 197, title: 'Rising Temperature', titleZh: '上升的温度', difficulty: 'Easy' },
  ],
}
