import type { TopicContent } from '../../types'

export const mysqlContent: TopicContent = {
  id: 'sql-mysql',
  title: { en: 'MySQL Deep Dive', zh: 'MySQL 深度指南' },
  description: {
    en: 'Comprehensive MySQL guide — data types, string/date/JSON functions, window functions, transactions, and performance tuning',
    zh: '全面的 MySQL 指南——数据类型、字符串/日期/JSON 函数、窗口函数、事务和性能调优',
  },
  timeEstimate: '90 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '# MySQL — Complete Reference Guide',
      '',
      '## Why MySQL?',
      '',
      'MySQL is the world\'s most popular open-source relational database. It powers Facebook, Twitter, YouTube, WordPress, and countless e-commerce platforms. Knowing MySQL is essential for web development, data engineering, and backend systems.',
      '',
      '**Key strengths:**',
      '- Extremely fast for read-heavy workloads',
      '- Simple setup and administration',
      '- Massive ecosystem (AWS RDS, Google Cloud SQL, PlanetScale, Vitess)',
      '- InnoDB storage engine: ACID transactions, row-level locking, foreign keys',
      '- MySQL 8.0+: window functions, CTEs, JSON support, invisible indexes',
      '',
      '---',
      '',
      '## 1. Data Types',
      '',
      'Choosing the right data type saves space and speeds up queries.',
      '',
      '### Integer Types',
      '',
      '```sql',
      '-- TINYINT   1 byte  -128 to 127 (or 0–255 UNSIGNED)',
      '-- SMALLINT  2 bytes -32768 to 32767',
      '-- MEDIUMINT 3 bytes -8388608 to 8388607',
      '-- INT       4 bytes -2147483648 to 2147483647',
      '-- BIGINT    8 bytes very large numbers',
      '',
      'CREATE TABLE users (',
      '  id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,',
      '  age        TINYINT UNSIGNED,',
      '  score      SMALLINT,',
      '  view_count BIGINT DEFAULT 0',
      ');',
      '```',
      '',
      '> **AUTO_INCREMENT** — MySQL\'s built-in auto-incrementing primary key (equivalent to PostgreSQL\'s SERIAL/BIGSERIAL).',
      '',
      '### Decimal / Float Types',
      '',
      '```sql',
      '-- DECIMAL(p, s) — exact; use for money',
      '-- FLOAT         — 4 bytes approximate',
      '-- DOUBLE        — 8 bytes approximate',
      '',
      'CREATE TABLE products (',
      '  price    DECIMAL(10, 2),   -- up to 99,999,999.99',
      '  rating   FLOAT,',
      '  weight_g DOUBLE',
      ');',
      '```',
      '',
      '### String Types',
      '',
      '```sql',
      '-- CHAR(n)        — fixed-length, padded with spaces (fast for fixed codes)',
      '-- VARCHAR(n)     — variable-length, up to n characters',
      '-- TEXT           — up to 65 535 bytes',
      '-- MEDIUMTEXT     — up to 16 MB',
      '-- LONGTEXT       — up to 4 GB',
      '',
      'CREATE TABLE articles (',
      '  slug    VARCHAR(255) NOT NULL,',
      '  summary TEXT,',
      '  body    LONGTEXT',
      ');',
      '```',
      '',
      '### Date & Time Types',
      '',
      '```sql',
      '-- DATE          — YYYY-MM-DD',
      '-- TIME          — HH:MM:SS',
      '-- DATETIME      — YYYY-MM-DD HH:MM:SS (no timezone)',
      '-- TIMESTAMP     — same range but stored as UTC, auto-converts to session timezone',
      '-- YEAR          — YYYY',
      '',
      'CREATE TABLE events (',
      '  event_date DATE,',
      '  start_time TIME,',
      '  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,',
      '  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
      ');',
      '```',
      '',
      '> **TIMESTAMP vs DATETIME:** Use `TIMESTAMP` when you need UTC storage and automatic timezone conversion. Use `DATETIME` when you want to store the date/time exactly as entered.',
      '',
      '### Boolean & JSON',
      '',
      '```sql',
      '-- BOOLEAN / BOOL  — alias for TINYINT(1). 0 = false, 1 = true',
      '-- JSON            — validated JSON storage (MySQL 5.7+)',
      '',
      'CREATE TABLE settings (',
      '  is_active  BOOLEAN DEFAULT TRUE,',
      '  metadata   JSON',
      ');',
      '```',
      '',
      '---',
      '',
      '## 2. String Functions',
      '',
      'These are the most frequently used string functions in MySQL.',
      '',
      '### Length & Case',
      '',
      '```sql',
      'SELECT',
      '  LENGTH(\'Hello\'),          -- 5  (byte length)',
      '  CHAR_LENGTH(\'Hello\'),     -- 5  (character length, important for multi-byte)',
      '  UPPER(\'hello\'),           -- HELLO',
      '  LOWER(\'HELLO\'),           -- hello',
      '  LCASE(\'HELLO\');           -- hello  (alias for LOWER)',
      '```',
      '',
      '### Trimming & Padding',
      '',
      '```sql',
      'SELECT',
      '  TRIM(\'  hello  \'),         -- \'hello\'',
      '  LTRIM(\'  hello\'),          -- \'hello\'',
      '  RTRIM(\'hello  \'),          -- \'hello\'',
      '  LPAD(\'5\', 3, \'0\'),        -- \'005\'',
      '  RPAD(\'hi\', 5, \'.\');       -- \'hi...\'',
      '```',
      '',
      '### Substring & Search',
      '',
      '```sql',
      'SELECT',
      '  SUBSTRING(\'Hello World\', 7),        -- \'World\'',
      '  SUBSTRING(\'Hello World\', 7, 3),     -- \'Wor\'',
      '  SUBSTR(\'Hello World\', 1, 5),        -- \'Hello\'  (alias)',
      '  LEFT(\'Hello World\', 5),             -- \'Hello\'',
      '  RIGHT(\'Hello World\', 5),            -- \'World\'',
      '  MID(\'Hello World\', 7, 5),           -- \'World\'  (alias for SUBSTRING)',
      '  INSTR(\'Hello World\', \'World\'),      -- 7  (1-based position)',
      '  LOCATE(\'World\', \'Hello World\');     -- 7  (alias for INSTR)',
      '```',
      '',
      '### Concatenation',
      '',
      '```sql',
      '-- CONCAT: NULL-safe if any argument is NULL → returns NULL',
      'SELECT CONCAT(\'Hello\', \' \', \'World\');  -- \'Hello World\'',
      '',
      '-- CONCAT_WS: with separator — skips NULL values',
      'SELECT CONCAT_WS(\', \', \'Alice\', NULL, \'Bob\');  -- \'Alice, Bob\'',
      '',
      '-- GROUP_CONCAT: aggregate multiple rows into one string (MySQL-specific)',
      'SELECT',
      '  department,',
      '  GROUP_CONCAT(name ORDER BY name SEPARATOR \', \') AS employees',
      'FROM employees',
      'GROUP BY department;',
      '',
      '-- Limit GROUP_CONCAT length:',
      'SET group_concat_max_len = 10000;',
      '```',
      '',
      '> **GROUP_CONCAT** is MySQL\'s version of PostgreSQL\'s `STRING_AGG`. It\'s extremely useful for producing comma-separated lists from rows.',
      '',
      '### Replace & Reverse',
      '',
      '```sql',
      'SELECT',
      '  REPLACE(\'Hello World\', \'World\', \'MySQL\'),  -- \'Hello MySQL\'',
      '  REVERSE(\'Hello\'),                           -- \'olleH\'',
      '  REPEAT(\'ab\', 3),                            -- \'ababab\'',
      '  SPACE(3),                                   -- \'   \'',
      '  INSERT(\'Hello World\', 7, 5, \'MySQL\');       -- \'Hello MySQL\'',
      '```',
      '',
      '### Pattern Matching',
      '',
      '```sql',
      '-- LIKE: wildcards % (any chars) and _ (single char)',
      'SELECT * FROM employees WHERE name LIKE \'A%\';',
      'SELECT * FROM employees WHERE email LIKE \'%@gmail.com\';',
      '',
      '-- REGEXP / RLIKE: regular expression matching',
      'SELECT * FROM employees WHERE name REGEXP \'^[A-Z][a-z]+$\';',
      'SELECT * FROM employees WHERE phone RLIKE \'^[0-9]{10}$\';',
      '',
      '-- REGEXP_REPLACE (MySQL 8.0+)',
      'SELECT REGEXP_REPLACE(\'Hello   World\', \' +\', \' \');  -- \'Hello World\'',
      '',
      '-- REGEXP_SUBSTR (MySQL 8.0+)',
      'SELECT REGEXP_SUBSTR(\'order-12345-done\', \'[0-9]+\');  -- \'12345\'',
      '```',
      '',
      '### Format & Other',
      '',
      '```sql',
      'SELECT',
      '  FORMAT(1234567.891, 2),   -- \'1,234,567.89\' (locale-formatted)',
      '  SOUNDEX(\'Robert\'),        -- \'R163\' (phonetic matching)',
      '  MD5(\'password\'),          -- 32-char hex hash',
      '  SHA2(\'password\', 256);    -- 64-char SHA-256 hash',
      '```',
      '',
      '---',
      '',
      '## 3. Date & Time Functions',
      '',
      '### Getting Current Date/Time',
      '',
      '```sql',
      'SELECT',
      '  NOW(),              -- 2024-03-15 14:30:00  (datetime, session timezone)',
      '  CURDATE(),          -- 2024-03-15',
      '  CURRENT_DATE(),     -- 2024-03-15  (alias)',
      '  CURTIME(),          -- 14:30:00',
      '  CURRENT_TIME(),     -- 14:30:00  (alias)',
      '  SYSDATE(),          -- like NOW() but evaluated each call',
      '  UTC_TIMESTAMP();    -- current UTC datetime',
      '```',
      '',
      '### Extracting Parts',
      '',
      '```sql',
      'SELECT',
      '  YEAR(\'2024-03-15\'),          -- 2024',
      '  MONTH(\'2024-03-15\'),         -- 3',
      '  DAY(\'2024-03-15\'),           -- 15',
      '  DAYOFWEEK(\'2024-03-15\'),     -- 6 (1=Sunday)',
      '  DAYOFYEAR(\'2024-03-15\'),     -- 75',
      '  WEEK(\'2024-03-15\'),          -- 11',
      '  QUARTER(\'2024-03-15\'),       -- 1',
      '  HOUR(\'14:30:45\'),            -- 14',
      '  MINUTE(\'14:30:45\'),          -- 30',
      '  SECOND(\'14:30:45\');          -- 45',
      '',
      '-- EXTRACT: standard SQL equivalent',
      'SELECT EXTRACT(YEAR FROM \'2024-03-15\');   -- 2024',
      'SELECT EXTRACT(MONTH FROM NOW());',
      '```',
      '',
      '### Date Arithmetic',
      '',
      '```sql',
      '-- DATE_ADD / DATE_SUB',
      'SELECT DATE_ADD(\'2024-01-01\', INTERVAL 30 DAY);    -- 2024-01-31',
      'SELECT DATE_ADD(\'2024-01-01\', INTERVAL 3 MONTH);   -- 2024-04-01',
      'SELECT DATE_SUB(\'2024-03-15\', INTERVAL 1 YEAR);    -- 2023-03-15',
      '',
      '-- Shorthand with + / - operators',
      'SELECT \'2024-01-01\' + INTERVAL 30 DAY;             -- 2024-01-31',
      '',
      '-- DATEDIFF: difference in days (date1 - date2)',
      'SELECT DATEDIFF(\'2024-12-31\', \'2024-01-01\');      -- 365',
      '',
      '-- TIMESTAMPDIFF: difference in any unit',
      'SELECT TIMESTAMPDIFF(YEAR,  \'1990-05-20\', NOW());  -- age in years',
      'SELECT TIMESTAMPDIFF(MONTH, \'2024-01-01\', \'2024-03-15\');  -- 2',
      'SELECT TIMESTAMPDIFF(HOUR,  \'2024-03-15 08:00\', \'2024-03-15 14:30\');  -- 6',
      '```',
      '',
      '### Formatting Dates',
      '',
      '```sql',
      '-- DATE_FORMAT: format a date using format specifiers',
      'SELECT DATE_FORMAT(NOW(), \'%Y-%m-%d\');             -- 2024-03-15',
      'SELECT DATE_FORMAT(NOW(), \'%d/%m/%Y %H:%i\');       -- 15/03/2024 14:30',
      'SELECT DATE_FORMAT(NOW(), \'%W, %M %d %Y\');         -- Friday, March 15 2024',
      '',
      '-- Common format specifiers:',
      '-- %Y  4-digit year    %y  2-digit year',
      '-- %m  2-digit month   %M  Month name',
      '-- %d  2-digit day     %D  Day with suffix (1st, 2nd)',
      '-- %H  Hour 24h        %h  Hour 12h',
      '-- %i  Minutes         %s  Seconds',
      '-- %p  AM/PM           %W  Weekday name',
      '',
      '-- STR_TO_DATE: parse a string into a date',
      'SELECT STR_TO_DATE(\'15/03/2024\', \'%d/%m/%Y\');     -- 2024-03-15',
      'SELECT STR_TO_DATE(\'March 15 2024\', \'%M %d %Y\');  -- 2024-03-15',
      '```',
      '',
      '### Rounding / Truncating Dates',
      '',
      '```sql',
      '-- LAST_DAY: last day of the month',
      'SELECT LAST_DAY(\'2024-02-01\');   -- 2024-02-29 (2024 is a leap year)',
      '',
      '-- MAKEDATE / MAKETIME',
      'SELECT MAKEDATE(2024, 100);      -- 2024-04-09  (100th day of 2024)',
      'SELECT MAKETIME(14, 30, 0);      -- 14:30:00',
      '',
      '-- Date truncation equivalent (no DATE_TRUNC in MySQL)',
      'SELECT DATE_FORMAT(NOW(), \'%Y-%m-01\');   -- first day of current month',
      'SELECT DATE_FORMAT(NOW(), \'%Y-01-01\');   -- first day of current year',
      '```',
      '',
      '---',
      '',
      '## 4. Control Flow Functions',
      '',
      '### IF / IIF',
      '',
      '```sql',
      '-- IF(condition, true_value, false_value)',
      'SELECT name, IF(salary > 80000, \'Senior\', \'Junior\') AS level',
      'FROM employees;',
      '',
      '-- Nested IF',
      'SELECT',
      '  name,',
      '  IF(salary > 100000, \'Executive\',',
      '    IF(salary > 70000, \'Senior\', \'Junior\')',
      '  ) AS level',
      'FROM employees;',
      '```',
      '',
      '### IFNULL / NULLIF / COALESCE',
      '',
      '```sql',
      '-- IFNULL(expr, fallback): return fallback if expr is NULL',
      'SELECT IFNULL(NULL, \'default\');       -- \'default\'',
      'SELECT IFNULL(salary, 0) FROM employees;',
      '',
      '-- NULLIF(a, b): return NULL if a = b, else return a',
      'SELECT NULLIF(10, 10);    -- NULL',
      'SELECT NULLIF(10, 5);     -- 10',
      '-- Use case: avoid division by zero',
      'SELECT total / NULLIF(quantity, 0) FROM orders;',
      '',
      '-- COALESCE: return first non-NULL value (standard SQL)',
      'SELECT COALESCE(NULL, NULL, \'found\', \'ignored\');  -- \'found\'',
      'SELECT COALESCE(preferred_name, first_name, \'Unknown\') AS display_name',
      'FROM users;',
      '```',
      '',
      '### CASE Expression',
      '',
      '```sql',
      '-- Simple CASE',
      'SELECT',
      '  name,',
      '  CASE department_id',
      '    WHEN 1 THEN \'Engineering\'',
      '    WHEN 2 THEN \'Sales\'',
      '    WHEN 3 THEN \'Marketing\'',
      '    ELSE \'Other\'',
      '  END AS dept_name',
      'FROM employees;',
      '',
      '-- Searched CASE',
      'SELECT',
      '  name,',
      '  CASE',
      '    WHEN salary >= 100000 THEN \'High\'',
      '    WHEN salary >= 70000  THEN \'Mid\'',
      '    ELSE \'Low\'',
      '  END AS salary_band',
      'FROM employees;',
      '',
      '-- CASE in aggregation (conditional count)',
      'SELECT',
      '  department,',
      '  COUNT(*) AS total,',
      '  SUM(CASE WHEN salary > 80000 THEN 1 ELSE 0 END) AS senior_count',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '---',
      '',
      '## 5. Upsert Patterns',
      '',
      'MySQL has three ways to handle insert conflicts — a key difference from PostgreSQL.',
      '',
      '### INSERT ... ON DUPLICATE KEY UPDATE',
      '',
      '```sql',
      '-- Most flexible: insert if not exists, update if key conflict',
      'INSERT INTO page_views (page_id, view_date, count)',
      'VALUES (101, CURDATE(), 1)',
      'ON DUPLICATE KEY UPDATE count = count + 1;',
      '',
      '-- With VALUES() reference to the inserted row\'s columns',
      'INSERT INTO products (sku, name, price)',
      'VALUES (\'ABC123\', \'Widget\', 9.99)',
      'ON DUPLICATE KEY UPDATE',
      '  name  = VALUES(name),',
      '  price = VALUES(price);',
      '',
      '-- MySQL 8.0.20+ alias syntax (VALUES() is deprecated)',
      'INSERT INTO products (sku, name, price)',
      'VALUES (\'ABC123\', \'Widget\', 9.99) AS new',
      'ON DUPLICATE KEY UPDATE',
      '  name  = new.name,',
      '  price = new.price;',
      '```',
      '',
      '### INSERT IGNORE',
      '',
      '```sql',
      '-- Silently ignores duplicate key errors (skips the row)',
      'INSERT IGNORE INTO users (email, name)',
      'VALUES (\'alice@example.com\', \'Alice\');',
      '',
      '-- Also ignores other non-fatal errors (data truncation, etc.)',
      '```',
      '',
      '### REPLACE INTO',
      '',
      '```sql',
      '-- DELETE the conflicting row, then INSERT a fresh row',
      '-- WARNING: resets AUTO_INCREMENT, breaks foreign keys, loses old column values',
      'REPLACE INTO users (id, email, name)',
      'VALUES (1, \'alice@example.com\', \'Alice Updated\');',
      '',
      '-- Generally prefer ON DUPLICATE KEY UPDATE over REPLACE INTO',
      '```',
      '',
      '---',
      '',
      '## 6. Window Functions (MySQL 8.0+)',
      '',
      'Window functions perform calculations across a set of table rows without collapsing them.',
      '',
      '### Ranking Functions',
      '',
      '```sql',
      '-- ROW_NUMBER: unique sequential number',
      '-- RANK: same rank for ties, gaps after ties',
      '-- DENSE_RANK: same rank for ties, no gaps',
      'SELECT',
      '  name,',
      '  salary,',
      '  department,',
      '  ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS row_num,',
      '  RANK()       OVER (PARTITION BY department ORDER BY salary DESC) AS rnk,',
      '  DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dense_rnk',
      'FROM employees;',
      '',
      '-- Get top earner per department:',
      'SELECT * FROM (',
      '  SELECT',
      '    *,',
      '    RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS rnk',
      '  FROM employees',
      ') ranked',
      'WHERE rnk = 1;',
      '```',
      '',
      '### Offset Functions',
      '',
      '```sql',
      '-- LAG: access a previous row value',
      '-- LEAD: access a next row value',
      'SELECT',
      '  order_date,',
      '  revenue,',
      '  LAG(revenue, 1, 0)  OVER (ORDER BY order_date) AS prev_revenue,',
      '  LEAD(revenue, 1, 0) OVER (ORDER BY order_date) AS next_revenue,',
      '  revenue - LAG(revenue) OVER (ORDER BY order_date) AS daily_change',
      'FROM daily_sales;',
      '',
      '-- FIRST_VALUE / LAST_VALUE',
      'SELECT',
      '  name,',
      '  salary,',
      '  FIRST_VALUE(salary) OVER (PARTITION BY department ORDER BY hire_date) AS first_hire_salary,',
      '  LAST_VALUE(salary)  OVER (',
      '    PARTITION BY department',
      '    ORDER BY hire_date',
      '    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING',
      '  ) AS last_hire_salary',
      'FROM employees;',
      '```',
      '',
      '### Running Totals & Moving Averages',
      '',
      '```sql',
      'SELECT',
      '  order_date,',
      '  revenue,',
      '  SUM(revenue)  OVER (ORDER BY order_date ROWS UNBOUNDED PRECEDING) AS running_total,',
      '  AVG(revenue)  OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS moving_avg_7d',
      'FROM daily_sales;',
      '```',
      '',
      '### NTILE & Percentile',
      '',
      '```sql',
      '-- NTILE: divide into N buckets',
      'SELECT name, salary,',
      '  NTILE(4) OVER (ORDER BY salary) AS quartile',
      'FROM employees;',
      '',
      '-- PERCENT_RANK: relative rank 0.0 to 1.0',
      'SELECT name, salary,',
      '  ROUND(PERCENT_RANK() OVER (ORDER BY salary) * 100, 1) AS percentile',
      'FROM employees;',
      '```',
      '',
      '---',
      '',
      '## 7. JSON Functions (MySQL 8.0+)',
      '',
      '### Inserting & Reading JSON',
      '',
      '```sql',
      'CREATE TABLE products (',
      '  id         INT AUTO_INCREMENT PRIMARY KEY,',
      '  name       VARCHAR(255),',
      '  attributes JSON',
      ');',
      '',
      'INSERT INTO products (name, attributes) VALUES',
      '  (\'Laptop\', \'{"cpu": "Intel i7", "ram": 16, "tags": ["tech", "portable"]}\'),',
      '  (\'Phone\',  \'{"cpu": "Snapdragon 8", "ram": 12, "tags": ["mobile"]}\');',
      '',
      '-- JSON_EXTRACT: extract a value',
      'SELECT JSON_EXTRACT(attributes, \'$.cpu\') FROM products;',
      '',
      '-- -> operator: shorthand for JSON_EXTRACT (returns JSON)',
      'SELECT attributes->\'$.cpu\' FROM products;',
      '',
      '-- ->> operator: unquote result (returns plain string/number)',
      'SELECT attributes->>\'$.cpu\' AS cpu FROM products;',
      '-- Result: Intel i7  (no surrounding quotes)',
      '```',
      '',
      '### Modifying JSON',
      '',
      '```sql',
      '-- JSON_SET: insert or update keys',
      'UPDATE products',
      'SET attributes = JSON_SET(attributes, \'$.storage\', \'512GB\', \'$.ram\', 32)',
      'WHERE id = 1;',
      '',
      '-- JSON_INSERT: insert only (won\'t overwrite existing keys)',
      'UPDATE products',
      'SET attributes = JSON_INSERT(attributes, \'$.warranty\', \'2 years\')',
      'WHERE id = 1;',
      '',
      '-- JSON_REMOVE: delete a key',
      'UPDATE products',
      'SET attributes = JSON_REMOVE(attributes, \'$.warranty\')',
      'WHERE id = 1;',
      '',
      '-- JSON_REPLACE: update only (won\'t create new keys)',
      'UPDATE products',
      'SET attributes = JSON_REPLACE(attributes, \'$.ram\', 64)',
      'WHERE id = 1;',
      '```',
      '',
      '### Querying JSON',
      '',
      '```sql',
      '-- Filter by JSON value',
      'SELECT name FROM products',
      'WHERE attributes->>\'$.ram\' > 8;',
      '',
      '-- JSON_CONTAINS: check if JSON contains a value',
      'SELECT name FROM products',
      'WHERE JSON_CONTAINS(attributes->>\'$.tags\', \'["tech"]\');',
      '',
      '-- JSON_ARRAY_LENGTH',
      'SELECT name, JSON_LENGTH(attributes->\'$.tags\') AS tag_count',
      'FROM products;',
      '',
      '-- JSON_KEYS: get object keys',
      'SELECT JSON_KEYS(attributes) FROM products WHERE id = 1;',
      '-- Result: ["cpu", "ram", "tags", "storage"]',
      '',
      '-- JSON_ARRAYAGG / JSON_OBJECTAGG (MySQL 8.0+)',
      'SELECT',
      '  department,',
      '  JSON_ARRAYAGG(name) AS employee_names',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '---',
      '',
      '## 8. Full-Text Search',
      '',
      '```sql',
      '-- Create FULLTEXT index',
      'CREATE TABLE articles (',
      '  id    INT AUTO_INCREMENT PRIMARY KEY,',
      '  title VARCHAR(255),',
      '  body  TEXT,',
      '  FULLTEXT idx_fts (title, body)',
      ');',
      '',
      '-- MATCH ... AGAINST: natural language mode (default)',
      'SELECT title, MATCH(title, body) AGAINST (\'mysql tutorial\') AS score',
      'FROM articles',
      'WHERE MATCH(title, body) AGAINST (\'mysql tutorial\')',
      'ORDER BY score DESC;',
      '',
      '-- Boolean mode: + required, - excluded, * wildcard',
      'SELECT title FROM articles',
      'WHERE MATCH(title, body) AGAINST (\'+mysql +tutorial -beginner\' IN BOOLEAN MODE);',
      '',
      '-- Query expansion: broadens search with related terms',
      'SELECT title FROM articles',
      'WHERE MATCH(title, body) AGAINST (\'mysql\' WITH QUERY EXPANSION);',
      '```',
      '',
      '---',
      '',
      '## 9. Transactions',
      '',
      '```sql',
      '-- MySQL InnoDB supports full ACID transactions',
      '',
      'START TRANSACTION;',
      '',
      'UPDATE accounts SET balance = balance - 500 WHERE id = 1;',
      'UPDATE accounts SET balance = balance + 500 WHERE id = 2;',
      '',
      '-- If something goes wrong:',
      'ROLLBACK;',
      '',
      '-- If everything is fine:',
      'COMMIT;',
      '',
      '-- Savepoints',
      'START TRANSACTION;',
      '  INSERT INTO orders (customer_id, total) VALUES (101, 199.99);',
      '  SAVEPOINT after_order;',
      '',
      '  INSERT INTO order_items (order_id, product_id) VALUES (LAST_INSERT_ID(), 5);',
      '',
      '  -- Rollback only to savepoint (order preserved, items rolled back)',
      '  ROLLBACK TO SAVEPOINT after_order;',
      '',
      'COMMIT;',
      '',
      '-- Isolation levels',
      'SET TRANSACTION ISOLATION LEVEL READ COMMITTED;',
      '-- Options: READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ (default), SERIALIZABLE',
      '```',
      '',
      '---',
      '',
      '## 10. Performance Tuning',
      '',
      '### EXPLAIN',
      '',
      '```sql',
      '-- Analyze query execution plan',
      'EXPLAIN SELECT * FROM employees WHERE department = \'Engineering\';',
      '',
      '-- EXPLAIN output columns:',
      '-- type:         ALL (full scan), index, range, ref, eq_ref, const (best to worst)',
      '-- possible_keys: indexes that could be used',
      '-- key:          index actually used',
      '-- rows:         estimated rows to examine',
      '-- Extra:        Using where, Using index, Using filesort, Using temporary',
      '',
      '-- EXPLAIN FORMAT=JSON — detailed JSON output',
      'EXPLAIN FORMAT=JSON SELECT e.name, d.name',
      'FROM employees e',
      'JOIN departments d ON e.department_id = d.id',
      'WHERE e.salary > 80000;',
      '',
      '-- EXPLAIN ANALYZE (MySQL 8.0.18+) — actually runs the query',
      'EXPLAIN ANALYZE SELECT * FROM orders WHERE customer_id = 101;',
      '```',
      '',
      '### Indexes',
      '',
      '```sql',
      '-- Create a regular index',
      'CREATE INDEX idx_emp_dept ON employees (department);',
      '',
      '-- Composite index: column order matters',
      '-- Best for queries that filter on (department, salary) in that order',
      'CREATE INDEX idx_dept_salary ON employees (department, salary);',
      '',
      '-- Unique index',
      'CREATE UNIQUE INDEX idx_email ON users (email);',
      '',
      '-- Prefix index (for long VARCHAR/TEXT columns)',
      'CREATE INDEX idx_title_prefix ON articles (title(50));',
      '',
      '-- Covering index: includes all columns needed by the query',
      'CREATE INDEX idx_covering ON employees (department, salary, name);',
      '',
      '-- Invisible index (MySQL 8.0): disable without dropping',
      'ALTER TABLE employees ALTER INDEX idx_emp_dept INVISIBLE;',
      'ALTER TABLE employees ALTER INDEX idx_emp_dept VISIBLE;',
      '',
      '-- View indexes on a table',
      'SHOW INDEX FROM employees;',
      '```',
      '',
      '### Index Best Practices',
      '',
      '```sql',
      '-- LEFT() function prevents index use:',
      'SELECT * FROM users WHERE LEFT(email, 5) = \'alice\';  -- NO index',
      'SELECT * FROM users WHERE email LIKE \'alice%\';         -- YES index',
      '',
      '-- Functions on indexed columns kill index usage:',
      'SELECT * FROM orders WHERE YEAR(created_at) = 2024;        -- NO',
      'SELECT * FROM orders WHERE created_at >= \'2024-01-01\'',
      '                       AND created_at  < \'2025-01-01\';    -- YES',
      '',
      '-- OR can prevent index use on different columns:',
      'SELECT * FROM users WHERE first_name = \'Alice\' OR last_name = \'Smith\';',
      '-- Better with UNION:',
      'SELECT * FROM users WHERE first_name = \'Alice\'',
      'UNION',
      'SELECT * FROM users WHERE last_name = \'Smith\';',
      '```',
      '',
      '---',
      '',
      '## 11. CTEs and Recursive Queries (MySQL 8.0+)',
      '',
      '```sql',
      '-- Regular CTE',
      'WITH high_earners AS (',
      '  SELECT * FROM employees WHERE salary > 90000',
      ')',
      'SELECT department, COUNT(*) FROM high_earners GROUP BY department;',
      '',
      '-- Multiple CTEs',
      'WITH',
      '  dept_avg AS (',
      '    SELECT department, AVG(salary) AS avg_sal FROM employees GROUP BY department',
      '  ),',
      '  overall_avg AS (',
      '    SELECT AVG(salary) AS grand_avg FROM employees',
      '  )',
      'SELECT d.department, d.avg_sal, o.grand_avg,',
      '       d.avg_sal - o.grand_avg AS diff',
      'FROM dept_avg d, overall_avg o;',
      '',
      '-- Recursive CTE: org chart traversal',
      'WITH RECURSIVE org_tree AS (',
      '  -- Base case: CEO (no manager)',
      '  SELECT id, name, manager_id, 0 AS depth',
      '  FROM employees',
      '  WHERE manager_id IS NULL',
      '',
      '  UNION ALL',
      '',
      '  -- Recursive step: find direct reports',
      '  SELECT e.id, e.name, e.manager_id, ot.depth + 1',
      '  FROM employees e',
      '  JOIN org_tree ot ON e.manager_id = ot.id',
      ')',
      'SELECT REPEAT(\'  \', depth) || name AS hierarchy',
      'FROM org_tree',
      'ORDER BY depth, name;',
      '```',
      '',
      '---',
      '',
      '## 12. Stored Procedures & User-Defined Functions',
      '',
      '```sql',
      '-- Stored Procedure: reusable SQL code block',
      'DELIMITER //  -- Change delimiter to allow ; inside procedure',
      '',
      'CREATE PROCEDURE get_employees_by_dept(IN dept_name VARCHAR(100))',
      'BEGIN',
      '  SELECT id, name, salary',
      '  FROM employees',
      '  WHERE department = dept_name',
      '  ORDER BY salary DESC;',
      'END//  ',
      '',
      'DELIMITER ;',
      '',
      '-- Call the procedure',
      'CALL get_employees_by_dept(\'Engineering\');',
      '',
      '-- Procedure with OUT parameter',
      'DELIMITER //',
      'CREATE PROCEDURE get_dept_avg(IN dept VARCHAR(100), OUT avg_salary DECIMAL(10,2))',
      'BEGIN',
      '  SELECT AVG(salary) INTO avg_salary',
      '  FROM employees',
      '  WHERE department = dept;',
      'END//  ',
      'DELIMITER ;',
      '',
      'CALL get_dept_avg(\'Engineering\', @avg);',
      'SELECT @avg;',
      '',
      '-- User-Defined Function',
      'DELIMITER //',
      'CREATE FUNCTION years_of_service(hire_date DATE)',
      'RETURNS INT DETERMINISTIC',
      'BEGIN',
      '  RETURN TIMESTAMPDIFF(YEAR, hire_date, CURDATE());',
      'END//  ',
      'DELIMITER ;',
      '',
      'SELECT name, years_of_service(hire_date) AS years FROM employees;',
      '```',
      '',
      '---',
      '',
      '## 13. Storage Engines',
      '',
      '| Engine | ACID | Full-Text | Transactions | Best For |',
      '|--------|------|-----------|--------------|----------|',
      '| InnoDB | Yes | Yes (5.6+)| Yes | Default — general purpose |',
      '| MyISAM | No  | Yes       | No  | Legacy, read-heavy |',
      '| MEMORY | No  | No        | No  | Temporary tables, caching |',
      '| CSV    | No  | No        | No  | CSV file import/export |',
      '',
      '```sql',
      '-- Specify engine on table creation',
      'CREATE TABLE sessions (',
      '  id   VARCHAR(64) PRIMARY KEY,',
      '  data TEXT',
      ') ENGINE=MEMORY;',
      '',
      '-- Check engine',
      'SELECT table_name, engine FROM information_schema.tables',
      'WHERE table_schema = DATABASE();',
      '```',
      '',
      '---',
      '',
      '## 14. MySQL vs PostgreSQL Cheat Sheet',
      '',
      '| Feature | MySQL | PostgreSQL |',
      '|---------|-------|------------|',
      '| Auto increment | `AUTO_INCREMENT` | `SERIAL` / `GENERATED ALWAYS AS IDENTITY` |',
      '| String concat | `CONCAT(a, b)` | `a || b` |',
      '| Current datetime | `NOW()` | `NOW()` / `CURRENT_TIMESTAMP` |',
      '| Substring | `SUBSTRING(s, pos, len)` | `SUBSTRING(s FROM pos FOR len)` |',
      '| Regex replace | `REGEXP_REPLACE(s, p, r)` | `REGEXP_REPLACE(s, p, r)` |',
      '| Insert or update | `ON DUPLICATE KEY UPDATE` | `ON CONFLICT DO UPDATE` |',
      '| Aggregate to string | `GROUP_CONCAT(...)` | `STRING_AGG(expr, sep)` |',
      '| Date format | `DATE_FORMAT(d, fmt)` | `TO_CHAR(d, fmt)` |',
      '| JSON extract | `col->>"$.key"` | `col->>"key"` |',
      '| Case sensitivity | String comparisons case-insensitive by default | Case-sensitive by default |',
      '| Boolean | `TINYINT(1)` | `BOOLEAN` (native type) |',
      '| Schemas | Schemas = Databases | Multiple schemas per database |',
      '',
      '---',
      '',
      '## Practice Exercises',
      '',
      '### Exercise 1: String Manipulation',
      '```sql',
      '-- Given a users table with columns: id, first_name, last_name, email',
      '-- 1. Return full name as "Last, First" format',
      '-- 2. Mask email: show only first 3 chars + "***" + domain',
      '-- 3. Find users whose email domain is gmail.com',
      '',
      '-- Solution:',
      'SELECT',
      '  CONCAT(last_name, \', \', first_name) AS full_name,',
      '  CONCAT(LEFT(email, 3), \'***\', SUBSTRING_INDEX(email, \'@\', -1)) AS masked_email',
      'FROM users',
      'WHERE SUBSTRING_INDEX(email, \'@\', -1) = \'gmail.com\';',
      '```',
      '',
      '### Exercise 2: Date Calculations',
      '```sql',
      '-- Find employees hired more than 5 years ago',
      '-- Show their name, hire_date, and years of service',
      '',
      'SELECT',
      '  name,',
      '  hire_date,',
      '  TIMESTAMPDIFF(YEAR, hire_date, CURDATE()) AS years_of_service',
      'FROM employees',
      'WHERE TIMESTAMPDIFF(YEAR, hire_date, CURDATE()) > 5',
      'ORDER BY hire_date;',
      '```',
      '',
      '### Exercise 3: Upsert',
      '```sql',
      '-- Track daily page views. On conflict (page_id + view_date),',
      '-- increment the count rather than failing',
      '',
      'INSERT INTO page_views (page_id, view_date, count)',
      'VALUES (42, CURDATE(), 1)',
      'ON DUPLICATE KEY UPDATE count = count + 1;',
      '```',
      '',
      '### Exercise 4: Window Function Ranking',
      '```sql',
      '-- For each department, rank employees by salary (highest first)',
      '-- Show name, department, salary, and rank',
      '',
      'SELECT',
      '  name,',
      '  department,',
      '  salary,',
      '  DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS salary_rank',
      'FROM employees',
      'ORDER BY department, salary_rank;',
      '```',
      '',
      '### Exercise 5: Running Total with Date Filter',
      '```sql',
      '-- Show monthly revenue for 2024 with a running YTD total',
      '',
      'SELECT',
      '  DATE_FORMAT(order_date, \'%Y-%m\') AS month,',
      '  SUM(total)                         AS monthly_revenue,',
      '  SUM(SUM(total)) OVER (',
      '    ORDER BY DATE_FORMAT(order_date, \'%Y-%m\')',
      '  ) AS ytd_total',
      'FROM orders',
      'WHERE YEAR(order_date) = 2024',
      'GROUP BY DATE_FORMAT(order_date, \'%Y-%m\')',
      'ORDER BY month;',
      '```',
    ].join('\n'),
    zh: [
      '# MySQL — 完整参考指南',
      '',
      '## 为什么选择 MySQL？',
      '',
      'MySQL 是全球最流行的开源关系型数据库，驱动着 Facebook、Twitter、YouTube、WordPress 以及无数电商平台。掌握 MySQL 对 Web 开发、数据工程和后端系统至关重要。',
      '',
      '**核心优势：**',
      '- 读密集型工作负载速度极快',
      '- 简单的安装和管理',
      '- 庞大的生态系统（AWS RDS、Google Cloud SQL、PlanetScale、Vitess）',
      '- InnoDB 引擎：ACID 事务、行级锁、外键',
      '- MySQL 8.0+：窗口函数、CTE、JSON 支持、不可见索引',
      '',
      '---',
      '',
      '## 1. 数据类型',
      '',
      '选择合适的数据类型可节省存储空间并加快查询速度。',
      '',
      '### 整数类型',
      '',
      '```sql',
      '-- TINYINT   1 字节  -128 到 127（或 UNSIGNED 的 0–255）',
      '-- SMALLINT  2 字节  -32768 到 32767',
      '-- MEDIUMINT 3 字节  -8388608 到 8388607',
      '-- INT       4 字节  -2147483648 到 2147483647',
      '-- BIGINT    8 字节  非常大的数',
      '',
      'CREATE TABLE users (',
      '  id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,',
      '  age        TINYINT UNSIGNED,',
      '  score      SMALLINT,',
      '  view_count BIGINT DEFAULT 0',
      ');',
      '```',
      '',
      '> **AUTO_INCREMENT** — MySQL 内置的自增主键（等价于 PostgreSQL 的 SERIAL/BIGSERIAL）',
      '',
      '### 字符串类型',
      '',
      '```sql',
      '-- CHAR(n)    固定长度，用空格填充（适合固定格式代码）',
      '-- VARCHAR(n) 可变长度，最多 n 个字符',
      '-- TEXT       最多 65535 字节',
      '-- MEDIUMTEXT 最多 16 MB',
      '-- LONGTEXT   最多 4 GB',
      '',
      'CREATE TABLE articles (',
      '  slug    VARCHAR(255) NOT NULL,',
      '  summary TEXT,',
      '  body    LONGTEXT',
      ');',
      '```',
      '',
      '### 日期和时间类型',
      '',
      '```sql',
      '-- DATE       YYYY-MM-DD',
      '-- TIME       HH:MM:SS',
      '-- DATETIME   不含时区',
      '-- TIMESTAMP  存储为 UTC，自动转换为会话时区',
      '',
      'CREATE TABLE events (',
      '  event_date DATE,',
      '  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,',
      '  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
      ');',
      '```',
      '',
      '---',
      '',
      '## 2. 字符串函数',
      '',
      '### 长度与大小写',
      '',
      '```sql',
      'SELECT',
      '  LENGTH(\'Hello\'),       -- 5（字节长度）',
      '  CHAR_LENGTH(\'Hello\'),  -- 5（字符长度，多字节字符集更准确）',
      '  UPPER(\'hello\'),        -- HELLO',
      '  LOWER(\'HELLO\');        -- hello',
      '```',
      '',
      '### 截取与搜索',
      '',
      '```sql',
      'SELECT',
      '  SUBSTRING(\'Hello World\', 7),       -- \'World\'',
      '  LEFT(\'Hello World\', 5),            -- \'Hello\'',
      '  RIGHT(\'Hello World\', 5),           -- \'World\'',
      '  INSTR(\'Hello World\', \'World\'),     -- 7（1-based 位置）',
      '  LOCATE(\'World\', \'Hello World\');    -- 7',
      '```',
      '',
      '### 拼接函数',
      '',
      '```sql',
      '-- CONCAT：任意参数为 NULL 则结果为 NULL',
      'SELECT CONCAT(\'Hello\', \' \', \'World\');  -- \'Hello World\'',
      '',
      '-- CONCAT_WS：带分隔符，跳过 NULL 值',
      'SELECT CONCAT_WS(\', \', \'Alice\', NULL, \'Bob\');  -- \'Alice, Bob\'',
      '',
      '-- GROUP_CONCAT：将多行聚合为一个字符串（MySQL 特有）',
      'SELECT department,',
      '  GROUP_CONCAT(name ORDER BY name SEPARATOR \', \') AS employees',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '> **GROUP_CONCAT** 是 MySQL 版的 PostgreSQL `STRING_AGG`，对生成逗号分隔列表非常有用。',
      '',
      '### 正则表达式',
      '',
      '```sql',
      '-- REGEXP / RLIKE',
      'SELECT * FROM employees WHERE name REGEXP \'^[A-Z][a-z]+$\';',
      '',
      '-- REGEXP_REPLACE（MySQL 8.0+）',
      'SELECT REGEXP_REPLACE(\'Hello   World\', \' +\', \' \');  -- \'Hello World\'',
      '```',
      '',
      '---',
      '',
      '## 3. 日期和时间函数',
      '',
      '### 获取当前时间',
      '',
      '```sql',
      'SELECT',
      '  NOW(),        -- 2024-03-15 14:30:00（会话时区）',
      '  CURDATE(),    -- 2024-03-15',
      '  CURTIME(),    -- 14:30:00',
      '  UTC_TIMESTAMP();',
      '```',
      '',
      '### 提取日期部分',
      '',
      '```sql',
      'SELECT',
      '  YEAR(\'2024-03-15\'),     -- 2024',
      '  MONTH(\'2024-03-15\'),    -- 3',
      '  DAY(\'2024-03-15\'),      -- 15',
      '  DAYOFWEEK(\'2024-03-15\'); -- 6（1=周日）',
      '```',
      '',
      '### 日期计算',
      '',
      '```sql',
      '-- DATE_ADD / DATE_SUB',
      'SELECT DATE_ADD(\'2024-01-01\', INTERVAL 30 DAY);   -- 2024-01-31',
      'SELECT DATE_SUB(\'2024-03-15\', INTERVAL 1 YEAR);   -- 2023-03-15',
      '',
      '-- DATEDIFF：天数差',
      'SELECT DATEDIFF(\'2024-12-31\', \'2024-01-01\');     -- 365',
      '',
      '-- TIMESTAMPDIFF：任意单位的差值',
      'SELECT TIMESTAMPDIFF(YEAR, \'1990-05-20\', NOW());  -- 年龄',
      '```',
      '',
      '### 日期格式化',
      '',
      '```sql',
      '-- DATE_FORMAT：使用格式说明符格式化日期',
      'SELECT DATE_FORMAT(NOW(), \'%Y-%m-%d\');            -- 2024-03-15',
      'SELECT DATE_FORMAT(NOW(), \'%W, %M %d %Y\');        -- Friday, March 15 2024',
      '',
      '-- STR_TO_DATE：将字符串解析为日期',
      'SELECT STR_TO_DATE(\'15/03/2024\', \'%d/%m/%Y\');    -- 2024-03-15',
      '```',
      '',
      '---',
      '',
      '## 4. 流程控制函数',
      '',
      '```sql',
      '-- IF(条件, 真值, 假值)',
      'SELECT name, IF(salary > 80000, \'Senior\', \'Junior\') AS level',
      'FROM employees;',
      '',
      '-- IFNULL：如果为 NULL 则返回备用值',
      'SELECT IFNULL(salary, 0) FROM employees;',
      '',
      '-- NULLIF：相等则返回 NULL（防除零）',
      'SELECT total / NULLIF(quantity, 0) FROM orders;',
      '',
      '-- COALESCE：返回第一个非 NULL 值',
      'SELECT COALESCE(preferred_name, first_name, \'Unknown\') FROM users;',
      '```',
      '',
      '---',
      '',
      '## 5. Upsert 模式',
      '',
      '```sql',
      '-- ON DUPLICATE KEY UPDATE（最灵活）',
      'INSERT INTO page_views (page_id, view_date, count)',
      'VALUES (101, CURDATE(), 1)',
      'ON DUPLICATE KEY UPDATE count = count + 1;',
      '',
      '-- INSERT IGNORE：静默忽略重复键错误',
      'INSERT IGNORE INTO users (email, name)',
      'VALUES (\'alice@example.com\', \'Alice\');',
      '```',
      '',
      '---',
      '',
      '## 6. 窗口函数（MySQL 8.0+）',
      '',
      '```sql',
      '-- 排名函数',
      'SELECT name, salary, department,',
      '  ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS row_num,',
      '  RANK()       OVER (PARTITION BY department ORDER BY salary DESC) AS rnk,',
      '  DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dense_rnk',
      'FROM employees;',
      '',
      '-- LAG / LEAD：访问前后行',
      'SELECT order_date, revenue,',
      '  LAG(revenue)  OVER (ORDER BY order_date) AS prev_revenue,',
      '  LEAD(revenue) OVER (ORDER BY order_date) AS next_revenue',
      'FROM daily_sales;',
      '',
      '-- 累计求和',
      'SELECT order_date, revenue,',
      '  SUM(revenue) OVER (ORDER BY order_date ROWS UNBOUNDED PRECEDING) AS running_total',
      'FROM daily_sales;',
      '```',
      '',
      '---',
      '',
      '## 7. JSON 函数（MySQL 8.0+）',
      '',
      '```sql',
      '-- -> 返回 JSON 格式，->> 返回文本格式',
      'SELECT attributes->\'$.cpu\'  AS cpu_json,',
      '       attributes->>\'$.cpu\' AS cpu_text',
      'FROM products;',
      '',
      '-- JSON_SET：设置 JSON 字段值',
      'UPDATE products',
      'SET attributes = JSON_SET(attributes, \'$.storage\', \'512GB\')',
      'WHERE id = 1;',
      '',
      '-- JSON_ARRAYAGG：聚合为 JSON 数组',
      'SELECT department, JSON_ARRAYAGG(name) AS names',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '---',
      '',
      '## 8. 事务',
      '',
      '```sql',
      'START TRANSACTION;',
      '',
      'UPDATE accounts SET balance = balance - 500 WHERE id = 1;',
      'UPDATE accounts SET balance = balance + 500 WHERE id = 2;',
      '',
      'COMMIT;   -- 成功提交',
      '-- 或',
      'ROLLBACK; -- 出错回滚',
      '',
      '-- 保存点',
      'START TRANSACTION;',
      '  INSERT INTO orders ...',
      '  SAVEPOINT after_order;',
      '  INSERT INTO order_items ...',
      '  ROLLBACK TO SAVEPOINT after_order;  -- 只回滚到保存点',
      'COMMIT;',
      '```',
      '',
      '---',
      '',
      '## 9. 性能调优',
      '',
      '```sql',
      '-- EXPLAIN：分析查询执行计划',
      'EXPLAIN SELECT * FROM employees WHERE department = \'Engineering\';',
      '-- type 列：ALL（全表扫描）< range < ref < eq_ref < const（最佳）',
      '',
      '-- EXPLAIN ANALYZE（MySQL 8.0.18+）：实际执行并返回计划',
      'EXPLAIN ANALYZE SELECT * FROM orders WHERE customer_id = 101;',
      '',
      '-- 创建索引',
      'CREATE INDEX idx_dept ON employees (department);',
      'CREATE INDEX idx_dept_salary ON employees (department, salary);  -- 复合索引',
      '',
      '-- 避免在索引列上使用函数（会导致索引失效）',
      'SELECT * FROM orders WHERE YEAR(created_at) = 2024;  -- 不走索引',
      'SELECT * FROM orders',
      '  WHERE created_at >= \'2024-01-01\' AND created_at < \'2025-01-01\';  -- 走索引',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 595, title: 'Big Countries', titleZh: '大的国家', difficulty: 'Easy' },
    { id: 620, title: 'Not Boring Movies', titleZh: '有趣的电影', difficulty: 'Easy' },
    { id: 1179, title: 'Reformat Department Table', titleZh: '重新格式化部门表', difficulty: 'Easy' },
    { id: 196, title: 'Delete Duplicate Emails', titleZh: '删除重复的电子邮箱', difficulty: 'Easy' },
    { id: 177, title: 'Nth Highest Salary', titleZh: '第N高的薪水', difficulty: 'Medium' },
  ],
}
