import type { TopicContent } from '../../types'

export const oracleSQLContent: TopicContent = {
  id: 'sql-oracle',
  title: { en: 'Oracle SQL Essentials', zh: 'Oracle SQL 精要' },
  description: {
    en: 'Oracle-specific features: ROWNUM, ROWID, DUAL, sequences, NVL, DECODE, hierarchical queries, and MERGE',
    zh: 'Oracle 特有功能：ROWNUM、ROWID、DUAL、序列、NVL、DECODE、层次查询和 MERGE',
  },
  timeEstimate: '70 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## Oracle vs Standard SQL — Key Differences',
      '',
      'Oracle SQL has been around since the 1970s and has many proprietary extensions. Modern Oracle (12c+) added SQL standard features, but legacy syntax is still everywhere.',
      '',
      '```',
      'Feature              Standard SQL      Oracle SQL',
      '───────────────────  ────────────────  ────────────────────────',
      'Limit rows           LIMIT n           ROWNUM / FETCH FIRST n ROWS',
      'String concat        CONCAT() / ||     || (native)',
      'NULL check           IS NULL           IS NULL + NVL()',
      'Conditional          CASE WHEN         CASE WHEN + DECODE()',
      'Date arithmetic      DATE ± INTERVAL   DATE ± number (days)',
      'Dual-table dummy     (none)            DUAL',
      'Auto-increment       IDENTITY          SEQUENCE + TRIGGER',
      'Top-N query          LIMIT             ROWNUM / ROW_NUMBER()',
      'Hierarchy query      Recursive CTE     CONNECT BY',
      'Upsert               MERGE             MERGE (Oracle 9i+)',
      '```',
      '',
      '## The DUAL Table',
      '',
      'DUAL is a special one-row, one-column table used when you need a SELECT without a real source table.',
      '',
      '```sql',
      '-- Evaluate an expression',
      'SELECT 1 + 1 FROM DUAL;',
      "SELECT UPPER('hello') FROM DUAL;",
      "SELECT SYSDATE FROM DUAL;   -- current date/time",
      '',
      '-- Convert a value using a function without a table',
      "SELECT TO_DATE('2024-03-15', 'YYYY-MM-DD') FROM DUAL;",
      "SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;",
      '```',
      '',
      '## ROWNUM — Row Count Pseudocolumn',
      '',
      'ROWNUM is a pseudocolumn that numbers output rows **before ORDER BY is applied**. This is the most common Oracle gotcha.',
      '',
      '```sql',
      '-- WRONG: ROWNUM is assigned before ORDER BY, so you get random top-10',
      'SELECT * FROM employees',
      'WHERE ROWNUM <= 10',
      'ORDER BY salary DESC;    -- ORDER BY happens AFTER ROWNUM is assigned!',
      '',
      '-- CORRECT: wrap in a subquery to order first, then limit',
      'SELECT *',
      'FROM (',
      '  SELECT * FROM employees ORDER BY salary DESC',
      ')',
      'WHERE ROWNUM <= 10;',
      '',
      '-- Pagination with ROWNUM (legacy — before Oracle 12c)',
      'SELECT *',
      'FROM (',
      '  SELECT e.*, ROWNUM AS rn',
      '  FROM (',
      '    SELECT * FROM employees ORDER BY salary DESC',
      '  ) e',
      '  WHERE ROWNUM <= 20   -- page 2 ends at row 20',
      ')',
      'WHERE rn >= 11;        -- page 2 starts at row 11',
      '```',
      '',
      '## FETCH FIRST — Modern Oracle Pagination (12c+)',
      '',
      '```sql',
      '-- Much cleaner than ROWNUM',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'FETCH FIRST 10 ROWS ONLY;',
      '',
      '-- With offset (pagination)',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;   -- rows 11-20',
      '',
      '-- WITH TIES: include rows that tie for last position',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'FETCH FIRST 3 ROWS WITH TIES;',
      '```',
      '',
      '## ROWID — Physical Row Address',
      '',
      'ROWID is the physical address of a row on disk. Useful for finding and deleting duplicates efficiently.',
      '',
      '```sql',
      '-- Show ROWIDs',
      'SELECT ROWID, name, email FROM employees;',
      '',
      '-- Delete duplicate emails, keeping the oldest (smallest ROWID)',
      'DELETE FROM employees',
      'WHERE ROWID NOT IN (',
      '  SELECT MIN(ROWID)',
      '  FROM employees',
      '  GROUP BY email',
      ');',
      '```',
      '',
      '## NVL and NVL2 — NULL Substitution',
      '',
      '```sql',
      '-- NVL(expr, default): return default if expr is NULL',
      "SELECT name, NVL(manager_id, 0) AS mgr  -- 0 if no manager",
      'FROM employees;',
      '',
      '-- NVL2(expr, not_null_result, null_result)',
      "SELECT name, NVL2(manager_id, 'Has Manager', 'Top Level') AS mgr_status",
      'FROM employees;',
      '',
      '-- COALESCE (standard SQL, also works in Oracle): first non-NULL value',
      "SELECT COALESCE(nickname, first_name, 'Unknown') AS display_name",
      'FROM users;',
      '',
      '-- NULLIF(a, b): returns NULL if a = b, else returns a',
      'SELECT NULLIF(actual_hours, 0)   -- avoid division by zero',
      'FROM timesheets;',
      '```',
      '',
      '## DECODE — Oracle Conditional Function',
      '',
      'DECODE is Oracle\'s proprietary conditional expression, predating CASE WHEN. Still found in legacy code.',
      '',
      '```sql',
      '-- DECODE(expression, search1, result1, search2, result2, ..., default)',
      "SELECT name,",
      "       DECODE(department,",
      "              'Engineering', 'Tech',",
      "              'Product',     'Tech',",
      "              'HR',          'People',",
      "              'Other'",
      "       ) AS dept_group",
      'FROM employees;',
      '',
      '-- Equivalent CASE WHEN (preferred in modern SQL):',
      "SELECT name,",
      "       CASE department",
      "         WHEN 'Engineering' THEN 'Tech'",
      "         WHEN 'Product'     THEN 'Tech'",
      "         WHEN 'HR'          THEN 'People'",
      "         ELSE                    'Other'",
      "       END AS dept_group",
      'FROM employees;',
      '```',
      '',
      '## Date Functions in Oracle',
      '',
      '```sql',
      '-- Current date/time',
      'SELECT SYSDATE     FROM DUAL;   -- server date+time (no timezone)',
      'SELECT SYSTIMESTAMP FROM DUAL;  -- with timezone',
      'SELECT CURRENT_DATE FROM DUAL;  -- session timezone',
      '',
      '-- Date arithmetic: Oracle dates are numbers (1 unit = 1 day)',
      "SELECT SYSDATE + 7      FROM DUAL;   -- 7 days from now",
      "SELECT SYSDATE - 1      FROM DUAL;   -- yesterday",
      "SELECT SYSDATE + 1/24   FROM DUAL;   -- 1 hour from now",
      '',
      '-- Difference between two dates returns NUMBER of days',
      'SELECT hire_date, SYSDATE - hire_date AS days_employed',
      'FROM employees;',
      '',
      '-- TO_DATE: string → date',
      "SELECT TO_DATE('15-MAR-2024', 'DD-MON-YYYY') FROM DUAL;",
      "SELECT TO_DATE('2024/03/15', 'YYYY/MM/DD')   FROM DUAL;",
      '',
      '-- TO_CHAR: date/number → string',
      "SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')          FROM DUAL;",
      "SELECT TO_CHAR(SYSDATE, 'Day, DD Month YYYY')  FROM DUAL;",
      "SELECT TO_CHAR(salary, '$999,999.99')          FROM employees;",
      '',
      '-- ADD_MONTHS, MONTHS_BETWEEN, LAST_DAY',
      'SELECT ADD_MONTHS(SYSDATE, 3)              FROM DUAL;  -- 3 months later',
      'SELECT MONTHS_BETWEEN(SYSDATE, hire_date)  FROM employees;',
      'SELECT LAST_DAY(SYSDATE)                   FROM DUAL;  -- last day of this month',
      '',
      '-- TRUNC: truncate to day/month/year',
      "SELECT TRUNC(SYSDATE)             FROM DUAL;  -- remove time part",
      "SELECT TRUNC(SYSDATE, 'MM')       FROM DUAL;  -- first day of month",
      "SELECT TRUNC(SYSDATE, 'YYYY')     FROM DUAL;  -- first day of year",
      '```',
      '',
      '## Sequences — Auto-Increment in Oracle',
      '',
      'Oracle does not have an IDENTITY column before 12c. Use a SEQUENCE instead.',
      '',
      '```sql',
      '-- Create a sequence',
      'CREATE SEQUENCE emp_seq',
      '  START WITH 1',
      '  INCREMENT BY 1',
      '  NOCACHE',
      '  NOCYCLE;',
      '',
      '-- Use in INSERT',
      'INSERT INTO employees (emp_id, name)',
      "VALUES (emp_seq.NEXTVAL, 'Alice');",
      '',
      '-- Get current value (only after NEXTVAL in same session)',
      'SELECT emp_seq.CURRVAL FROM DUAL;',
      '',
      '-- Oracle 12c+ IDENTITY column (no sequence needed)',
      'CREATE TABLE employees (',
      '  emp_id  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,',
      '  name    VARCHAR2(100)',
      ');',
      '```',
      '',
      '## CONNECT BY — Hierarchical Queries',
      '',
      'Oracle\'s proprietary way to traverse tree structures (org charts, folder trees).',
      '',
      '```sql',
      '-- Traverse org chart from the CEO down',
      'SELECT LEVEL,',
      '       LPAD(\' \', (LEVEL-1)*2) || name AS org_tree,',
      '       emp_id,',
      '       manager_id',
      'FROM employees',
      'START WITH manager_id IS NULL         -- root: no manager = CEO',
      'CONNECT BY PRIOR emp_id = manager_id  -- parent\'s emp_id = child\'s manager_id',
      'ORDER SIBLINGS BY name;               -- sort siblings alphabetically',
      '',
      '-- LEVEL pseudocolumn: 1 for root, 2 for children, 3 for grandchildren...',
      '-- PRIOR refers to the parent row',
      '',
      '-- Find all direct and indirect reports of employee 10',
      'SELECT name, LEVEL AS depth',
      'FROM employees',
      'START WITH emp_id = 10',
      'CONNECT BY PRIOR emp_id = manager_id;',
      '',
      '-- Find all managers of employee 42 up to root',
      'SELECT name, LEVEL AS depth',
      'FROM employees',
      'START WITH emp_id = 42',
      'CONNECT BY PRIOR manager_id = emp_id;  -- note: PRIOR reversed',
      '```',
      '',
      '## MERGE — Upsert (Insert or Update)',
      '',
      'MERGE combines INSERT and UPDATE into one atomic statement. Essential for ETL and data synchronization.',
      '',
      '```sql',
      '-- Sync staging table into target table',
      'MERGE INTO employees tgt',
      'USING staging_employees src ON (tgt.emp_id = src.emp_id)',
      '',
      'WHEN MATCHED THEN',
      '  UPDATE SET',
      '    tgt.name   = src.name,',
      '    tgt.salary = src.salary',
      '',
      'WHEN NOT MATCHED THEN',
      '  INSERT (emp_id, name, salary)',
      '  VALUES (src.emp_id, src.name, src.salary);',
      '',
      '-- You can also add DELETE inside WHEN MATCHED:',
      'WHEN MATCHED THEN',
      '  UPDATE SET tgt.salary = src.salary',
      "  DELETE WHERE src.status = 'terminated'",
      '```',
      '',
      '## String Functions',
      '',
      '```sql',
      "-- Length",
      "SELECT LENGTH('Oracle SQL') FROM DUAL;  -- 10",
      '',
      '-- Substring: SUBSTR(string, start_position, length)',
      '-- Oracle positions are 1-based',
      "SELECT SUBSTR('Oracle SQL', 1, 6) FROM DUAL;  -- 'Oracle'",
      "SELECT SUBSTR('Oracle SQL', -3)   FROM DUAL;  -- 'SQL' (from end)",
      '',
      '-- Position of substring: INSTR(string, search, start, occurrence)',
      "SELECT INSTR('banana', 'a')     FROM DUAL;  -- 2",
      "SELECT INSTR('banana', 'a', 3)  FROM DUAL;  -- 4 (start from pos 3)",
      '',
      '-- Pad string',
      "SELECT LPAD('42', 5, '0') FROM DUAL;  -- '00042'",
      "SELECT RPAD('left', 8, '-') FROM DUAL; -- 'left----'",
      '',
      '-- Trim',
      "SELECT TRIM('  hello  ')        FROM DUAL;  -- 'hello'",
      "SELECT LTRIM(' hello')          FROM DUAL;  -- 'hello'",
      "SELECT RTRIM('hello ')          FROM DUAL;  -- 'hello'",
      "SELECT TRIM(LEADING '0' FROM '00042') FROM DUAL;  -- '42'",
      '',
      '-- Replace',
      "SELECT REPLACE('Hello World', 'World', 'Oracle') FROM DUAL;",
      '',
      '-- Regular expression support (Oracle 10g+)',
      "SELECT REGEXP_REPLACE('abc123def', '[0-9]+', 'NUM') FROM DUAL;",
      "SELECT REGEXP_SUBSTR('2024-03-15', '[0-9]{4}') FROM DUAL;  -- '2024'",
      '```',
      '',
      '## Analytical Functions (Oracle\'s Window Functions)',
      '',
      '```sql',
      '-- Oracle uses the same OVER() syntax as standard SQL',
      '-- but historically called them "analytic functions"',
      '',
      '-- Running total of salary',
      'SELECT name,',
      '       salary,',
      '       SUM(salary) OVER (ORDER BY hire_date',
      '                         ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total',
      'FROM employees;',
      '',
      '-- RATIO_TO_REPORT: each row\'s value as a fraction of the window total',
      'SELECT name,',
      '       salary,',
      '       RATIO_TO_REPORT(salary) OVER (PARTITION BY department) AS salary_pct',
      'FROM employees;',
      '',
      '-- LISTAGG: aggregate strings within a group (Oracle 11g+)',
      'SELECT department,',
      "       LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS employee_list",
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '## Exercise Set 6 — Oracle SQL',
      '',
      '**Exercise 1 (Easy):** List all employees hired in the last 180 days.',
      '',
      '```sql',
      'SELECT name, hire_date',
      'FROM employees',
      'WHERE hire_date >= SYSDATE - 180',
      'ORDER BY hire_date DESC;',
      '```',
      '',
      '**Exercise 2 (Easy):** Show each employee\'s name and how many complete years they have worked.',
      '',
      '```sql',
      'SELECT name,',
      '       TRUNC(MONTHS_BETWEEN(SYSDATE, hire_date) / 12) AS years_employed',
      'FROM employees',
      'ORDER BY years_employed DESC;',
      '```',
      '',
      '**Exercise 3 (Medium):** Print the org chart for the entire company using CONNECT BY, showing hierarchy with indentation.',
      '',
      '```sql',
      'SELECT LPAD(\' \', (LEVEL - 1) * 4) || name AS org_chart,',
      '       LEVEL AS depth',
      'FROM employees',
      'START WITH manager_id IS NULL',
      'CONNECT BY PRIOR emp_id = manager_id',
      'ORDER SIBLINGS BY name;',
      '```',
      '',
      '**Exercise 4 (Medium):** Using MERGE, synchronize the `employees` table with data from `employees_import`. Update salary if employee exists; insert if new.',
      '',
      '```sql',
      'MERGE INTO employees tgt',
      'USING employees_import src',
      '  ON (tgt.emp_id = src.emp_id)',
      'WHEN MATCHED THEN',
      '  UPDATE SET tgt.salary = src.salary, tgt.name = src.name',
      'WHEN NOT MATCHED THEN',
      '  INSERT (emp_id, name, salary, hire_date)',
      '  VALUES (src.emp_id, src.name, src.salary, src.hire_date);',
      '```',
      '',
      '**Exercise 5 (Hard):** Paginate employees ordered by salary, returning page 3 (rows 21-30) using FETCH FIRST / OFFSET.',
      '',
      '```sql',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;',
      '```',
      '',
      '**Exercise 6 (Hard):** Use LISTAGG to produce a comma-separated list of employee names per department.',
      '',
      '```sql',
      'SELECT department,',
      "       LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS members",
      'FROM employees',
      'GROUP BY department',
      'ORDER BY department;',
      '```',
    ].join('\n'),
    zh: [
      '## Oracle SQL vs 标准 SQL——关键差异',
      '',
      'Oracle SQL 自 1970 年代起存在，有很多专有扩展。现代 Oracle（12c+）添加了 SQL 标准功能，但传统语法随处可见。',
      '',
      '```',
      '功能              标准 SQL          Oracle SQL',
      '──────────────    ────────────────  ────────────────────────',
      '限制行数          LIMIT n           ROWNUM / FETCH FIRST n ROWS',
      '字符串拼接        CONCAT() / ||     || （原生）',
      'NULL 检查         IS NULL           IS NULL + NVL()',
      '条件表达式        CASE WHEN         CASE WHEN + DECODE()',
      '日期运算          DATE ± INTERVAL   DATE ± 数字（天）',
      '虚表              （无）            DUAL',
      '自增主键          IDENTITY          SEQUENCE + TRIGGER',
      '前 N 行           LIMIT             ROWNUM / ROW_NUMBER()',
      '层次查询          递归 CTE          CONNECT BY',
      '更新插入          MERGE             MERGE（Oracle 9i+）',
      '```',
      '',
      '## DUAL 表',
      '',
      'DUAL 是一个特殊的单行单列表，在不需要真实源表时用于 SELECT。',
      '',
      '```sql',
      '-- 计算表达式',
      'SELECT 1 + 1 FROM DUAL;',
      "SELECT UPPER('hello') FROM DUAL;",
      'SELECT SYSDATE FROM DUAL;   -- 当前日期/时间',
      '',
      '-- 日期格式转换',
      "SELECT TO_DATE('2024-03-15', 'YYYY-MM-DD') FROM DUAL;",
      "SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;",
      '```',
      '',
      '## ROWNUM——行计数伪列',
      '',
      'ROWNUM 是一个在 **ORDER BY 应用之前**为输出行编号的伪列。这是 Oracle 最常见的陷阱。',
      '',
      '```sql',
      '-- 错误：ROWNUM 在 ORDER BY 之前分配，所以得到随机的前 10 行',
      'SELECT * FROM employees',
      'WHERE ROWNUM <= 10',
      'ORDER BY salary DESC;    -- ORDER BY 在 ROWNUM 分配之后执行！',
      '',
      '-- 正确：用子查询先排序，再限制',
      'SELECT *',
      'FROM (',
      '  SELECT * FROM employees ORDER BY salary DESC',
      ')',
      'WHERE ROWNUM <= 10;',
      '```',
      '',
      '## FETCH FIRST——现代 Oracle 分页（12c+）',
      '',
      '```sql',
      '-- 比 ROWNUM 更简洁',
      'SELECT name, salary',
      'FROM employees',
      'ORDER BY salary DESC',
      'FETCH FIRST 10 ROWS ONLY;',
      '',
      '-- 带偏移量（分页）',
      'OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;   -- 第 11-20 行',
      '```',
      '',
      '## NVL 和 NVL2——NULL 替换',
      '',
      '```sql',
      '-- NVL(expr, 默认值)：expr 为 NULL 时返回默认值',
      "SELECT name, NVL(manager_id, 0) AS 经理ID  -- 无经理时为 0",
      'FROM employees;',
      '',
      '-- NVL2(expr, 非NULL结果, NULL结果)',
      "SELECT name, NVL2(manager_id, '有经理', '最高级') AS 经理状态",
      'FROM employees;',
      '```',
      '',
      '## DECODE——Oracle 条件函数',
      '',
      '```sql',
      '-- DECODE(表达式, 搜索1, 结果1, 搜索2, 结果2, ..., 默认值)',
      "SELECT name,",
      "       DECODE(department,",
      "              'Engineering', '技术',",
      "              'Product',     '技术',",
      "              'HR',          '人事',",
      "              '其他'",
      "       ) AS 部门分类",
      'FROM employees;',
      '```',
      '',
      '## Oracle 日期函数',
      '',
      '```sql',
      '-- 当前日期/时间',
      'SELECT SYSDATE FROM DUAL;      -- 服务器日期+时间（无时区）',
      'SELECT SYSTIMESTAMP FROM DUAL; -- 含时区',
      '',
      '-- 日期算术：Oracle 日期是数字（1 单位 = 1 天）',
      'SELECT SYSDATE + 7    FROM DUAL;   -- 7 天后',
      'SELECT SYSDATE + 1/24 FROM DUAL;   -- 1 小时后',
      '',
      '-- 两日期差返回天数',
      'SELECT hire_date, SYSDATE - hire_date AS 在职天数',
      'FROM employees;',
      '',
      '-- TO_DATE：字符串 → 日期',
      "SELECT TO_DATE('2024/03/15', 'YYYY/MM/DD') FROM DUAL;",
      '',
      '-- TO_CHAR：日期/数字 → 字符串',
      "SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')   FROM DUAL;",
      "SELECT TO_CHAR(salary, '$999,999.99')  FROM employees;",
      '',
      '-- ADD_MONTHS、MONTHS_BETWEEN、LAST_DAY',
      'SELECT ADD_MONTHS(SYSDATE, 3)             FROM DUAL;',
      'SELECT MONTHS_BETWEEN(SYSDATE, hire_date) FROM employees;',
      'SELECT LAST_DAY(SYSDATE)                  FROM DUAL;',
      '',
      '-- TRUNC：截断时间部分',
      "SELECT TRUNC(SYSDATE)       FROM DUAL;  -- 去除时间",
      "SELECT TRUNC(SYSDATE, 'MM') FROM DUAL;  -- 本月第一天",
      '```',
      '',
      '## 序列——Oracle 中的自增',
      '',
      '```sql',
      '-- 创建序列',
      'CREATE SEQUENCE emp_seq',
      '  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;',
      '',
      '-- 在 INSERT 中使用',
      'INSERT INTO employees (emp_id, name)',
      "VALUES (emp_seq.NEXTVAL, 'Alice');",
      '',
      '-- Oracle 12c+ IDENTITY 列',
      'CREATE TABLE employees (',
      '  emp_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,',
      '  name   VARCHAR2(100)',
      ');',
      '```',
      '',
      '## CONNECT BY——层次查询',
      '',
      '```sql',
      '-- 从 CEO 向下遍历组织架构',
      'SELECT LEVEL,',
      "       LPAD(' ', (LEVEL-1)*2) || name AS 组织树",
      'FROM employees',
      'START WITH manager_id IS NULL         -- 根节点：无经理 = CEO',
      'CONNECT BY PRIOR emp_id = manager_id  -- 父节点的 emp_id = 子节点的 manager_id',
      'ORDER SIBLINGS BY name;',
      '',
      '-- LEVEL 伪列：根为 1，子节点为 2，孙节点为 3...',
      '-- PRIOR 指向父行',
      '```',
      '',
      '## MERGE——更新插入（Upsert）',
      '',
      '```sql',
      'MERGE INTO employees tgt',
      'USING staging_employees src ON (tgt.emp_id = src.emp_id)',
      '',
      'WHEN MATCHED THEN',
      '  UPDATE SET tgt.name = src.name, tgt.salary = src.salary',
      '',
      'WHEN NOT MATCHED THEN',
      '  INSERT (emp_id, name, salary)',
      '  VALUES (src.emp_id, src.name, src.salary);',
      '```',
      '',
      '## LISTAGG——字符串聚合',
      '',
      '```sql',
      '-- 每个部门员工姓名的逗号分隔列表',
      'SELECT department,',
      "       LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS 成员列表",
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '## 练习题 6——Oracle SQL',
      '',
      '**练习 1（简单）：** 列出过去 180 天内入职的员工。',
      '',
      '```sql',
      'SELECT name, hire_date',
      'FROM employees',
      'WHERE hire_date >= SYSDATE - 180',
      'ORDER BY hire_date DESC;',
      '```',
      '',
      '**练习 2（中等）：** 用 CONNECT BY 打印整个公司的层次组织架构，带缩进。',
      '',
      '```sql',
      "SELECT LPAD(' ', (LEVEL - 1) * 4) || name AS 组织架构",
      'FROM employees',
      'START WITH manager_id IS NULL',
      'CONNECT BY PRIOR emp_id = manager_id',
      'ORDER SIBLINGS BY name;',
      '```',
      '',
      '**练习 3（中等）：** 用 MERGE 将 `employees_import` 数据同步到 `employees`。',
      '',
      '```sql',
      'MERGE INTO employees tgt',
      'USING employees_import src ON (tgt.emp_id = src.emp_id)',
      'WHEN MATCHED THEN',
      '  UPDATE SET tgt.salary = src.salary',
      'WHEN NOT MATCHED THEN',
      '  INSERT (emp_id, name, salary, hire_date)',
      '  VALUES (src.emp_id, src.name, src.salary, src.hire_date);',
      '```',
      '',
      '**练习 4（困难）：** 用 LISTAGG 生成每个部门员工的逗号分隔列表，并显示总人数。',
      '',
      '```sql',
      'SELECT department,',
      "       LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS 成员列表,",
      '       COUNT(*) AS 人数',
      'FROM employees',
      'GROUP BY department',
      'ORDER BY 人数 DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 511, title: 'Game Play Analysis I', titleZh: '游戏玩法分析 I', difficulty: 'Easy' },
    { id: 550, title: 'Game Play Analysis IV', titleZh: '游戏玩法分析 IV', difficulty: 'Medium' },
    { id: 607, title: 'Sales Person', titleZh: '销售员', difficulty: 'Easy' },
    { id: 608, title: 'Tree Node', titleZh: '树节点', difficulty: 'Medium' },
  ],
}
