import type { TopicContent } from '../../types'

export const postgresqlContent: TopicContent = {
  id: 'sql-postgresql',
  title: { en: 'PostgreSQL Deep Dive', zh: 'PostgreSQL 深度指南' },
  description: {
    en: 'Master PostgreSQL-specific features: JSONB, arrays, DISTINCT ON, upsert, full-text search, window functions, and advanced data types',
    zh: '掌握 PostgreSQL 特有功能：JSONB、数组、DISTINCT ON、插入更新、全文搜索、窗口函数和高级数据类型',
  },
  timeEstimate: '90 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## Why PostgreSQL?',
      '',
      'PostgreSQL ("Postgres") is the most feature-complete open-source relational database. It follows the SQL standard closely, adds powerful extensions (JSONB, arrays, full-text search), and is the default choice for most modern web applications (used by GitHub, Instagram, Shopify, Discord, and more).',
      '',
      '```',
      'Feature                 Standard SQL   PostgreSQL',
      '──────────────────────  ─────────────  ────────────────────────────',
      'Auto-increment          IDENTITY       SERIAL / BIGSERIAL / IDENTITY',
      'JSON storage            —              JSON / JSONB (indexed)',
      'Array columns           —              ARRAY type, operators',
      'Limit first-row/group   —              DISTINCT ON',
      'Upsert                  —              ON CONFLICT DO UPDATE',
      'Return modified rows    —              RETURNING clause',
      'Full-text search        —              tsvector / tsquery',
      'Correlated inline query —              LATERAL JOIN',
      'String aggregation      —              string_agg()',
      'Range types             —              int4range, daterange…',
      'UUID type               —              uuid (native)',
      '```',
      '',
      '## Data Types — What Makes PostgreSQL Unique',
      '',
      '```sql',
      '-- Auto-increment primary keys',
      'CREATE TABLE employees (',
      '  id         BIGSERIAL PRIMARY KEY,     -- auto-incrementing BIGINT',
      '  emp_code   SERIAL,                    -- auto-incrementing INT',
      '  -- Modern standard syntax (PostgreSQL 10+):',
      '  emp_id     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY',
      ');',
      '',
      '-- Text: PostgreSQL recommends TEXT over VARCHAR(n)',
      '-- TEXT has no performance penalty vs VARCHAR; no need to pick a length',
      'CREATE TABLE articles (',
      '  id      BIGSERIAL PRIMARY KEY,',
      '  title   TEXT NOT NULL,',
      '  body    TEXT,',
      '  tags    TEXT[],          -- array of text',
      '  meta    JSONB,           -- binary JSON (indexable)',
      '  score   NUMERIC(5,2),    -- exact decimal (use for money!)',
      '  rating  REAL,            -- floating point (use for science/stats)',
      '  active  BOOLEAN NOT NULL DEFAULT TRUE,',
      '  created TIMESTAMPTZ NOT NULL DEFAULT NOW()  -- timestamp WITH timezone',
      ');',
      '',
      '-- UUID type',
      'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";',
      'SELECT uuid_generate_v4();   -- random UUID: a1b2c3d4-...',
      '',
      '-- Enum type',
      "CREATE TYPE order_status AS ENUM ('pending','processing','shipped','delivered','cancelled');",
      'CREATE TABLE orders (id BIGSERIAL PRIMARY KEY, status order_status NOT NULL);',
      '```',
      '',
      '## String Functions — Top 20 Most Used',
      '',
      '```sql',
      '-- LENGTH / CHAR_LENGTH: character count',
      "SELECT LENGTH('hello');          -- 5",
      "SELECT CHAR_LENGTH('café');      -- 4 (counts characters, not bytes)",
      '',
      '-- UPPER / LOWER / INITCAP',
      "SELECT UPPER('hello world');     -- HELLO WORLD",
      "SELECT INITCAP('hello world');   -- Hello World",
      '',
      '-- TRIM / LTRIM / RTRIM',
      "SELECT TRIM('  hello  ');        -- 'hello'",
      "SELECT TRIM(BOTH 'x' FROM 'xxhelloxx');  -- 'hello'",
      '',
      '-- SUBSTRING / LEFT / RIGHT',
      "SELECT SUBSTRING('hello world', 7, 5);   -- 'world'  (start, length)",
      "SELECT SUBSTRING('hello world' FROM 7);   -- 'world'  (from position)",
      "SELECT LEFT('hello', 3);                  -- 'hel'",
      "SELECT RIGHT('hello', 3);                 -- 'llo'",
      '',
      '-- POSITION / STRPOS: find substring',
      "SELECT POSITION('lo' IN 'hello');    -- 4",
      "SELECT STRPOS('hello', 'lo');        -- 4",
      '',
      '-- REPLACE',
      "SELECT REPLACE('hello world', 'world', 'postgres');  -- 'hello postgres'",
      '',
      '-- SPLIT_PART: split by delimiter, pick piece',
      "SELECT SPLIT_PART('2024-03-15', '-', 2);   -- '03' (month)",
      '',
      '-- CONCAT / || operator',
      "SELECT 'Hello' || ' ' || 'World';",
      "SELECT CONCAT('Hello', ' ', 'World');",
      "SELECT CONCAT_WS(', ', 'Alice', 'Bob', 'Carol');  -- 'Alice, Bob, Carol'",
      '',
      '-- FORMAT: sprintf-style',
      "SELECT FORMAT('Hello %s, you are %s years old', 'Alice', 30);",
      '',
      '-- LPAD / RPAD',
      "SELECT LPAD('42', 6, '0');    -- '000042'",
      "SELECT RPAD('hello', 8, '.');  -- 'hello...'",
      '',
      '-- REGEXP_REPLACE / REGEXP_MATCHES',
      "SELECT REGEXP_REPLACE('Phone: 123-456-7890', '[0-9-]', '', 'g');  -- 'Phone: '",
      "SELECT REGEXP_MATCHES('2024-03-15', '(\\d{4})-(\\d{2})-(\\d{2})');  -- {2024,03,15}",
      '',
      '-- REVERSE',
      "SELECT REVERSE('hello');  -- 'olleh'",
      '',
      '-- REPEAT',
      "SELECT REPEAT('ab', 3);   -- 'ababab'",
      '',
      '-- MD5 / SHA256',
      "SELECT MD5('password');",
      "SELECT ENCODE(SHA256('password'::bytea), 'hex');",
      '',
      '-- string_agg: aggregate strings (like GROUP_CONCAT in MySQL)',
      "SELECT department, STRING_AGG(name, ', ' ORDER BY name) AS members",
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '## Date & Time — Most Used Functions',
      '',
      '```sql',
      '-- Current date/time',
      'SELECT NOW();               -- 2024-03-15 14:30:00.123456+00 (with timezone)',
      'SELECT CURRENT_TIMESTAMP;   -- same as NOW()',
      'SELECT CURRENT_DATE;        -- 2024-03-15',
      'SELECT CURRENT_TIME;        -- 14:30:00.123456+00',
      "SELECT NOW() AT TIME ZONE 'America/New_York';  -- convert to timezone",
      '',
      '-- EXTRACT / DATE_PART: get part of a date',
      "SELECT EXTRACT(YEAR  FROM NOW());   -- 2024",
      "SELECT EXTRACT(MONTH FROM NOW());   -- 3",
      "SELECT EXTRACT(DOW   FROM NOW());   -- 0=Sunday, 6=Saturday",
      "SELECT EXTRACT(EPOCH FROM NOW());   -- Unix timestamp (seconds)",
      '',
      '-- DATE_TRUNC: truncate to precision',
      "SELECT DATE_TRUNC('month', NOW());   -- 2024-03-01 00:00:00",
      "SELECT DATE_TRUNC('week',  NOW());   -- start of current week (Monday)",
      "SELECT DATE_TRUNC('year',  NOW());   -- 2024-01-01 00:00:00",
      "SELECT DATE_TRUNC('hour',  NOW());   -- 2024-03-15 14:00:00",
      '',
      '-- Arithmetic with INTERVAL',
      "SELECT NOW() + INTERVAL '7 days';          -- 7 days from now",
      "SELECT NOW() - INTERVAL '1 month';         -- 1 month ago",
      "SELECT NOW() + INTERVAL '2 hours 30 minutes';",
      "SELECT '2024-03-15'::date + 30;            -- add 30 days",
      '',
      '-- AGE: human-readable difference',
      "SELECT AGE(NOW(), '1990-05-20'::date);     -- 33 years 9 mons 25 days",
      "SELECT AGE('2024-01-01', '2020-06-15');",
      '',
      '-- TO_CHAR: format date as string',
      "SELECT TO_CHAR(NOW(), 'YYYY-MM-DD');          -- '2024-03-15'",
      "SELECT TO_CHAR(NOW(), 'Day, DD Month YYYY');  -- 'Friday, 15 March 2024'",
      "SELECT TO_CHAR(NOW(), 'HH24:MI:SS');          -- '14:30:00'",
      "SELECT TO_CHAR(12345.67, '999,999.99');       -- '12,345.67'",
      '',
      '-- TO_DATE / TO_TIMESTAMP: parse string to date',
      "SELECT TO_DATE('15/03/2024', 'DD/MM/YYYY');",
      "SELECT TO_TIMESTAMP('2024-03-15 14:30', 'YYYY-MM-DD HH24:MI');",
      '',
      '-- Useful date expressions',
      '-- First day of current month:',
      "SELECT DATE_TRUNC('month', CURRENT_DATE);",
      '-- Last day of current month:',
      "SELECT (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month - 1 day')::date;",
      '-- Days between two dates:',
      "SELECT '2024-12-31'::date - '2024-01-01'::date;   -- 365",
      '```',
      '',
      '## JSONB — The Most Powerful PostgreSQL Feature',
      '',
      'JSONB stores JSON as a parsed binary structure with full index support. Use it for flexible schemas, configuration data, and semi-structured data.',
      '',
      '```sql',
      '-- Create table with JSONB column',
      'CREATE TABLE users (',
      '  id       BIGSERIAL PRIMARY KEY,',
      '  name     TEXT,',
      "  profile  JSONB NOT NULL DEFAULT '{}'",
      ');',
      '',
      "INSERT INTO users (name, profile) VALUES",
      "  ('Alice', '{\"age\": 30, \"city\": \"NYC\", \"skills\": [\"SQL\", \"Python\"]}'),",
      "  ('Bob',   '{\"age\": 25, \"city\": \"LA\",  \"skills\": [\"JS\", \"React\"]}');",
      '',
      '-- Operators:',
      "-- ->  : get JSON field as JSON",
      "-- ->> : get JSON field as TEXT",
      "-- #>  : get nested path as JSON",
      "-- #>> : get nested path as TEXT",
      '',
      "SELECT profile -> 'city'           FROM users;  -- \"NYC\" (JSON)",
      "SELECT profile ->> 'city'          FROM users;  -- NYC (text)",
      "SELECT profile -> 'skills' -> 0    FROM users;  -- \"SQL\" (first element)",
      "SELECT profile #>> '{skills,0}'    FROM users;  -- SQL (nested path as text)",
      '',
      '-- WHERE with JSONB',
      "SELECT name FROM users WHERE profile ->> 'city' = 'NYC';",
      "SELECT name FROM users WHERE (profile -> 'age')::int > 28;",
      '',
      '-- @> : does left JSON contain right JSON? (index-supported)',
      "SELECT name FROM users WHERE profile @> '{\"city\": \"NYC\"}';",
      "SELECT name FROM users WHERE profile @> '{\"skills\": [\"SQL\"]}';",
      '',
      '-- ? : does key exist?',
      "SELECT name FROM users WHERE profile ? 'age';",
      '',
      '-- ?| : any of these keys exist?',
      "SELECT name FROM users WHERE profile ?| ARRAY['age','score'];",
      '',
      '-- Build JSONB',
      "SELECT JSONB_BUILD_OBJECT('name', name, 'age', profile -> 'age') FROM users;",
      '',
      '-- Expand array to rows',
      "SELECT name, JSONB_ARRAY_ELEMENTS_TEXT(profile -> 'skills') AS skill",
      'FROM users;',
      '',
      '-- Update a JSONB field (|| merges)',
      "UPDATE users SET profile = profile || '{\"active\": true}' WHERE id = 1;",
      '',
      '-- Remove a key',
      "UPDATE users SET profile = profile - 'age' WHERE id = 1;",
      '',
      '-- GIN index for fast JSONB search',
      'CREATE INDEX idx_users_profile ON users USING GIN (profile);',
      '```',
      '',
      '## Arrays — Native Array Columns',
      '',
      '```sql',
      'CREATE TABLE posts (',
      '  id    BIGSERIAL PRIMARY KEY,',
      '  title TEXT,',
      '  tags  TEXT[]    -- array column',
      ');',
      '',
      "INSERT INTO posts (title, tags) VALUES",
      "  ('Intro to SQL',   ARRAY['sql','beginner','database']),",
      "  ('Advanced PG',    ARRAY['postgresql','advanced']),",
      "  ('Python & SQL',   ARRAY['python','sql']);",
      '',
      '-- @> : array contains?',
      "SELECT title FROM posts WHERE tags @> ARRAY['sql'];",
      '',
      '-- && : arrays overlap (any element in common)?',
      "SELECT title FROM posts WHERE tags && ARRAY['sql','python'];",
      '',
      '-- ANY: value in array?',
      "SELECT title FROM posts WHERE 'sql' = ANY(tags);",
      '',
      '-- UNNEST: expand array to rows',
      'SELECT title, UNNEST(tags) AS tag FROM posts;',
      '',
      '-- ARRAY_AGG: aggregate values into array',
      'SELECT department, ARRAY_AGG(name ORDER BY name) AS employees',
      'FROM employees GROUP BY department;',
      '',
      '-- ARRAY_LENGTH / CARDINALITY',
      'SELECT title, ARRAY_LENGTH(tags, 1) AS tag_count FROM posts;  -- dimension 1',
      'SELECT title, CARDINALITY(tags) AS tag_count FROM posts;       -- same thing',
      '',
      '-- Array slicing',
      "SELECT tags[1:2] FROM posts;   -- first two elements (1-based!)",
      '',
      '-- ARRAY_APPEND / ARRAY_PREPEND / ARRAY_REMOVE',
      "UPDATE posts SET tags = ARRAY_APPEND(tags, 'new') WHERE id = 1;",
      "UPDATE posts SET tags = ARRAY_REMOVE(tags, 'beginner') WHERE id = 1;",
      '```',
      '',
      '## DISTINCT ON — Unique to PostgreSQL',
      '',
      'Returns the first row for each unique value of specified columns. Far faster than a correlated subquery for "latest record per group" problems.',
      '',
      '```sql',
      '-- Get the most recent order for each customer',
      'SELECT DISTINCT ON (cust_id)',
      '       cust_id, order_id, order_date, total',
      'FROM orders',
      'ORDER BY cust_id, order_date DESC;  -- ORDER BY must start with DISTINCT ON columns',
      '',
      '-- Get the highest-paid employee per department',
      'SELECT DISTINCT ON (dept_id)',
      '       dept_id, name, salary',
      'FROM employees',
      'ORDER BY dept_id, salary DESC;',
      '',
      '-- Equivalent but slower (correlated subquery):',
      '-- SELECT * FROM employees e1',
      '-- WHERE salary = (SELECT MAX(salary) FROM employees e2 WHERE e2.dept_id = e1.dept_id)',
      '```',
      '',
      '## UPSERT — INSERT ... ON CONFLICT',
      '',
      '```sql',
      '-- ON CONFLICT DO UPDATE (update on duplicate)',
      'INSERT INTO employees (emp_id, name, salary)',
      'VALUES (1, \'Alice\', 95000)',
      'ON CONFLICT (emp_id)',
      'DO UPDATE SET',
      '  name   = EXCLUDED.name,',
      '  salary = EXCLUDED.salary;',
      '',
      '-- EXCLUDED refers to the row that was not inserted',
      '',
      '-- ON CONFLICT DO NOTHING (ignore duplicates silently)',
      'INSERT INTO tags (name) VALUES (\'sql\'), (\'postgresql\'), (\'sql\')',
      'ON CONFLICT (name) DO NOTHING;',
      '',
      '-- Upsert with conditional update',
      'INSERT INTO product_prices (prod_id, price, updated_at)',
      'VALUES (42, 29.99, NOW())',
      'ON CONFLICT (prod_id) DO UPDATE SET',
      '  price      = EXCLUDED.price,',
      '  updated_at = EXCLUDED.updated_at',
      'WHERE product_prices.price <> EXCLUDED.price;  -- only update if price changed',
      '```',
      '',
      '## RETURNING — Get Data Back from INSERT/UPDATE/DELETE',
      '',
      '```sql',
      '-- Get the auto-generated ID after insert',
      'INSERT INTO employees (name, salary)',
      'VALUES (\'Alice\', 90000)',
      'RETURNING id, name;',
      '',
      '-- Get all rows after a bulk insert',
      'INSERT INTO departments (dept_name, location)',
      'VALUES (\'Engineering\', \'SF\'), (\'Sales\', \'NYC\')',
      'RETURNING *;',
      '',
      '-- Get updated rows',
      'UPDATE employees',
      'SET salary = salary * 1.10',
      'WHERE dept_id = 1',
      'RETURNING name, salary AS new_salary;',
      '',
      '-- Use RETURNING in a CTE',
      'WITH new_emp AS (',
      '  INSERT INTO employees (name, dept_id, salary)',
      '  VALUES (\'Bob\', 2, 80000)',
      '  RETURNING id, name',
      ')',
      'INSERT INTO audit_log (emp_id, action, changed_at)',
      "SELECT id, 'INSERT', NOW() FROM new_emp;",
      '```',
      '',
      '## Advanced Aggregation',
      '',
      '```sql',
      '-- FILTER: conditional aggregation without CASE (cleaner syntax)',
      'SELECT',
      '  COUNT(*)                                     AS total,',
      "  COUNT(*) FILTER (WHERE status = 'active')   AS active_count,",
      "  COUNT(*) FILTER (WHERE status = 'inactive') AS inactive_count,",
      "  AVG(salary) FILTER (WHERE dept_id = 1)      AS eng_avg_salary",
      'FROM employees;',
      '',
      '-- PERCENTILE_CONT: median and percentiles',
      'SELECT',
      '  PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY salary) AS median_salary,',
      '  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY salary) AS p25_salary,',
      '  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY salary) AS p75_salary',
      'FROM employees;',
      '',
      '-- PERCENTILE_DISC: nearest actual value',
      'SELECT PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY salary) FROM employees;',
      '',
      '-- MODE: most frequent value',
      'SELECT MODE() WITHIN GROUP (ORDER BY department) FROM employees;',
      '',
      '-- BOOL_AND / BOOL_OR',
      'SELECT department,',
      '       BOOL_AND(salary > 50000) AS all_above_50k,',
      '       BOOL_OR(salary > 150000) AS any_above_150k',
      'FROM employees',
      'GROUP BY department;',
      '',
      '-- CORR: Pearson correlation coefficient',
      'SELECT CORR(salary, years_experience) AS salary_experience_correlation',
      'FROM employees;',
      '',
      '-- JSON aggregation',
      'SELECT department,',
      '       JSON_AGG(name ORDER BY salary DESC) AS employees_json,',
      '       JSONB_AGG(JSONB_BUILD_OBJECT(\'name\', name, \'salary\', salary)) AS details',
      'FROM employees',
      'GROUP BY department;',
      '```',
      '',
      '## LATERAL JOIN — Row-by-Row Subquery',
      '',
      '`LATERAL` lets a subquery in `FROM` reference columns from tables listed earlier in `FROM`. Essential for "top N per group" and row-by-row transformations.',
      '',
      '```sql',
      '-- Top 3 employees per department',
      'SELECT d.dept_name, e.name, e.salary',
      'FROM departments d',
      'CROSS JOIN LATERAL (',
      '  SELECT name, salary',
      '  FROM employees',
      '  WHERE dept_id = d.dept_id',
      '  ORDER BY salary DESC',
      '  LIMIT 3',
      ') e;',
      '',
      '-- Expand JSON array to rows alongside the parent row',
      'SELECT u.name, skill',
      'FROM users u,',
      "LATERAL JSONB_ARRAY_ELEMENTS_TEXT(u.profile -> 'skills') AS skill;",
      '```',
      '',
      '## Full-Text Search',
      '',
      '```sql',
      '-- tsvector: a processed document (tokens + lexemes)',
      "SELECT TO_TSVECTOR('english', 'The quick brown fox jumps over the lazy dog');",
      "-- 'brown':3 'dog':9 'fox':4 'jump':5 'lazi':8 'quick':2",
      '',
      '-- tsquery: a search expression',
      "SELECT TO_TSQUERY('english', 'quick & fox');    -- quick AND fox",
      "SELECT TO_TSQUERY('english', 'quick | slow');   -- quick OR slow",
      "SELECT TO_TSQUERY('english', 'quick & !slow');  -- quick AND NOT slow",
      "SELECT PLAINTO_TSQUERY('english', 'quick brown fox');  -- auto AND",
      '',
      '-- @@ operator: does document match query?',
      "SELECT 'The quick brown fox'::tsvector @@ 'fox'::tsquery;  -- true",
      '',
      '-- Full-text search on a table',
      "SELECT title, body",
      "FROM articles",
      "WHERE TO_TSVECTOR('english', title || ' ' || body) @@ PLAINTO_TSQUERY('english', 'postgresql performance');",
      '',
      '-- TS_RANK: relevance scoring',
      "SELECT title,",
      "       TS_RANK(TO_TSVECTOR('english', body), query) AS rank",
      "FROM articles,",
      "     PLAINTO_TSQUERY('english', 'postgresql performance') query",
      "WHERE TO_TSVECTOR('english', body) @@ query",
      "ORDER BY rank DESC;",
      '',
      '-- Add a tsvector column for performance (pre-computed)',
      "ALTER TABLE articles ADD COLUMN search_vec TSVECTOR",
      "  GENERATED ALWAYS AS (TO_TSVECTOR('english', title || ' ' || COALESCE(body, ''))) STORED;",
      'CREATE INDEX idx_articles_fts ON articles USING GIN (search_vec);',
      '```',
      '',
      '## Math & Utility Functions',
      '',
      '```sql',
      '-- Numeric',
      'SELECT ROUND(3.14159, 2);      -- 3.14',
      'SELECT CEIL(4.1);              -- 5',
      'SELECT FLOOR(4.9);             -- 4',
      'SELECT TRUNC(4.9);             -- 4 (truncate, no rounding)',
      'SELECT ABS(-42);               -- 42',
      'SELECT POWER(2, 10);           -- 1024',
      'SELECT SQRT(144);              -- 12',
      'SELECT MOD(17, 5);             -- 2',
      'SELECT RANDOM();               -- 0.0 to 1.0',
      'SELECT FLOOR(RANDOM() * 100);  -- random int 0-99',
      '',
      '-- NULL handling',
      "SELECT COALESCE(NULL, NULL, 'default');     -- 'default'",
      "SELECT NULLIF(5, 5);                        -- NULL (equal → NULL)",
      "SELECT NULLIF(column, '');                  -- treat empty string as NULL",
      '',
      '-- Type casting',
      "SELECT '42'::integer;",
      "SELECT '3.14'::numeric;",
      "SELECT 42::text;",
      "SELECT '2024-03-15'::date;",
      "SELECT CAST('42' AS INTEGER);   -- standard SQL equivalent",
      '',
      '-- GENERATE_SERIES: generate sequences',
      'SELECT * FROM GENERATE_SERIES(1, 10);',
      "SELECT * FROM GENERATE_SERIES('2024-01-01'::date, '2024-12-31', INTERVAL '1 month');",
      '',
      '-- UNNEST with multiple arrays (zip)',
      "SELECT UNNEST(ARRAY['a','b','c']) AS letter,",
      '       UNNEST(ARRAY[1, 2, 3])   AS number;',
      '```',
      '',
      '## EXPLAIN ANALYZE — Understanding Query Performance',
      '',
      '```sql',
      '-- See the query execution plan',
      'EXPLAIN SELECT * FROM employees WHERE dept_id = 1;',
      '',
      '-- ANALYZE: actually run the query and show real timings',
      'EXPLAIN ANALYZE SELECT * FROM employees WHERE salary > 100000;',
      '',
      '-- VERBOSE + BUFFERS: full detail',
      'EXPLAIN (ANALYZE, VERBOSE, BUFFERS)',
      'SELECT e.name, d.dept_name',
      'FROM employees e JOIN departments d ON e.dept_id = d.dept_id',
      'WHERE e.salary > 80000;',
      '',
      '-- Key terms in output:',
      '-- Seq Scan:       full table scan (no index used)',
      '-- Index Scan:     using an index (fast for selective queries)',
      '-- Hash Join:      join using a hash table (good for large tables)',
      '-- Nested Loop:    join row-by-row (good when one side is small)',
      '-- cost=X..Y:      estimated startup cost .. total cost',
      '-- rows=N:         estimated row count',
      '-- actual time:    real milliseconds',
      '```',
      '',
      '## Exercise Set — PostgreSQL',
      '',
      '**Exercise 1 (Easy):** Write a query using `STRING_AGG` to list each department and a comma-separated list of employee names, sorted alphabetically.',
      '',
      '```sql',
      "SELECT d.dept_name,",
      "       STRING_AGG(e.name, ', ' ORDER BY e.name) AS members",
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id',
      'GROUP BY d.dept_id, d.dept_name',
      'ORDER BY d.dept_name;',
      '```',
      '',
      '**Exercise 2 (Easy):** Use `DATE_TRUNC` to count how many employees were hired in each calendar year.',
      '',
      '```sql',
      "SELECT DATE_TRUNC('year', hire_date::date) AS hire_year,",
      '       COUNT(*) AS hires',
      'FROM employees',
      "GROUP BY DATE_TRUNC('year', hire_date::date)",
      'ORDER BY hire_year;',
      '```',
      '',
      '**Exercise 3 (Medium):** Using `DISTINCT ON`, find the most recently hired employee in each department.',
      '',
      '```sql',
      'SELECT DISTINCT ON (dept_id)',
      '       dept_id, name, hire_date',
      'FROM employees',
      'ORDER BY dept_id, hire_date DESC;',
      '```',
      '',
      '**Exercise 4 (Medium):** Write an upsert: if an employee with `emp_id = 99` exists, update their salary; otherwise insert them.',
      '',
      '```sql',
      "INSERT INTO employees (emp_id, name, dept_id, salary, hire_date)",
      "VALUES (99, 'Test User', 1, 75000, CURRENT_DATE)",
      'ON CONFLICT (emp_id) DO UPDATE SET',
      '  salary = EXCLUDED.salary;',
      '```',
      '',
      '**Exercise 5 (Hard):** Use `PERCENTILE_CONT` to find the median salary per department, alongside the average.',
      '',
      '```sql',
      'SELECT d.dept_name,',
      '       ROUND(AVG(e.salary), 2) AS avg_salary,',
      '       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY e.salary) AS median_salary',
      'FROM employees e',
      'JOIN departments d ON e.dept_id = d.dept_id',
      'GROUP BY d.dept_id, d.dept_name',
      'ORDER BY avg_salary DESC;',
      '```',
    ].join('\n'),
    zh: [
      '## 为什么选择 PostgreSQL？',
      '',
      'PostgreSQL（"Postgres"）是功能最完整的开源关系型数据库。它严格遵循 SQL 标准，并添加了强大的扩展（JSONB、数组、全文搜索），是大多数现代 Web 应用的首选（GitHub、Instagram、Shopify、Discord 等均在使用）。',
      '',
      '## 数据类型——PostgreSQL 的独特之处',
      '',
      '```sql',
      '-- 自增主键',
      'CREATE TABLE employees (',
      '  id     BIGSERIAL PRIMARY KEY,   -- 自增 BIGINT',
      '  emp_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY  -- 现代标准语法',
      ');',
      '',
      '-- PostgreSQL 推荐使用 TEXT 而不是 VARCHAR(n)',
      '-- TEXT 性能与 VARCHAR 相同，无需指定长度',
      'CREATE TABLE articles (',
      '  id      BIGSERIAL PRIMARY KEY,',
      '  title   TEXT NOT NULL,',
      '  tags    TEXT[],          -- 文本数组',
      '  meta    JSONB,           -- 二进制 JSON（可索引）',
      '  score   NUMERIC(5,2),   -- 精确小数（用于金钱！）',
      '  active  BOOLEAN NOT NULL DEFAULT TRUE,',
      '  created TIMESTAMPTZ NOT NULL DEFAULT NOW()  -- 带时区的时间戳',
      ');',
      '```',
      '',
      '## 字符串函数——最常用的 20 个',
      '',
      '```sql',
      "-- 长度",
      "SELECT LENGTH('hello');          -- 5",
      "SELECT CHAR_LENGTH('café');      -- 4（按字符计，非字节）",
      '',
      '-- 大小写转换',
      "SELECT UPPER('hello world');     -- HELLO WORLD",
      "SELECT INITCAP('hello world');   -- Hello World",
      '',
      '-- 截取',
      "SELECT SUBSTRING('hello world', 7, 5);   -- 'world'（起始位置, 长度）",
      "SELECT LEFT('hello', 3);                  -- 'hel'",
      "SELECT RIGHT('hello', 3);                 -- 'llo'",
      '',
      '-- 查找子字符串',
      "SELECT STRPOS('hello', 'lo');    -- 4",
      '',
      '-- 分割',
      "SELECT SPLIT_PART('2024-03-15', '-', 2);  -- '03'（月份）",
      '',
      '-- 字符串聚合（类似 MySQL 的 GROUP_CONCAT）',
      "SELECT department, STRING_AGG(name, ', ' ORDER BY name) AS members",
      'FROM employees GROUP BY department;',
      '',
      '-- 格式化',
      "SELECT FORMAT('你好 %s，你已 %s 岁', 'Alice', 30);",
      '',
      '-- 正则替换',
      "SELECT REGEXP_REPLACE('电话：123-456', '[0-9-]', '', 'g');",
      '```',
      '',
      '## 日期时间——最常用的函数',
      '',
      '```sql',
      '-- 当前日期/时间',
      'SELECT NOW();               -- 带时区的当前时间',
      'SELECT CURRENT_DATE;        -- 当前日期',
      '',
      '-- EXTRACT / DATE_PART：获取日期部分',
      "SELECT EXTRACT(YEAR  FROM NOW());   -- 2024",
      "SELECT EXTRACT(MONTH FROM NOW());   -- 3",
      "SELECT EXTRACT(EPOCH FROM NOW());   -- Unix 时间戳（秒）",
      '',
      '-- DATE_TRUNC：截断到指定精度',
      "SELECT DATE_TRUNC('month', NOW());   -- 当月第一天",
      "SELECT DATE_TRUNC('week',  NOW());   -- 本周第一天（周一）",
      '',
      '-- INTERVAL 算术',
      "SELECT NOW() + INTERVAL '7 days';   -- 7 天后",
      "SELECT NOW() - INTERVAL '1 month';  -- 1 个月前",
      '',
      '-- AGE：计算年龄/时间差',
      "SELECT AGE(NOW(), '1990-05-20'::date);  -- 33 years 9 mons 25 days",
      '',
      '-- TO_CHAR：格式化日期为字符串',
      "SELECT TO_CHAR(NOW(), 'YYYY-MM-DD');          -- '2024-03-15'",
      "SELECT TO_CHAR(NOW(), 'HH24:MI:SS');          -- '14:30:00'",
      "SELECT TO_CHAR(12345.67, '999,999.99');       -- '12,345.67'",
      '```',
      '',
      '## JSONB——PostgreSQL 最强大的功能',
      '',
      'JSONB 以解析后的二进制结构存储 JSON，支持完整索引。用于灵活模式、配置数据和半结构化数据。',
      '',
      '```sql',
      '-- 操作符：',
      "-- ->  : 获取 JSON 字段（返回 JSON）",
      "-- ->> : 获取 JSON 字段（返回 TEXT）",
      "-- @>  : 左侧 JSON 是否包含右侧？（支持索引）",
      "-- ?   : 键是否存在？",
      '',
      "SELECT profile -> 'city'    FROM users;  -- \"NYC\"（JSON）",
      "SELECT profile ->> 'city'   FROM users;  -- NYC（文本）",
      '',
      "-- 包含查询（可用 GIN 索引加速）",
      "SELECT name FROM users WHERE profile @> '{\"city\": \"NYC\"}';",
      '',
      '-- 合并更新',
      "UPDATE users SET profile = profile || '{\"active\": true}' WHERE id = 1;",
      '',
      '-- GIN 索引',
      'CREATE INDEX idx_users_profile ON users USING GIN (profile);',
      '```',
      '',
      '## DISTINCT ON——PostgreSQL 独有',
      '',
      '返回指定列中每个唯一值的第一行。比相关子查询快得多，常用于"每组最新记录"问题。',
      '',
      '```sql',
      '-- 获取每个客户最近的订单',
      'SELECT DISTINCT ON (cust_id)',
      '       cust_id, order_id, order_date, total',
      'FROM orders',
      'ORDER BY cust_id, order_date DESC;  -- ORDER BY 必须以 DISTINCT ON 列开头',
      '```',
      '',
      '## UPSERT——INSERT ... ON CONFLICT',
      '',
      '```sql',
      '-- 冲突时更新',
      "INSERT INTO employees (emp_id, name, salary) VALUES (1, 'Alice', 95000)",
      'ON CONFLICT (emp_id) DO UPDATE SET',
      '  name = EXCLUDED.name, salary = EXCLUDED.salary;',
      '',
      '-- 冲突时忽略',
      "INSERT INTO tags (name) VALUES ('sql'), ('sql')",
      'ON CONFLICT (name) DO NOTHING;',
      '```',
      '',
      '## RETURNING——获取修改后的数据',
      '',
      '```sql',
      '-- 插入后获取自动生成的 ID',
      "INSERT INTO employees (name, salary) VALUES ('Alice', 90000)",
      'RETURNING id, name;',
      '',
      '-- 更新后获取新值',
      'UPDATE employees SET salary = salary * 1.10 WHERE dept_id = 1',
      'RETURNING name, salary AS new_salary;',
      '```',
      '',
      '## 高级聚合',
      '',
      '```sql',
      '-- FILTER：条件聚合（比 CASE WHEN 更简洁）',
      'SELECT',
      "  COUNT(*) FILTER (WHERE status = 'active')   AS 在职人数,",
      "  AVG(salary) FILTER (WHERE dept_id = 1)      AS 工程部平均薪资",
      'FROM employees;',
      '',
      '-- PERCENTILE_CONT：中位数和百分位数',
      'SELECT',
      '  PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY salary) AS 中位薪资,',
      '  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY salary) AS 第25百分位',
      'FROM employees;',
      '```',
      '',
      '## 练习题——PostgreSQL',
      '',
      '**练习 1（简单）：** 用 `STRING_AGG` 列出每个部门及按字母顺序排列的员工姓名列表。',
      '',
      '```sql',
      "SELECT d.dept_name,",
      "       STRING_AGG(e.name, ', ' ORDER BY e.name) AS members",
      'FROM employees e JOIN departments d ON e.dept_id = d.dept_id',
      'GROUP BY d.dept_id, d.dept_name ORDER BY d.dept_name;',
      '```',
      '',
      '**练习 2（中等）：** 使用 `DISTINCT ON` 找出每个部门最近入职的员工。',
      '',
      '```sql',
      'SELECT DISTINCT ON (dept_id) dept_id, name, hire_date',
      'FROM employees',
      'ORDER BY dept_id, hire_date DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 175, title: 'Combine Two Tables', titleZh: '组合两个表', difficulty: 'Easy' },
    { id: 184, title: 'Department Highest Salary', titleZh: '部门工资最高的员工', difficulty: 'Medium' },
    { id: 185, title: 'Department Top Three Salaries', titleZh: '部门工资前三高的所有员工', difficulty: 'Hard' },
    { id: 550, title: 'Game Play Analysis IV', titleZh: '游戏玩法分析 IV', difficulty: 'Medium' },
  ],
}
