import type { TopicContent } from '../../types'

export const sqlSubqueries: TopicContent = {
  id: 'sql-subqueries',
  title: { en: 'Subqueries & CTEs', zh: '子查询与 CTE' },
  description: {
    en: 'Write nested queries, correlated subqueries, and readable WITH clauses (Common Table Expressions)',
    zh: '编写嵌套查询、相关子查询和可读的 WITH 子句（公用表表达式）',
  },
  timeEstimate: '55 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## What Is a Subquery?',
      '',
      'A subquery (or inner query) is a SELECT statement nested inside another SQL statement. It can appear in SELECT, FROM, WHERE, or HAVING clauses.',
      '',
      '## Subquery in WHERE (Most Common)',
      '',
      '```sql',
      '-- Find employees who earn more than the company-wide average',
      'SELECT name, salary',
      'FROM employees',
      'WHERE salary > (SELECT AVG(salary) FROM employees);',
      '',
      '-- The inner query (SELECT AVG(salary) FROM employees)',
      '-- runs first and returns a single value, e.g., 75000',
      '-- Then the outer query runs: WHERE salary > 75000',
      '```',
      '',
      '**Subquery returning multiple values — use IN:**',
      '',
      '```sql',
      '-- Find employees who work in departments located in "New York"',
      'SELECT name',
      'FROM employees',
      'WHERE dept_id IN (',
      '  SELECT dept_id FROM departments WHERE location = \'New York\'',
      ');',
      '```',
      '',
      '**NOT IN / NOT EXISTS — rows that do NOT match:**',
      '',
      '```sql',
      '-- Employees with no orders (subquery approach)',
      'SELECT name',
      'FROM employees',
      'WHERE emp_id NOT IN (',
      '  SELECT DISTINCT emp_id FROM orders',
      ');',
      '',
      '-- WARNING: NOT IN returns no rows if the subquery contains any NULL!',
      '-- Safer alternative: NOT EXISTS',
      'SELECT name',
      'FROM employees e',
      'WHERE NOT EXISTS (',
      '  SELECT 1 FROM orders o WHERE o.emp_id = e.emp_id',
      ');',
      '```',
      '',
      '## Correlated Subqueries — Row-by-Row Execution',
      '',
      'A correlated subquery references columns from the outer query. It runs **once per row** of the outer query — potentially slow on large tables.',
      '',
      '```sql',
      '-- Find the highest-paid employee in each department',
      '-- (correlated: inner query references e.department from outer)',
      'SELECT name, department, salary',
      'FROM employees e',
      'WHERE salary = (',
      '  SELECT MAX(salary)',
      '  FROM employees',
      '  WHERE department = e.department   -- references outer query',
      ');',
      '',
      '-- Reads as: "For each employee, find the max salary in their department.',
      '-- Return the employee if their salary equals that max."',
      '```',
      '',
      '**EXISTS with correlated subquery:**',
      '',
      '```sql',
      '-- Customers who placed at least one order over $500',
      'SELECT c.name',
      'FROM customers c',
      'WHERE EXISTS (',
      '  SELECT 1',
      '  FROM orders o',
      '  WHERE o.customer_id = c.id',
      '    AND o.amount > 500',
      ');',
      '-- EXISTS stops as soon as ONE matching row is found (efficient)',
      '```',
      '',
      '## Subquery in FROM (Derived Table / Inline View)',
      '',
      'Put a subquery in the FROM clause to treat the result as a temporary table.',
      '',
      '```sql',
      '-- Average of department averages',
      'SELECT AVG(dept_avg) AS company_avg',
      'FROM (',
      '  SELECT department, AVG(salary) AS dept_avg',
      '  FROM employees',
      '  GROUP BY department',
      ') dept_summary;',
      '',
      '-- Top 5 customers by total spend, then join their details',
      'SELECT c.name, top5.total_spent',
      'FROM customers c',
      'JOIN (',
      '  SELECT customer_id, SUM(amount) AS total_spent',
      '  FROM orders',
      '  GROUP BY customer_id',
      '  ORDER BY total_spent DESC',
      '  LIMIT 5',
      ') top5 ON c.id = top5.customer_id;',
      '```',
      '',
      '## Subquery in SELECT (Scalar Subquery)',
      '',
      '```sql',
      '-- Show each department and the count of employees in it',
      'SELECT dept_name,',
      '       (SELECT COUNT(*)',
      '        FROM employees e',
      '        WHERE e.dept_id = d.dept_id) AS headcount',
      'FROM departments d;',
      '',
      '-- Must return exactly ONE row and ONE column per outer row',
      '```',
      '',
      '## Common Table Expressions (CTEs) — WITH Clause',
      '',
      'A CTE defines a named temporary result set that you can reference once in the main query. It makes complex queries far more readable than nested subqueries.',
      '',
      '```sql',
      '-- Syntax',
      'WITH cte_name AS (',
      '  SELECT ...',
      ')',
      'SELECT * FROM cte_name;',
      '',
      '-- Example: same "employees above average salary" query using CTE',
      'WITH company_avg AS (',
      '  SELECT AVG(salary) AS avg_sal FROM employees',
      ')',
      'SELECT name, salary',
      'FROM employees, company_avg',
      'WHERE salary > avg_sal;',
      '```',
      '',
      '**Multiple CTEs (chained):**',
      '',
      '```sql',
      'WITH',
      '-- Step 1: compute each department\'s total payroll',
      'dept_payroll AS (',
      '  SELECT dept_id, SUM(salary) AS total',
      '  FROM employees',
      '  GROUP BY dept_id',
      '),',
      '-- Step 2: rank departments by payroll',
      'ranked AS (',
      '  SELECT dept_id, total,',
      '         RANK() OVER (ORDER BY total DESC) AS rnk',
      '  FROM dept_payroll',
      ')',
      '-- Step 3: get the top 3 departments',
      'SELECT d.dept_name, r.total, r.rnk',
      'FROM ranked r',
      'JOIN departments d ON r.dept_id = d.dept_id',
      'WHERE r.rnk <= 3;',
      '```',
      '',
      '## Recursive CTEs — Hierarchical Data',
      '',
      'Recursive CTEs query tree/graph structures like org charts or bill of materials.',
      '',
      '```sql',
      '-- Walk the employee → manager hierarchy from bottom to top',
      'WITH RECURSIVE org_chart AS (',
      '  -- Base case: start with a specific employee',
      '  SELECT emp_id, name, manager_id, 0 AS depth',
      '  FROM employees',
      '  WHERE emp_id = 42',
      '',
      '  UNION ALL',
      '',
      '  -- Recursive case: find each row\'s manager',
      '  SELECT e.emp_id, e.name, e.manager_id, oc.depth + 1',
      '  FROM employees e',
      '  JOIN org_chart oc ON e.emp_id = oc.manager_id',
      ')',
      'SELECT name, depth FROM org_chart ORDER BY depth;',
      '',
      '-- Note: Oracle uses CONNECT BY instead of recursive CTEs (see Oracle chapter)',
      '```',
      '',
      '## CTE vs Subquery — When to Use Which',
      '',
      '```',
      'Subquery         CTE',
      '─────────────────────────────────────────',
      'Inline, anonymous Named, reusable in query',
      'Hard to read when Complex queries: CTE is cleaner',
      'deeply nested',
      'Can reference in  Referenced once in the main query',
      'multiple places   (standard CTEs are not reused)',
      '```',
      '',
      '**Rule of thumb:** if a subquery needs to be referenced more than once, or if the query has more than 2 levels of nesting, use a CTE.',
      '',
      '## Exercise Set 4 — Subqueries & CTEs',
      '',
      '**Exercise 1 (Easy):** Find employees whose salary is above the average salary of their own department.',
      '',
      '```sql',
      '-- Correlated subquery approach',
      'SELECT name, department, salary',
      'FROM employees e1',
      'WHERE salary > (',
      '  SELECT AVG(salary)',
      '  FROM employees e2',
      '  WHERE e2.department = e1.department',
      ');',
      '```',
      '',
      '**Exercise 2 (Medium — LeetCode 176):** Find the second highest salary. Return NULL if it does not exist.',
      '',
      '```sql',
      '-- Using subquery',
      'SELECT MAX(salary) AS SecondHighestSalary',
      'FROM employees',
      'WHERE salary < (SELECT MAX(salary) FROM employees);',
      '',
      '-- Using CTE + LIMIT',
      'WITH ranked AS (',
      '  SELECT DISTINCT salary',
      '  FROM employees',
      '  ORDER BY salary DESC',
      '  LIMIT 2',
      ')',
      'SELECT MIN(salary) AS SecondHighestSalary FROM ranked;',
      '```',
      '',
      '**Exercise 3 (Medium):** For each department, show the top 2 highest-paid employees.',
      '',
      '```sql',
      'WITH ranked_employees AS (',
      '  SELECT name,',
      '         department,',
      '         salary,',
      '         ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM ranked_employees',
      'WHERE rn <= 2',
      'ORDER BY department, salary DESC;',
      '```',
      '',
      '**Exercise 4 (Hard):** Find customers who placed orders in every month of 2023.',
      '',
      '```sql',
      'WITH monthly_orders AS (',
      '  SELECT customer_id,',
      '         COUNT(DISTINCT MONTH(order_date)) AS active_months',
      '  FROM orders',
      "  WHERE YEAR(order_date) = 2023",
      '  GROUP BY customer_id',
      ')',
      'SELECT customer_id',
      'FROM monthly_orders',
      'WHERE active_months = 12;',
      '```',
    ].join('\n'),
    zh: [
      '## 什么是子查询？',
      '',
      '子查询（或内层查询）是嵌套在另一条 SQL 语句中的 SELECT 语句。可出现在 SELECT、FROM、WHERE 或 HAVING 子句中。',
      '',
      '## WHERE 中的子查询（最常见）',
      '',
      '```sql',
      '-- 找出薪资高于公司平均水平的员工',
      'SELECT name, salary',
      'FROM employees',
      'WHERE salary > (SELECT AVG(salary) FROM employees);',
      '',
      '-- 内层查询先执行，返回一个值，如 75000',
      '-- 然后外层查询执行：WHERE salary > 75000',
      '```',
      '',
      '**子查询返回多值——使用 IN：**',
      '',
      '```sql',
      '-- 找出在"纽约"部门工作的员工',
      'SELECT name',
      'FROM employees',
      "WHERE dept_id IN (SELECT dept_id FROM departments WHERE location = '纽约');",
      '```',
      '',
      '**注意 NOT IN 的陷阱：**',
      '',
      '```sql',
      '-- 如果子查询结果包含任何 NULL，NOT IN 将返回零行！',
      '-- 更安全的替代方案：NOT EXISTS',
      'SELECT name',
      'FROM employees e',
      'WHERE NOT EXISTS (',
      '  SELECT 1 FROM orders o WHERE o.emp_id = e.emp_id',
      ');',
      '```',
      '',
      '## 相关子查询——逐行执行',
      '',
      '相关子查询引用外层查询的列。对外层查询的**每一行**执行一次——大表上可能很慢。',
      '',
      '```sql',
      '-- 找出每个部门薪资最高的员工',
      'SELECT name, department, salary',
      'FROM employees e',
      'WHERE salary = (',
      '  SELECT MAX(salary)',
      '  FROM employees',
      '  WHERE department = e.department   -- 引用外层查询',
      ');',
      '```',
      '',
      '## FROM 中的子查询（派生表/内联视图）',
      '',
      '```sql',
      '-- 各部门平均薪资的平均值',
      'SELECT AVG(dept_avg) AS 公司平均薪资',
      'FROM (',
      '  SELECT department, AVG(salary) AS dept_avg',
      '  FROM employees',
      '  GROUP BY department',
      ') dept_summary;',
      '```',
      '',
      '## 公用表表达式（CTE）——WITH 子句',
      '',
      'CTE 定义一个命名的临时结果集，可在主查询中引用一次。它比嵌套子查询可读性强得多。',
      '',
      '```sql',
      '-- 语法',
      'WITH cte名称 AS (',
      '  SELECT ...',
      ')',
      'SELECT * FROM cte名称;',
      '',
      '-- 示例：使用 CTE 查找薪资高于平均水平的员工',
      'WITH 公司平均 AS (',
      '  SELECT AVG(salary) AS avg_sal FROM employees',
      ')',
      'SELECT name, salary',
      'FROM employees, 公司平均',
      'WHERE salary > avg_sal;',
      '```',
      '',
      '**多个 CTE（链式）：**',
      '',
      '```sql',
      'WITH',
      '-- 第 1 步：计算每个部门的总工资',
      'dept_payroll AS (',
      '  SELECT dept_id, SUM(salary) AS total',
      '  FROM employees GROUP BY dept_id',
      '),',
      '-- 第 2 步：按工资排名',
      'ranked AS (',
      '  SELECT dept_id, total,',
      '         RANK() OVER (ORDER BY total DESC) AS rnk',
      '  FROM dept_payroll',
      ')',
      '-- 第 3 步：获取前 3 名部门',
      'SELECT d.dept_name, r.total, r.rnk',
      'FROM ranked r JOIN departments d ON r.dept_id = d.dept_id',
      'WHERE r.rnk <= 3;',
      '```',
      '',
      '## 递归 CTE——层次数据',
      '',
      '递归 CTE 查询树/图结构，如组织架构或物料清单。',
      '',
      '```sql',
      '-- 从某员工向上遍历管理层级',
      'WITH RECURSIVE org_chart AS (',
      '  SELECT emp_id, name, manager_id, 0 AS 层级',
      '  FROM employees WHERE emp_id = 42',
      '  UNION ALL',
      '  SELECT e.emp_id, e.name, e.manager_id, oc.层级 + 1',
      '  FROM employees e JOIN org_chart oc ON e.emp_id = oc.manager_id',
      ')',
      'SELECT name, 层级 FROM org_chart ORDER BY 层级;',
      '',
      '-- 注意：Oracle 使用 CONNECT BY 而不是递归 CTE（见 Oracle 章节）',
      '```',
      '',
      '## 练习题 4——子查询与 CTE',
      '',
      '**练习 1（简单）：** 找出薪资高于本部门平均薪资的员工。',
      '',
      '```sql',
      'SELECT name, department, salary',
      'FROM employees e1',
      'WHERE salary > (',
      '  SELECT AVG(salary)',
      '  FROM employees e2',
      '  WHERE e2.department = e1.department',
      ');',
      '```',
      '',
      '**练习 2（中等——LeetCode 176）：** 找出第二高的薪资。不存在时返回 NULL。',
      '',
      '```sql',
      'SELECT MAX(salary) AS SecondHighestSalary',
      'FROM employees',
      'WHERE salary < (SELECT MAX(salary) FROM employees);',
      '```',
      '',
      '**练习 3（中等）：** 每个部门薪资最高的前 2 名员工。',
      '',
      '```sql',
      'WITH ranked_employees AS (',
      '  SELECT name, department, salary,',
      '         ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM ranked_employees',
      'WHERE rn <= 2',
      'ORDER BY department, salary DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 176, title: 'Second Highest Salary', titleZh: '第二高的薪水', difficulty: 'Medium' },
    { id: 177, title: 'Nth Highest Salary', titleZh: '第N高的薪水', difficulty: 'Medium' },
    { id: 185, title: 'Department Top Three Salaries', titleZh: '部门工资前三高的所有员工', difficulty: 'Hard' },
    { id: 262, title: 'Trips and Users', titleZh: '行程和用户', difficulty: 'Hard' },
  ],
}
