import type { TopicContent } from '../../types'

export const sqlWindowFunctions: TopicContent = {
  id: 'sql-window-functions',
  title: { en: 'Window Functions', zh: '窗口函数' },
  description: {
    en: 'Use OVER, PARTITION BY, ROW_NUMBER, RANK, LAG/LEAD, and running totals for advanced analytics',
    zh: '使用 OVER、PARTITION BY、ROW_NUMBER、RANK、LAG/LEAD 和运行总计进行高级分析',
  },
  timeEstimate: '60 min',
  contentType: 'content',
  hasVisualizer: false,
  content: {
    en: [
      '## What Are Window Functions?',
      '',
      'Window functions perform calculations across a set of rows **related to the current row**, without collapsing the rows into a single output (unlike GROUP BY).',
      '',
      '```',
      'GROUP BY:         Window Function:',
      '──────────────    ──────────────────────────────────',
      'dept  | avg_sal   name    dept   salary  dept_avg',
      '──────┼────────   ────────┼────────┼───────┼────────',
      'Eng   | 90000     Alice   Eng     80000   90000',
      'Sales | 70000     Bob     Eng     100000  90000  ← rows preserved',
      '              →   Carol   Sales   65000   70000',
      '                  Dave    Sales   75000   70000',
      '```',
      '',
      '## Syntax — The OVER Clause',
      '',
      '```sql',
      'function_name() OVER (',
      '  [PARTITION BY column1, column2, ...]  -- define the window group',
      '  [ORDER BY column3 ASC/DESC]           -- define the order within the window',
      '  [ROWS/RANGE frame_spec]               -- define the frame (optional)',
      ')',
      '```',
      '',
      '## ROW_NUMBER, RANK, DENSE_RANK',
      '',
      'These three functions assign a number to each row within a partition.',
      '',
      '```sql',
      'SELECT name,',
      '       department,',
      '       salary,',
      '       ROW_NUMBER()  OVER (PARTITION BY department ORDER BY salary DESC) AS row_num,',
      '       RANK()        OVER (PARTITION BY department ORDER BY salary DESC) AS rank_num,',
      '       DENSE_RANK()  OVER (PARTITION BY department ORDER BY salary DESC) AS dense_rank',
      'FROM employees;',
      '',
      '-- Suppose Engineering salaries are: 100000, 100000, 80000',
      '-- name     | row_num | rank | dense_rank',
      '-- Alice    |   1     |   1  |     1      (salary: 100000)',
      '-- Bob      |   2     |   1  |     1      (salary: 100000, tied)',
      '-- Carol    |   3     |   3  |     2      (salary: 80000)',
      '--                       ↑ gap              ↑ no gap',
      '```',
      '',
      '**Difference:**',
      '- `ROW_NUMBER`: always unique, no ties (1, 2, 3, 4)',
      '- `RANK`: tied rows get the same rank, skips next ranks (1, 1, 3, 4)',
      '- `DENSE_RANK`: tied rows get the same rank, no skips (1, 1, 2, 3)',
      '',
      '**Classic use: get the top N per group**',
      '',
      '```sql',
      'WITH ranked AS (',
      '  SELECT name, department, salary,',
      '         DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dr',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM ranked',
      "WHERE dr <= 3;   -- top 3 salaries per department (ties included)",
      '```',
      '',
      '## LAG and LEAD — Access Adjacent Rows',
      '',
      'LAG looks at a previous row; LEAD looks at a following row, within the same partition and order.',
      '',
      '```sql',
      '-- Compare each employee\'s salary with the previous row\'s salary in their department',
      'SELECT name,',
      '       department,',
      '       salary,',
      '       LAG(salary, 1, 0) OVER (PARTITION BY department ORDER BY hire_date) AS prev_salary,',
      '       salary - LAG(salary, 1, 0) OVER (PARTITION BY department ORDER BY hire_date) AS salary_diff',
      'FROM employees;',
      '',
      '-- LAG(col, offset, default)',
      '-- offset: how many rows back (default 1)',
      '-- default: value to return if no prior row exists (default NULL)',
      '```',
      '',
      '**Classic use: find days with a temperature rise (LeetCode 197 modern approach)**',
      '',
      '```sql',
      'WITH daily AS (',
      '  SELECT recordDate,',
      '         temperature,',
      '         LAG(temperature) OVER (ORDER BY recordDate) AS prev_temp,',
      '         LAG(recordDate)  OVER (ORDER BY recordDate) AS prev_date',
      '  FROM Weather',
      ')',
      'SELECT recordDate AS id',
      'FROM daily',
      'WHERE temperature > prev_temp',
      '  AND recordDate = prev_date + INTERVAL 1 DAY;',
      '```',
      '',
      '## SUM / AVG / COUNT as Window Functions — Running Totals',
      '',
      '```sql',
      '-- Running total of salary ordered by hire date',
      'SELECT name,',
      '       hire_date,',
      '       salary,',
      '       SUM(salary) OVER (ORDER BY hire_date) AS running_total',
      'FROM employees;',
      '',
      '-- Running total WITHIN each department',
      'SELECT name,',
      '       department,',
      '       salary,',
      '       SUM(salary) OVER (PARTITION BY department ORDER BY hire_date) AS dept_running_total',
      'FROM employees;',
      '',
      '-- Moving average (last 3 rows including current)',
      'SELECT name,',
      '       salary,',
      '       AVG(salary) OVER (',
      '         ORDER BY hire_date',
      '         ROWS BETWEEN 2 PRECEDING AND CURRENT ROW',
      '       ) AS moving_avg_3',
      'FROM employees;',
      '```',
      '',
      '## FIRST_VALUE and LAST_VALUE',
      '',
      '```sql',
      '-- Show each employee\'s salary and the highest salary in their department',
      'SELECT name,',
      '       department,',
      '       salary,',
      '       FIRST_VALUE(salary) OVER (',
      '         PARTITION BY department',
      '         ORDER BY salary DESC',
      '       ) AS dept_max_salary',
      'FROM employees;',
      '',
      '-- LAST_VALUE note: requires explicit ROWS BETWEEN frame to work correctly',
      'SELECT name,',
      '       salary,',
      '       LAST_VALUE(salary) OVER (',
      '         PARTITION BY department',
      '         ORDER BY salary DESC',
      '         ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING',
      '       ) AS dept_min_salary',
      'FROM employees;',
      '```',
      '',
      '## NTILE — Divide into Buckets',
      '',
      '```sql',
      '-- Divide employees into 4 salary quartiles',
      'SELECT name,',
      '       salary,',
      '       NTILE(4) OVER (ORDER BY salary) AS quartile',
      'FROM employees;',
      '-- quartile 1 = bottom 25%, quartile 4 = top 25%',
      '```',
      '',
      '## PERCENT_RANK and CUME_DIST',
      '',
      '```sql',
      '-- What percentage of employees earn less than each employee?',
      'SELECT name,',
      '       salary,',
      '       ROUND(PERCENT_RANK() OVER (ORDER BY salary) * 100, 1) AS percentile',
      'FROM employees;',
      '',
      '-- CUME_DIST: fraction of rows with salary <= current row salary',
      'SELECT name,',
      '       salary,',
      '       ROUND(CUME_DIST() OVER (ORDER BY salary) * 100, 1) AS cumulative_pct',
      'FROM employees;',
      '```',
      '',
      '## Performance — Window Functions vs Subqueries',
      '',
      '```sql',
      '-- OLD approach (correlated subquery — O(n²))',
      'SELECT name, salary,',
      '       (SELECT COUNT(*) FROM employees e2 WHERE e2.salary < e1.salary) + 1 AS rank_num',
      'FROM employees e1;',
      '',
      '-- NEW approach (window function — O(n log n))',
      'SELECT name, salary,',
      '       RANK() OVER (ORDER BY salary) AS rank_num',
      'FROM employees;',
      '',
      '-- Window functions are almost always faster and more readable',
      '```',
      '',
      '## Exercise Set 5 — Window Functions',
      '',
      '**Exercise 1 (Easy):** Assign a sequential number to employees within each department, ordered by salary descending.',
      '',
      '```sql',
      'SELECT name, department, salary,',
      '       ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank',
      'FROM employees;',
      '```',
      '',
      '**Exercise 2 (Medium — LeetCode 178):** Rank all employees by salary. Ties share the same rank, with no gaps.',
      '',
      '```sql',
      'SELECT name, salary,',
      '       DENSE_RANK() OVER (ORDER BY salary DESC) AS rank_num',
      'FROM employees;',
      '```',
      '',
      '**Exercise 3 (Medium):** For each employee, show their salary, the previous employee\'s salary (ordered by hire date), and the difference.',
      '',
      '```sql',
      'SELECT name,',
      '       hire_date,',
      '       salary,',
      '       LAG(salary) OVER (ORDER BY hire_date)                AS prev_salary,',
      '       salary - LAG(salary) OVER (ORDER BY hire_date)       AS change',
      'FROM employees;',
      '```',
      '',
      '**Exercise 4 (Medium):** Show a running total of salaries ordered by hire date, and also the cumulative average.',
      '',
      '```sql',
      'SELECT name,',
      '       hire_date,',
      '       salary,',
      '       SUM(salary) OVER (ORDER BY hire_date ROWS UNBOUNDED PRECEDING) AS running_total,',
      '       AVG(salary) OVER (ORDER BY hire_date ROWS UNBOUNDED PRECEDING) AS running_avg',
      'FROM employees;',
      '```',
      '',
      '**Exercise 5 (Hard — LeetCode 185 style):** For each department, return the top 3 salary earners. Include ties (if two employees share 3rd place, include both).',
      '',
      '```sql',
      'WITH dept_ranked AS (',
      '  SELECT name,',
      '         department,',
      '         salary,',
      '         DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dr',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM dept_ranked',
      'WHERE dr <= 3',
      'ORDER BY department, salary DESC;',
      '```',
    ].join('\n'),
    zh: [
      '## 什么是窗口函数？',
      '',
      '窗口函数在与当前行**相关的一组行**上执行计算，而不像 GROUP BY 那样将行折叠成单个输出。',
      '',
      '```',
      'GROUP BY:         窗口函数：',
      '──────────────    ──────────────────────────────────',
      '部门  | 平均薪资   姓名   部门   薪资   部门平均',
      '──────┼────────   ────────┼────────┼───────┼────────',
      '工程  | 90000     Alice   工程    80000   90000',
      '销售  | 70000     Bob     工程   100000   90000  ← 行被保留',
      '              →   Carol   销售    65000   70000',
      '                  Dave    销售    75000   70000',
      '```',
      '',
      '## 语法——OVER 子句',
      '',
      '```sql',
      '函数名() OVER (',
      '  [PARTITION BY 列1, 列2, ...]  -- 定义窗口分组',
      '  [ORDER BY 列3 ASC/DESC]       -- 定义窗口内排序',
      '  [ROWS/RANGE 帧规范]           -- 定义帧（可选）',
      ')',
      '```',
      '',
      '## ROW_NUMBER、RANK、DENSE_RANK',
      '',
      '```sql',
      'SELECT name, department, salary,',
      '       ROW_NUMBER()  OVER (PARTITION BY department ORDER BY salary DESC) AS 行号,',
      '       RANK()        OVER (PARTITION BY department ORDER BY salary DESC) AS 排名,',
      '       DENSE_RANK()  OVER (PARTITION BY department ORDER BY salary DESC) AS 密集排名',
      'FROM employees;',
      '',
      '-- 工程部薪资：100000, 100000, 80000',
      '-- 姓名   | 行号 | 排名 | 密集排名',
      '-- Alice  |  1  |  1  |    1    （薪资：100000）',
      '-- Bob    |  2  |  1  |    1    （薪资：100000，并列）',
      '-- Carol  |  3  |  3  |    2    （薪资：80000）',
      '--              ↑ 有间隔     ↑ 无间隔',
      '```',
      '',
      '**区别：**',
      '- `ROW_NUMBER`：始终唯一，无并列（1, 2, 3, 4）',
      '- `RANK`：并列行相同排名，跳过下一名（1, 1, 3, 4）',
      '- `DENSE_RANK`：并列行相同排名，不跳过（1, 1, 2, 3）',
      '',
      '**经典用法：获取每组前 N 名**',
      '',
      '```sql',
      'WITH ranked AS (',
      '  SELECT name, department, salary,',
      '         DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dr',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM ranked WHERE dr <= 3;',
      '```',
      '',
      '## LAG 和 LEAD——访问相邻行',
      '',
      '```sql',
      '-- 每位员工的薪资与其所在部门上一行薪资的比较',
      'SELECT name, department, salary,',
      '       LAG(salary, 1, 0) OVER (PARTITION BY department ORDER BY hire_date) AS 上一薪资,',
      '       salary - LAG(salary, 1, 0) OVER (PARTITION BY department ORDER BY hire_date) AS 薪资差',
      'FROM employees;',
      '```',
      '',
      '## SUM/AVG/COUNT 作为窗口函数——累计计算',
      '',
      '```sql',
      '-- 按入职日期的累计工资总和',
      'SELECT name, hire_date, salary,',
      '       SUM(salary) OVER (ORDER BY hire_date) AS 累计总额',
      'FROM employees;',
      '',
      '-- 3 行移动平均',
      'SELECT name, salary,',
      '       AVG(salary) OVER (',
      '         ORDER BY hire_date',
      '         ROWS BETWEEN 2 PRECEDING AND CURRENT ROW',
      '       ) AS 三期移动均值',
      'FROM employees;',
      '```',
      '',
      '## 练习题 5——窗口函数',
      '',
      '**练习 1（简单）：** 在每个部门内，按薪资降序给员工分配序号。',
      '',
      '```sql',
      'SELECT name, department, salary,',
      '       ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS 部门排名',
      'FROM employees;',
      '```',
      '',
      '**练习 2（中等——LeetCode 178）：** 对所有员工按薪资排名。并列同名次，无间隔。',
      '',
      '```sql',
      'SELECT name, salary,',
      '       DENSE_RANK() OVER (ORDER BY salary DESC) AS 排名',
      'FROM employees;',
      '```',
      '',
      '**练习 3（困难）：** 每个部门薪资前 3 名（含并列）。',
      '',
      '```sql',
      'WITH dept_ranked AS (',
      '  SELECT name, department, salary,',
      '         DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dr',
      '  FROM employees',
      ')',
      'SELECT name, department, salary',
      'FROM dept_ranked WHERE dr <= 3',
      'ORDER BY department, salary DESC;',
      '```',
    ].join('\n'),
  },
  leetcode: [
    { id: 178, title: 'Rank Scores', titleZh: '分数排名', difficulty: 'Medium' },
    { id: 180, title: 'Consecutive Numbers', titleZh: '连续出现的数字', difficulty: 'Medium' },
    { id: 185, title: 'Department Top Three Salaries', titleZh: '部门工资前三高的所有员工', difficulty: 'Hard' },
    { id: 601, title: 'Human Traffic of Stadium', titleZh: '体育馆的人流量', difficulty: 'Hard' },
  ],
}
