import type { TopicContent } from '../../types'

export const binarySearch: TopicContent = {
  id: 'arrays-binary-search',
  title: { en: 'Binary Search Pattern', zh: '二分查找模式' },
  description: { en: 'Master 3 binary search templates for exact match, left bound, and right bound', zh: '掌握3个二分查找模板：精确匹配、左边界、右边界' },
  timeEstimate: '45 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'binarySearch',
  content: {
    en: [
      "## The Binary Search Core Concept",
      "",
      "Binary search is built on the principle of halving the search space. If you have n elements, each comparison eliminates half the remaining space. After k comparisons, you've checked at most 2^k elements. This is why binary search is O(log n) - incredibly efficient.",
      "",
      "However, binary search requires sorted data. If the data isn't sorted, sorting first (O(n log n)) might still be worth it if you do many searches.",
      "",
      "The challenge: there are three slightly different templates depending on what you're searching for.",
      "",
      "## Template 1: Exact Match",
      "",
      "Find the exact position of a target element. If not found, return -1.",
      "",
      "```javascript",
      "function binarySearchExact(arr, target) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left <= right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] === target) {",
      "      return mid",
      "    } else if (arr[mid] < target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid - 1",
      "    }",
      "  }",
      "  return -1",
      "}",
      "```",
      "",
      "**Key difference**: `while (left <= right)` - we continue until the pointers cross.",
      "",
      "## Template 2: Left Bound",
      "",
      "Find the leftmost position where target appears. This handles duplicates - if there are multiple copies of the target, find the first one.",
      "",
      "```javascript",
      "function binarySearchLeftBound(arr, target) {",
      "  let left = 0, right = arr.length",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] < target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid",
      "    }",
      "  }",
      "  if (left < arr.length && arr[left] === target) return left",
      "  return -1",
      "}",
      "```",
      "",
      "**Key differences**:",
      "- `right = arr.length` (not `arr.length - 1`)",
      "- `while (left < right)` (not `<=`)",
      "- When `arr[mid] < target`, move left; when `arr[mid] >= target`, move right",
      "- We bias towards the left side",
      "",
      "**Why this works**: When the loop ends, `left == right` pointing at the first position where `arr[pos] >= target`.",
      "",
      "## Template 3: Right Bound",
      "",
      "Find the rightmost position where target appears.",
      "",
      "```javascript",
      "function binarySearchRightBound(arr, target) {",
      "  let left = 0, right = arr.length",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] <= target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid",
      "    }",
      "  }",
      "  if (left > 0 && arr[left - 1] === target) return left - 1",
      "  return -1",
      "}",
      "```",
      "",
      "**Key differences from left bound**:",
      "- When `arr[mid] <= target`, move left (we include equal)",
      "- We check `arr[left - 1]` at the end (the position we skipped over)",
      "- We bias towards the right side",
      "",
      "## Example: Find First and Last Position",
      "",
      "```javascript",
      "function searchRange(arr, target) {",
      "  const left = binarySearchLeftBound(arr, target)",
      "  const right = binarySearchRightBound(arr, target)",
      "  if (left === -1) return [-1, -1]",
      "  return [left, right]",
      "}",
      "```",
      "",
      "For array `[5, 7, 7, 8, 8, 10]` and target `8`:",
      "- Left bound finds index 3 (first 8)",
      "- Right bound finds index 4 (last 8)",
      "- Return `[3, 4]`",
      "",
      "## Search Space Reduction Beyond Sorted Arrays",
      "",
      "Binary search isn't limited to finding elements in arrays. The core concept applies anywhere you have a monotonic property.",
      "",
      "**Example: Find Peak Element**",
      "",
      "A peak is an element greater than its neighbors. In an unsorted array, use binary search on the property: if `arr[mid]` is in an upslope, search right; if downslope, search left.",
      "",
      "```javascript",
      "function findPeak(arr) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] < arr[mid + 1]) {",
      "      left = mid + 1  // Go right",
      "    } else {",
      "      right = mid     // Go left (or mid is peak)",
      "    }",
      "  }",
      "  return left",
      "}",
      "```",
      "",
      "The monotonic property here is: \"if going up, peak is to the right; if going down, peak is here or to the left.\"",
      "",
      "## Common Mistakes",
      "",
      "1. **Integer overflow**: Use `mid = left + Math.floor((right - left) / 2)` instead of `(left + right) / 2`",
      "2. **Off-by-one errors**: Test boundary cases (first element, last element, not found)",
      "3. **Mixing templates**: Each template has specific conditions. Don't mix them.",
      "4. **Assuming data is sorted**: Binary search silently fails on unsorted data without error.",
      "",
      "## Time Complexity",
      "",
      "All three templates are O(log n) for search and O(n log n) if you sort first."
    ].join('\n'),
    zh: [
      "## 二分查找核心概念",
      "",
      "二分查找建立在减半搜索空间的原则上。如果有n个元素，每次比较消除一半的剩余空间。经过k次比较后，你最多检查2^k个元素。这就是为什么二分查找是O(log n) - 极其高效。",
      "",
      "然而，二分查找需要排序数据。如果数据未排序，先排序（O(n log n)）如果进行许多搜索可能仍值得。",
      "",
      "挑战：根据你搜索的内容，有三个略有不同的模板。",
      "",
      "## 模板1：精确匹配",
      "",
      "找到目标元素的确切位置。如果未找到，返回-1。",
      "",
      "```javascript",
      "function binarySearchExact(arr, target) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left <= right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] === target) {",
      "      return mid",
      "    } else if (arr[mid] < target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid - 1",
      "    }",
      "  }",
      "  return -1",
      "}",
      "```",
      "",
      "**关键区别**：`while (left <= right)` - 我们继续直到指针交叉。",
      "",
      "## 模板2：左边界",
      "",
      "找到目标出现的最左位置。这处理重复 - 如果有多个目标副本，找第一个。",
      "",
      "```javascript",
      "function binarySearchLeftBound(arr, target) {",
      "  let left = 0, right = arr.length",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] < target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid",
      "    }",
      "  }",
      "  if (left < arr.length && arr[left] === target) return left",
      "  return -1",
      "}",
      "```",
      "",
      "**关键区别**：",
      "- `right = arr.length`（不是`arr.length - 1`）",
      "- `while (left < right)`（不是`<=`）",
      "- 当`arr[mid] < target`时，左移；当`arr[mid] >= target`时，右移",
      "- 我们偏向左侧",
      "",
      "**为什么有效**：当循环结束时，`left == right`指向第一个`arr[pos] >= target`的位置。",
      "",
      "## 模板3：右边界",
      "",
      "找到目标出现的最右位置。",
      "",
      "```javascript",
      "function binarySearchRightBound(arr, target) {",
      "  let left = 0, right = arr.length",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] <= target) {",
      "      left = mid + 1",
      "    } else {",
      "      right = mid",
      "    }",
      "  }",
      "  if (left > 0 && arr[left - 1] === target) return left - 1",
      "  return -1",
      "}",
      "```",
      "",
      "**与左边界的关键区别**：",
      "- 当`arr[mid] <= target`时，左移（我们包括相等）",
      "- 我们检查`arr[left - 1]`在末尾（我们跳过的位置）",
      "- 我们偏向右侧",
      "",
      "## 示例：找第一和最后位置",
      "",
      "```javascript",
      "function searchRange(arr, target) {",
      "  const left = binarySearchLeftBound(arr, target)",
      "  const right = binarySearchRightBound(arr, target)",
      "  if (left === -1) return [-1, -1]",
      "  return [left, right]",
      "}",
      "```",
      "",
      "对于数组`[5, 7, 7, 8, 8, 10]`和目标`8`：",
      "- 左边界找到索引3（第一个8）",
      "- 右边界找到索引4（最后一个8）",
      "- 返回`[3, 4]`",
      "",
      "## 超越排序数组的搜索空间缩小",
      "",
      "二分查找不限于在数组中查找元素。核心概念适用于任何具有单调性质的地方。",
      "",
      "**示例：找峰值元素**",
      "",
      "峰值是大于其邻居的元素。在未排序数组中，在属性上使用二分查找：如果`arr[mid]`在上升斜坡，搜索右侧；如果下降，搜索左侧。",
      "",
      "```javascript",
      "function findPeak(arr) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left < right) {",
      "    const mid = Math.floor((left + right) / 2)",
      "    if (arr[mid] < arr[mid + 1]) {",
      "      left = mid + 1  // 向右走",
      "    } else {",
      "      right = mid     // 向左走（或mid是峰值）",
      "    }",
      "  }",
      "  return left",
      "}",
      "```",
      "",
      "这里的单调属性是：「如果上升，峰值在右侧；如果下降，峰值在这里或左侧。」",
      "",
      "## 常见错误",
      "",
      "1. **整数溢出**：使用`mid = left + Math.floor((right - left) / 2)`而不是`(left + right) / 2`",
      "2. **一一到位错误**：测试边界情况（第一个元素、最后一个元素、未找到）",
      "3. **混合模板**：每个模板有特定条件。不要混合它们。",
      "4. **假设数据已排序**：二分查找在未排序数据上无声失败而无错误。",
      "",
      "## 时间复杂度",
      "",
      "所有三个模板都是O(log n)用于搜索，如果先排序O(n log n)。"
    ].join('\n'),
  },
  leetcode: [
    { id: 704, title: 'Binary Search', titleZh: '二分查找', difficulty: 'Easy' },
    { id: 34, title: 'Find First and Last Position of Element in Sorted Array', titleZh: '在排序数组中查找元素的第一个和最后一个位置', difficulty: 'Medium' },
    { id: 33, title: 'Search in Rotated Sorted Array', titleZh: '搜索旋转排序数组', difficulty: 'Medium' },
    { id: 162, title: 'Find Peak Element', titleZh: '寻找峰值', difficulty: 'Medium' },
  ],
}
