import type { TopicContent } from '../../types'

export const prefixSum: TopicContent = {
  id: 'arrays-prefix-sum',
  title: { en: 'Prefix Sum & Difference Arrays', zh: '前缀和与差分数组' },
  description: { en: 'Convert range queries to O(1) with prefix sums, range updates to O(1) with difference arrays', zh: '用前缀和将范围查询转化为O(1)，用差分数组将范围更新转化为O(1)' },
  timeEstimate: '35 min',
  contentType: 'content+practice',
  hasVisualizer: false,
  content: {
    en: [
      "## The Prefix Sum Idea",
      "",
      "A prefix sum array stores the cumulative sum up to each position. If you want to know the sum of elements from index i to j, you don't sum them repeatedly - you compute it from the prefix sum array in O(1).",
      "",
      "Without prefix sum: sum from index 2 to 5 requires checking elements [2], [3], [4], [5] = O(n) per query.",
      "",
      "With prefix sum: sum from index 2 to 5 = prefix[6] - prefix[2] = O(1) per query.",
      "",
      "## Building a Prefix Sum Array",
      "",
      "```javascript",
      "function buildPrefixSum(arr) {",
      "  const prefix = [0]  // prefix[0] = 0 (empty sum)",
      "  for (let i = 0; i < arr.length; i++) {",
      "    prefix[i + 1] = prefix[i] + arr[i]",
      "  }",
      "  return prefix",
      "  // prefix[i] = sum of arr[0] to arr[i-1]",
      "}",
      "```",
      "",
      "**Example:**",
      "```",
      "arr = [1, 2, 3, 4, 5]",
      "prefix = [0, 1, 3, 6, 10, 15]",
      "  index:   0  1  2  3   4   5",
      "```",
      "",
      "- `prefix[0] = 0` (sum of no elements)",
      "- `prefix[1] = 1` (sum of arr[0])",
      "- `prefix[2] = 3` (sum of arr[0] + arr[1])",
      "- `prefix[5] = 15` (sum of all elements)",
      "",
      "## Querying Range Sum",
      "",
      "To find sum of elements from index i to j (inclusive):",
      "",
      "```javascript",
      "function rangeSum(prefix, i, j) {",
      "  return prefix[j + 1] - prefix[i]",
      "}",
      "```",
      "",
      "For our example, sum from index 1 to 3:",
      "- `rangeSum(prefix, 1, 3) = prefix[4] - prefix[1] = 10 - 1 = 9`",
      "- This is arr[1] + arr[2] + arr[3] = 2 + 3 + 4 = 9 ✓",
      "",
      "## Real Problem: Range Sum Query 1D",
      "",
      "Given an array, answer multiple range sum queries. Naïve approach is O(n) per query. Prefix sum is O(1) per query after O(n) preprocessing.",
      "",
      "```javascript",
      "class NumArray {",
      "  constructor(nums) {",
      "    this.prefix = [0]",
      "    for (const num of nums) {",
      "      this.prefix.push(this.prefix[this.prefix.length - 1] + num)",
      "    }",
      "  }",
      "  ",
      "  sumRange(left, right) {",
      "    return this.prefix[right + 1] - this.prefix[left]",
      "  }",
      "}",
      "```",
      "",
      "## Difference Arrays for Range Updates",
      "",
      "Prefix sum is great for queries. For updates (especially range updates), we use difference arrays. Instead of modifying all elements in a range (O(n)), we only update two boundary points (O(1)).",
      "",
      "**Difference array approach:**",
      "- To add value `v` to range [i, j], do: `diff[i] += v` and `diff[j+1] -= v`",
      "- Then compute prefix sum of the difference array to get final array",
      "",
      "## Building with Difference Array",
      "",
      "```javascript",
      "function updateRange(arr, i, j, val) {",
      "  const diff = new Array(arr.length + 1).fill(0)",
      "  ",
      "  // For each update, mark boundaries in difference array",
      "  diff[i] += val",
      "  diff[j + 1] -= val",
      "  ",
      "  // Reconstruct final array from difference array",
      "  let current = 0",
      "  for (let k = 0; k < arr.length; k++) {",
      "    current += diff[k]",
      "    arr[k] += current",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "**Example: Add 5 to range [1, 3]**",
      "```",
      "Before: [1, 2, 3, 4, 5]",
      "Difference array: [0, 5, 0, 0, -5, 0]",
      "Reconstruct: current = 0",
      "  k=0: current += diff[0] = 0, arr[0] = 1 + 0 = 1",
      "  k=1: current += diff[1] = 5, arr[1] = 2 + 5 = 7",
      "  k=2: current += diff[2] = 5, arr[2] = 3 + 5 = 8",
      "  k=3: current += diff[3] = 5, arr[3] = 4 + 5 = 9",
      "  k=4: current += diff[4] = 0, arr[4] = 5 + 0 = 5",
      "After: [1, 7, 8, 9, 5]",
      "```",
      "",
      "## Optimal Pattern for Multiple Range Updates",
      "",
      "If you need multiple range updates and then one query at the end:",
      "",
      "```javascript",
      "class RangeUpdateProcessor {",
      "  constructor(n) {",
      "    this.diff = new Array(n + 1).fill(0)",
      "  }",
      "  ",
      "  addRange(i, j, val) {",
      "    // O(1) per update",
      "    this.diff[i] += val",
      "    this.diff[j + 1] -= val",
      "  }",
      "  ",
      "  getArray() {",
      "    // O(n) to reconstruct final array",
      "    const result = []",
      "    let current = 0",
      "    for (let i = 0; i < this.diff.length - 1; i++) {",
      "      current += this.diff[i]",
      "      result.push(current)",
      "    }",
      "    return result",
      "  }",
      "}",
      "```",
      "",
      "## Time Complexity Comparison",
      "",
      "| Problem | Naïve | Prefix Sum | Difference |",
      "|---------|-------|-----------|-----------|",
      "| Single range query | O(n) | O(1) after O(n) build | N/A |",
      "| m range queries | O(m*n) | O(m) after O(n) build | N/A |",
      "| Single range update | O(n) | N/A | O(1) |",
      "| m range updates + final query | O(m*n) | N/A | O(m + n) |",
      "",
      "## Key Insight",
      "",
      "Prefix sum trades space for time: use O(n) extra space to answer queries in O(1). Difference array inverts this for updates: answer multiple O(1) updates, then spend O(n) to reconstruct. Choose based on what you need to optimize."
    ].join('\n'),
    zh: [
      "## 前缀和的想法",
      "",
      "前缀和数组存储每个位置的累积和。如果你想知道从索引i到j的元素和，你不必重复求和 - 你从前缀和数组用O(1)计算它。",
      "",
      "没有前缀和：从索引2到5的和需要检查元素[2], [3], [4], [5] = O(n)每次查询。",
      "",
      "有前缀和：从索引2到5的和 = prefix[6] - prefix[2] = O(1)每次查询。",
      "",
      "## 构建前缀和数组",
      "",
      "```javascript",
      "function buildPrefixSum(arr) {",
      "  const prefix = [0]  // prefix[0] = 0（空和）",
      "  for (let i = 0; i < arr.length; i++) {",
      "    prefix[i + 1] = prefix[i] + arr[i]",
      "  }",
      "  return prefix",
      "  // prefix[i] = arr[0]到arr[i-1]的和",
      "}",
      "```",
      "",
      "**示例：**",
      "```",
      "arr = [1, 2, 3, 4, 5]",
      "prefix = [0, 1, 3, 6, 10, 15]",
      "  索引：   0  1  2  3   4   5",
      "```",
      "",
      "- `prefix[0] = 0`（没有元素的和）",
      "- `prefix[1] = 1`（arr[0]的和）",
      "- `prefix[2] = 3`（arr[0] + arr[1]的和）",
      "- `prefix[5] = 15`（所有元素的和）",
      "",
      "## 查询范围和",
      "",
      "要找从索引i到j（包括）的元素和：",
      "",
      "```javascript",
      "function rangeSum(prefix, i, j) {",
      "  return prefix[j + 1] - prefix[i]",
      "}",
      "```",
      "",
      "对于我们的例子，从索引1到3的和：",
      "- `rangeSum(prefix, 1, 3) = prefix[4] - prefix[1] = 10 - 1 = 9`",
      "- 这是arr[1] + arr[2] + arr[3] = 2 + 3 + 4 = 9 ✓",
      "",
      "## 真实问题：区间和查询1D",
      "",
      "给定一个数组，回答多个范围和查询。幼稚的方法是O(n)每次查询。前缀和在O(n)预处理后O(1)每次查询。",
      "",
      "```javascript",
      "class NumArray {",
      "  constructor(nums) {",
      "    this.prefix = [0]",
      "    for (const num of nums) {",
      "      this.prefix.push(this.prefix[this.prefix.length - 1] + num)",
      "    }",
      "  }",
      "  ",
      "  sumRange(left, right) {",
      "    return this.prefix[right + 1] - this.prefix[left]",
      "  }",
      "}",
      "```",
      "",
      "## 差分数组用于范围更新",
      "",
      "前缀和对查询很好。对于更新（特别是范围更新），我们使用差分数组。与修改范围中的所有元素（O(n)）不同，我们只更新两个边界点（O(1)）。",
      "",
      "**差分数组方法：**",
      "- 要添加值`v`到范围[i, j]，做：`diff[i] += v`和`diff[j+1] -= v`",
      "- 然后计算差分数组的前缀和以获得最终数组",
      "",
      "## 用差分数组构建",
      "",
      "```javascript",
      "function updateRange(arr, i, j, val) {",
      "  const diff = new Array(arr.length + 1).fill(0)",
      "  ",
      "  // 对于每个更新，在差分数组中标记边界",
      "  diff[i] += val",
      "  diff[j + 1] -= val",
      "  ",
      "  // 从差分数组重建最终数组",
      "  let current = 0",
      "  for (let k = 0; k < arr.length; k++) {",
      "    current += diff[k]",
      "    arr[k] += current",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "**示例：添加5到范围[1, 3]**",
      "```",
      "之前：[1, 2, 3, 4, 5]",
      "差分数组：[0, 5, 0, 0, -5, 0]",
      "重建：current = 0",
      "  k=0: current += diff[0] = 0, arr[0] = 1 + 0 = 1",
      "  k=1: current += diff[1] = 5, arr[1] = 2 + 5 = 7",
      "  k=2: current += diff[2] = 5, arr[2] = 3 + 5 = 8",
      "  k=3: current += diff[3] = 5, arr[3] = 4 + 5 = 9",
      "  k=4: current += diff[4] = 0, arr[4] = 5 + 0 = 5",
      "之后：[1, 7, 8, 9, 5]",
      "```",
      "",
      "## 多个范围更新的最优模式",
      "",
      "如果你需要多个范围更新然后最后一个查询：",
      "",
      "```javascript",
      "class RangeUpdateProcessor {",
      "  constructor(n) {",
      "    this.diff = new Array(n + 1).fill(0)",
      "  }",
      "  ",
      "  addRange(i, j, val) {",
      "    // O(1)每个更新",
      "    this.diff[i] += val",
      "    this.diff[j + 1] -= val",
      "  }",
      "  ",
      "  getArray() {",
      "    // O(n)重建最终数组",
      "    const result = []",
      "    let current = 0",
      "    for (let i = 0; i < this.diff.length - 1; i++) {",
      "      current += this.diff[i]",
      "      result.push(current)",
      "    }",
      "    return result",
      "  }",
      "}",
      "```",
      "",
      "## 时间复杂度比较",
      "",
      "| 问题 | 幼稚 | 前缀和 | 差分 |",
      "|------|------|---------|------|",
      "| 单个范围查询 | O(n) | O(1)构建后O(n) | N/A |",
      "| m个范围查询 | O(m*n) | 构建后O(m) | N/A |",
      "| 单个范围更新 | O(n) | N/A | O(1) |",
      "| m个范围更新+最终查询 | O(m*n) | N/A | O(m + n) |",
      "",
      "## 关键洞察",
      "",
      "前缀和用空间换时间：用O(n)额外空间以O(1)回答查询。差分数组反转这一点用于更新：O(1)回答多个更新，然后花费O(n)重建。根据需要优化的内容选择。"
    ].join('\n'),
  },
  leetcode: [
    { id: 303, title: 'Range Sum Query - Immutable', titleZh: '区间和检索 - 数组不可变', difficulty: 'Easy' },
    { id: 560, title: 'Subarray Sum Equals K', titleZh: '和为K的子数组', difficulty: 'Medium' },
    { id: 304, title: 'Range Sum Query 2D - Immutable', titleZh: '二维区间和检索 - 数组不可变', difficulty: 'Medium' },
  ],
}
