import type { TopicContent } from '../../types'

export const slidingWindow: TopicContent = {
  id: 'arrays-sliding-window',
  title: { en: 'Sliding Window Pattern', zh: '滑动窗口模式' },
  description: { en: 'Optimize substring and subarray problems from brute force O(n²) to O(n)', zh: '将子字符串和子数组问题从O(n²)优化到O(n)' },
  timeEstimate: '45 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'slidingWindow',
  content: {
    en: [
      "## The Sliding Window Core Idea",
      "",
      "A sliding window is a rectangular frame that moves across data, usually left to right. Instead of checking all possible subarrays (O(n²)), you maintain a window and slide it intelligently. As the window moves, you update the information inside it incrementally.",
      "",
      "The magic: reuse computation from the previous window instead of recalculating from scratch. When the right boundary adds a new element, add its contribution. When the left boundary removes an element, subtract its contribution. This turns O(n²) into O(n).",
      "",
      "## Fixed Window Size Template",
      "",
      "When the window size is constant, the pattern is simple: move right boundary, when window size exceeds k, move left boundary.",
      "",
      "```javascript",
      "function maxAverageSubarray(nums, k) {",
      "  let windowSum = 0",
      "  // Build initial window [0, k-1]",
      "  for (let i = 0; i < k; i++) {",
      "    windowSum += nums[i]",
      "  }",
      "  let maxSum = windowSum",
      "  // Slide window: move right, and remove element on left",
      "  for (let right = k; right < nums.length; right++) {",
      "    windowSum += nums[right]         // Add new element",
      "    windowSum -= nums[right - k]     // Remove old element",
      "    maxSum = Math.max(maxSum, windowSum)",
      "  }",
      "  return maxSum / k",
      "}",
      "```",
      "",
      "**Time Complexity**: O(n) - each element enters the window once and leaves once.",
      "",
      "## Variable Window Size Template",
      "",
      "When the window size changes based on a condition, use two pointers: left and right. Expand the window by moving right. When the condition fails, shrink by moving left.",
      "",
      "```javascript",
      "function slidingWindowVariable(s, t) {",
      "  let left = 0",
      "  let windowCount = {}",
      "  let required = 0  // how many distinct characters we need",
      "  let formed = 0    // how many distinct characters have freq >= required",
      "  let result = \"\"",
      "  ",
      "  for (let right = 0; right < s.length; right++) {",
      "    // Add character from right",
      "    const char = s[right]",
      "    windowCount[char] = (windowCount[char] || 0) + 1",
      "    if (windowCount[char] === 1) formed++",
      "    ",
      "    // Try to shrink window from left",
      "    while (left <= right && /* condition met */) {",
      "      // Update result if this window is better",
      "      if (right - left + 1 < result.length) {",
      "        result = s.substring(left, right + 1)",
      "      }",
      "      // Remove character from left",
      "      const leftChar = s[left]",
      "      windowCount[leftChar]--",
      "      if (windowCount[leftChar] === 0) formed--",
      "      left++",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## Expand vs Shrink Decision",
      "",
      "**When to expand (move right)?**",
      "- When you haven't found the target condition yet",
      "- When the window is \"unsatisfied\"",
      "",
      "**When to shrink (move left)?**",
      "- When the condition is satisfied and you want to minimize the window",
      "- When you have a duplicate or excess element",
      "",
      "**Example: Longest Substring Without Repeating Characters**",
      "",
      "```javascript",
      "function lengthOfLongestSubstring(s) {",
      "  let left = 0",
      "  let charIndex = {}  // last seen index of each character",
      "  let maxLen = 0",
      "  ",
      "  for (let right = 0; right < s.length; right++) {",
      "    const char = s[right]",
      "    // If duplicate found, move left pointer",
      "    if (char in charIndex && charIndex[char] >= left) {",
      "      left = charIndex[char] + 1",
      "    }",
      "    charIndex[char] = right",
      "    maxLen = Math.max(maxLen, right - left + 1)",
      "  }",
      "  return maxLen",
      "}",
      "```",
      "",
      "Walking through \"abcabcbb\":",
      "- right=0, s[0]='a': window='a', maxLen=1",
      "- right=1, s[1]='b': window='ab', maxLen=2",
      "- right=2, s[2]='c': window='abc', maxLen=3",
      "- right=3, s[3]='a': 'a' at index 0, move left to 1, window='bca', maxLen=3",
      "- right=4, s[4]='b': 'b' at index 1, move left to 2, window='cab', maxLen=3",
      "- And so on... final answer is 3",
      "",
      "## Key Patterns That Use Sliding Window",
      "",
      "1. **Longest/Shortest substring/subarray with property X** - Variable window with two pointers",
      "2. **Fixed-size window aggregation** - Fixed window, just slide",
      "3. **All subarrays satisfying condition** - Variable window, collect results",
      "4. **Permutation/anagram problems** - Track character frequencies with a window",
      "",
      "## Common Implementation Detail: Character Frequency Maps",
      "",
      "Many sliding window problems involve character counts. Use a hash map to track character frequencies, and use a condition variable (like `matched` count) instead of comparing maps every iteration.",
      "",
      "```javascript",
      "// Instead of comparing maps (slow)",
      "if (JSON.stringify(windowCount) === JSON.stringify(requiredCount)) { ... }",
      "",
      "// Use a counter (fast)",
      "let matched = 0  // how many chars have required frequency",
      "if (windowCount[char] === requiredCount[char]) matched++",
      "if (matched === Object.keys(requiredCount).length) { /* found */ }",
      "```"
    ].join('\n'),
    zh: [
      "## 滑动窗口核心想法",
      "",
      "滑动窗口是一个通过数据移动的矩形框，通常从左到右。与检查所有可能的子数组（O(n²)）不同，你维护一个窗口并智能滑动它。当窗口移动时，你增量更新其内部信息。",
      "",
      "魔法：重用上一个窗口的计算而不是从头重新计算。当右边界添加新元素时，添加其贡献。当左边界移除元素时，减去其贡献。这将O(n²)转化为O(n)。",
      "",
      "## 固定窗口大小模板",
      "",
      "当窗口大小恒定时，模式很简单：移动右边界，当窗口大小超过k时，移动左边界。",
      "",
      "```javascript",
      "function maxAverageSubarray(nums, k) {",
      "  let windowSum = 0",
      "  // 构建初始窗口[0, k-1]",
      "  for (let i = 0; i < k; i++) {",
      "    windowSum += nums[i]",
      "  }",
      "  let maxSum = windowSum",
      "  // 滑动窗口：右移，并删除左边元素",
      "  for (let right = k; right < nums.length; right++) {",
      "    windowSum += nums[right]         // 添加新元素",
      "    windowSum -= nums[right - k]     // 删除旧元素",
      "    maxSum = Math.max(maxSum, windowSum)",
      "  }",
      "  return maxSum / k",
      "}",
      "```",
      "",
      "**时间复杂度**：O(n) - 每个元素进入窗口一次，离开一次。",
      "",
      "## 可变窗口大小模板",
      "",
      "当窗口大小根据条件改变时，使用两个指针：左和右。通过移动右扩展窗口。当条件失败时，通过移动左收缩。",
      "",
      "```javascript",
      "function slidingWindowVariable(s, t) {",
      "  let left = 0",
      "  let windowCount = {}",
      "  let required = 0  // 我们需要多少个不同字符",
      "  let formed = 0    // 有多少个不同字符频率满足要求",
      "  let result = \"\"",
      "  ",
      "  for (let right = 0; right < s.length; right++) {",
      "    // 从右边添加字符",
      "    const char = s[right]",
      "    windowCount[char] = (windowCount[char] || 0) + 1",
      "    if (windowCount[char] === 1) formed++",
      "    ",
      "    // 尝试从左边收缩窗口",
      "    while (left <= right && /* 条件满足 */) {",
      "      // 如果这个窗口更好，更新结果",
      "      if (right - left + 1 < result.length) {",
      "        result = s.substring(left, right + 1)",
      "      }",
      "      // 从左边删除字符",
      "      const leftChar = s[left]",
      "      windowCount[leftChar]--",
      "      if (windowCount[leftChar] === 0) formed--",
      "      left++",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "## 展开vs收缩决策",
      "",
      "**何时展开（移动右）？**",
      "- 当你还未找到目标条件时",
      "- 当窗口\"不满足\"时",
      "",
      "**何时收缩（移动左）？**",
      "- 当条件满足且你想最小化窗口时",
      "- 当你有重复或多余元素时",
      "",
      "**示例：最长不含重复字符的子字符串**",
      "",
      "```javascript",
      "function lengthOfLongestSubstring(s) {",
      "  let left = 0",
      "  let charIndex = {}  // 每个字符最后出现的索引",
      "  let maxLen = 0",
      "  ",
      "  for (let right = 0; right < s.length; right++) {",
      "    const char = s[right]",
      "    // 如果找到重复，移动左指针",
      "    if (char in charIndex && charIndex[char] >= left) {",
      "      left = charIndex[char] + 1",
      "    }",
      "    charIndex[char] = right",
      "    maxLen = Math.max(maxLen, right - left + 1)",
      "  }",
      "  return maxLen",
      "}",
      "```",
      "",
      "逐步通过\"abcabcbb\"：",
      "- right=0, s[0]='a': 窗口='a', maxLen=1",
      "- right=1, s[1]='b': 窗口='ab', maxLen=2",
      "- right=2, s[2]='c': 窗口='abc', maxLen=3",
      "- right=3, s[3]='a': 'a'在索引0，左移到1，窗口='bca', maxLen=3",
      "- right=4, s[4]='b': 'b'在索引1，左移到2，窗口='cab', maxLen=3",
      "- 以此类推...最终答案是3",
      "",
      "## 使用滑动窗口的关键模式",
      "",
      "1. **最长/最短具有属性X的子字符串/子数组** - 可变窗口，两指针",
      "2. **固定大小窗口聚合** - 固定窗口，只需滑动",
      "3. **所有满足条件的子数组** - 可变窗口，收集结果",
      "4. **排列/字谜问题** - 用窗口追踪字符频率",
      "",
      "## 常见实现细节：字符频率映射",
      "",
      "许多滑动窗口问题涉及字符计数。使用哈希映射追踪字符频率，使用条件变量（如`matched`计数）而不是每次迭代比较映射。",
      "",
      "```javascript",
      "// 与其比较映射（慢）",
      "if (JSON.stringify(windowCount) === JSON.stringify(requiredCount)) { ... }",
      "",
      "// 使用计数器（快）",
      "let matched = 0  // 有多少个字符有所需频率",
      "if (windowCount[char] === requiredCount[char]) matched++",
      "if (matched === Object.keys(requiredCount).length) { /* 找到 */ }",
      "```"
    ].join('\n'),
  },
  leetcode: [
    { id: 76, title: 'Minimum Window Substring', titleZh: '最小覆盖子串', difficulty: 'Hard' },
    { id: 567, title: 'Permutation in String', titleZh: '字符串的排列', difficulty: 'Medium' },
    { id: 3, title: 'Longest Substring Without Repeating Characters', titleZh: '无重复字符的最长子串', difficulty: 'Medium' },
    { id: 438, title: 'Find All Anagrams in a String', titleZh: '找到字符串中所有字母异位词', difficulty: 'Medium' },
  ],
}
