import type { TopicContent } from '../../types'

export const twoPointers: TopicContent = {
  id: 'arrays-two-pointers',
  title: { en: 'Two Pointers Pattern', zh: '双指针模式' },
  description: { en: 'Master left-right pointers and fast-slow pointers for array problems', zh: '掌握左右指针和快慢指针解决数组问题' },
  timeEstimate: '40 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'twoPointers',
  content: {
    en: [
      "## The Two Pointers Pattern",
      "",
      "Two pointers is a technique where you maintain two indices moving through data. There are two main variations: left-right pointers and fast-slow pointers. Both exploit sorted order or specific problem properties to achieve O(1) or O(n) efficiency.",
      "",
      "## Left-Right Pointers Template",
      "",
      "Place one pointer at the start and one at the end. Move them towards each other based on a condition. This works when the array is sorted or when you're comparing elements from opposite ends.",
      "",
      "```javascript",
      "function twoPointersLR(arr) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left < right) {",
      "    if (/* condition */) {",
      "      left++",
      "    } else {",
      "      right--",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**Example: Valid Palindrome**",
      "",
      "```javascript",
      "function isPalindrome(s) {",
      "  s = s.toLowerCase().replace(/[^a-z0-9]/g, '')",
      "  let left = 0, right = s.length - 1",
      "  while (left < right) {",
      "    if (s[left] !== s[right]) return false",
      "    left++",
      "    right--",
      "  }",
      "  return true",
      "}",
      "```",
      "",
      "The key insight: instead of reversing the string (O(n) extra space), compare from both ends simultaneously (O(1) extra space).",
      "",
      "**Example: Container With Most Water**",
      "",
      "You have heights at different positions. Find two lines that together contain the most water. The container width is the distance between indices, height is the minimum of two lines.",
      "",
      "```javascript",
      "function maxArea(heights) {",
      "  let left = 0, right = heights.length - 1",
      "  let maxArea = 0",
      "  while (left < right) {",
      "    const width = right - left",
      "    const height = Math.min(heights[left], heights[right])",
      "    const area = width * height",
      "    maxArea = Math.max(maxArea, area)",
      "    // Move the pointer with smaller height",
      "    if (heights[left] < heights[right]) {",
      "      left++",
      "    } else {",
      "      right--",
      "    }",
      "  }",
      "  return maxArea",
      "}",
      "```",
      "",
      "Why move the smaller height? If we move the taller pointer, the new height can only be smaller or equal (limited by the shorter line), and width decreases. By moving the shorter pointer, we have a chance for a taller line to increase area.",
      "",
      "## Fast-Slow Pointers Template",
      "",
      "Both pointers move in the same direction, but at different speeds. One moves 1 step per iteration, the other moves 2 steps (or more). This is useful for finding cycles, midpoints, or removing duplicates.",
      "",
      "```javascript",
      "function fastSlowPointers(arr) {",
      "  let slow = 0, fast = 0",
      "  while (fast < arr.length) {",
      "    // Do something with slow pointer",
      "    slow++",
      "    // Fast pointer moves faster",
      "    fast += 2",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**Example: Remove Element In-Place**",
      "",
      "Given an array and a value, remove all occurrences and return the new length. Must do it in-place with O(1) extra space.",
      "",
      "```javascript",
      "function removeElement(nums, val) {",
      "  let slow = 0  // position to write next non-val element",
      "  for (let fast = 0; fast < nums.length; fast++) {",
      "    if (nums[fast] !== val) {",
      "      nums[slow] = nums[fast]",
      "      slow++",
      "    }",
      "  }",
      "  return slow  // first 'slow' elements are valid",
      "}",
      "```",
      "",
      "The slow pointer only advances when we find a non-val element, creating a \"compacted\" array. Fast pointer scans all elements.",
      "",
      "## Why Two Pointers Work",
      "",
      "Two pointers reduce the search space. In left-right: O(n) iterations with each solving a subproblem. In fast-slow: detecting cycles in O(n) that would otherwise require a hash table (O(n) space). The pattern trades one advantage for another - usually space for time or simplicity.",
      "",
      "## When to Use Two Pointers",
      "",
      "- Sorted array problems",
      "- Finding pairs with specific sum or ratio",
      "- In-place removal or partitioning",
      "- Detecting cycles in sequences or linked lists",
      "- Reversing or comparing from opposite ends"
    ].join('\n'),
    zh: [
      "## 双指针模式",
      "",
      "双指针是一种通过维护两个索引在数据中移动的技术。有两种主要变体：左右指针和快慢指针。两者都利用排序顺序或特定问题属性来实现O(1)或O(n)效率。",
      "",
      "## 左右指针模板",
      "",
      "在开始处放置一个指针，在末尾放置另一个。根据条件将它们移向彼此。这在数组排序或比较对立端元素时有效。",
      "",
      "```javascript",
      "function twoPointersLR(arr) {",
      "  let left = 0, right = arr.length - 1",
      "  while (left < right) {",
      "    if (/* 条件 */) {",
      "      left++",
      "    } else {",
      "      right--",
      "    }",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**示例：验证回文**",
      "",
      "```javascript",
      "function isPalindrome(s) {",
      "  s = s.toLowerCase().replace(/[^a-z0-9]/g, '')",
      "  let left = 0, right = s.length - 1",
      "  while (left < right) {",
      "    if (s[left] !== s[right]) return false",
      "    left++",
      "    right--",
      "  }",
      "  return true",
      "}",
      "```",
      "",
      "关键洞察：与其反转字符串（O(n)额外空间），不如从两端同时比较（O(1)额外空间）。",
      "",
      "**示例：盛最多水的容器**",
      "",
      "你有不同位置的高度。找两条线一起能盛最多水。容器的宽度是索引间距，高度是两条线的最小值。",
      "",
      "```javascript",
      "function maxArea(heights) {",
      "  let left = 0, right = heights.length - 1",
      "  let maxArea = 0",
      "  while (left < right) {",
      "    const width = right - left",
      "    const height = Math.min(heights[left], heights[right])",
      "    const area = width * height",
      "    maxArea = Math.max(maxArea, area)",
      "    // 移动较小高度的指针",
      "    if (heights[left] < heights[right]) {",
      "      left++",
      "    } else {",
      "      right--",
      "    }",
      "  }",
      "  return maxArea",
      "}",
      "```",
      "",
      "为什么移动较小的高度？如果我们移动较高指针，新高度只能更小或相等（受限于较短线），宽度减少。通过移动较短指针，我们有机会找到更高的线来增加面积。",
      "",
      "## 快慢指针模板",
      "",
      "两个指针向同一方向移动，但速度不同。一个每次迭代移动1步，另一个移动2步（或更多）。这对于找到循环、中点或删除重复很有用。",
      "",
      "```javascript",
      "function fastSlowPointers(arr) {",
      "  let slow = 0, fast = 0",
      "  while (fast < arr.length) {",
      "    // 用slow指针做某事",
      "    slow++",
      "    // 快指针移动更快",
      "    fast += 2",
      "  }",
      "  return result",
      "}",
      "```",
      "",
      "**示例：原地移除元素**",
      "",
      "给定一个数组和一个值，移除所有出现并返回新长度。必须原地进行，仅O(1)额外空间。",
      "",
      "```javascript",
      "function removeElement(nums, val) {",
      "  let slow = 0  // 写入下一个非val元素的位置",
      "  for (let fast = 0; fast < nums.length; fast++) {",
      "    if (nums[fast] !== val) {",
      "      nums[slow] = nums[fast]",
      "      slow++",
      "    }",
      "  }",
      "  return slow  // 前'slow'个元素有效",
      "}",
      "```",
      "",
      "slow指针仅在找到非val元素时前进，创建一个\"压缩\"的数组。fast指针扫描所有元素。",
      "",
      "## 双指针为什么有效",
      "",
      "双指针缩小搜索空间。在左右中：O(n)次迭代，每次解决子问题。在快慢中：检测循环用O(n)，否则需哈希表（O(n)空间）。该模式交换一个优势获得另一个——通常用空间换时间或简洁性。",
      "",
      "## 何时使用双指针",
      "",
      "- 排序数组问题",
      "- 找具有特定和或比率的配对",
      "- 原地移除或分区",
      "- 检测序列或链表中的循环",
      "- 从对立端反转或比较"
    ].join('\n'),
  },
  leetcode: [
    { id: 125, title: 'Valid Palindrome', titleZh: '验证回文串', difficulty: 'Easy' },
    { id: 167, title: 'Two Sum II - Input Array Is Sorted', titleZh: '两数之和 II - 输入有序数组', difficulty: 'Medium' },
    { id: 11, title: 'Container With Most Water', titleZh: '盛最多水的容器', difficulty: 'Medium' },
    { id: 15, title: '3Sum', titleZh: '三数之和', difficulty: 'Medium' },
  ],
}
