import type { TopicContent } from '../../types'

export const bubbleSortContent: TopicContent = {
  id: 'sorting-bubble-sort',
  title: { en: 'Bubble Sort', zh: '冒泡排序' },
  description: { en: 'Understand the simplest sorting algorithm and when it applies', zh: '理解最简单的排序算法及其何时应用' },
  timeEstimate: '25 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'bubbleSort',
  content: {
    en: [
      "## How Bubble Sort Works",
      "",
      "Bubble sort is the simplest sorting algorithm. It repeatedly steps through the array, compares adjacent elements, and swaps them if they're in the wrong order. Larger values \"bubble\" to the right end.",
      "",
      "## Algorithm",
      "",
      "```javascript",
      "function bubbleSort(arr) {",
      "  const n = arr.length",
      "  for (let i = 0; i < n - 1; i++) {",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]  // Swap",
      "      }",
      "    }",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "**Optimization:** The array gets more sorted with each pass. Once a pass makes no swaps, the array is sorted.",
      "",
      "```javascript",
      "function bubbleSortOptimized(arr) {",
      "  const n = arr.length",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let swapped = false",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]",
      "        swapped = true",
      "      }",
      "    }",
      "    if (!swapped) break  // Early exit if sorted",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "## Complexity Analysis",
      "",
      "| Metric | Value |",
      "|--------|-------|",
      "| Time (best) | O(n) with optimization |",
      "| Time (average) | O(n²) |",
      "| Time (worst) | O(n²) |",
      "| Space | O(1) - in place |",
      "| Stable | Yes |",
      "",
      "## Example: [5, 3, 8, 4, 2]",
      "",
      "```",
      "Pass 1: Compare adjacent, swap if needed",
      "  5>3: swap → [3, 5, 8, 4, 2]",
      "  5<8: no swap → [3, 5, 8, 4, 2]",
      "  8>4: swap → [3, 5, 4, 8, 2]",
      "  8>2: swap → [3, 5, 4, 2, 8]",
      "  (Largest element 8 is now at the end)",
      "",
      "Pass 2: (Ignore last element, now in position)",
      "  3<5: no swap → [3, 5, 4, 2, 8]",
      "  5>4: swap → [3, 4, 5, 2, 8]",
      "  5>2: swap → [3, 4, 2, 5, 8]",
      "  (Second largest 5 is in position)",
      "",
      "Continue until no swaps in a pass...",
      "Final: [2, 3, 4, 5, 8]",
      "```",
      "",
      "## Why Bubble Sort",
      "",
      "Bubble sort is rarely used in practice because faster algorithms (merge sort, quick sort) exist. However, it's excellent for:",
      "",
      "**When to use:**",
      "- Teaching sorting concepts (simplest to understand)",
      "- Nearly sorted arrays with optimization (O(n) best case)",
      "- Small datasets where simplicity matters more than speed",
      "- Educational demonstrations",
      "",
      "**When NOT to use:**",
      "- Large datasets (O(n²) is too slow)",
      "- Performance-critical code (use merge/quick sort)",
      "- General purpose sorting (use built-in sort)",
      "",
      "## Comparison with Other Simple Sorts",
      "",
      "| Algorithm | Time | Space | When |",
      "|-----------|------|-------|------|",
      "| Bubble | O(n²) | O(1) | Nearly sorted, teaching |",
      "| Selection | O(n²) | O(1) | When writes are expensive |",
      "| Insertion | O(n²) | O(1) | Nearly sorted, stable needed |",
      "",
      "## Key Properties",
      "",
      "- **In-place:** Only needs O(1) extra space",
      "- **Stable:** Preserves relative order of equal elements",
      "- **Adaptive:** Optimized version is O(n) on sorted data",
      "- **Simple:** No complex data structures or comparisons needed",
      "",
      "## Why It's Called \"Bubble\"",
      "",
      "Larger elements \"bubble\" to the right end with each pass, like bubbles rising in water. Similarly, smaller elements gradually move left."
    ].join('\n'),
    zh: [
      "## 冒泡排序如何工作",
      "",
      "冒泡排序是最简单的排序算法。它反复通过数组，比较相邻元素，如果顺序错误则交换。较大的值\"冒泡\"到右端。",
      "",
      "## 算法",
      "",
      "```javascript",
      "function bubbleSort(arr) {",
      "  const n = arr.length",
      "  for (let i = 0; i < n - 1; i++) {",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]  // 交换",
      "      }",
      "    }",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "**优化：**数组随每次遍历变得更有序。一旦遍历无交换，数组已排序。",
      "",
      "```javascript",
      "function bubbleSortOptimized(arr) {",
      "  const n = arr.length",
      "  for (let i = 0; i < n - 1; i++) {",
      "    let swapped = false",
      "    for (let j = 0; j < n - i - 1; j++) {",
      "      if (arr[j] > arr[j + 1]) {",
      "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]",
      "        swapped = true",
      "      }",
      "    }",
      "    if (!swapped) break  // 如果已排序提前退出",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "## 复杂度分析",
      "",
      "| 指标 | 值 |",
      "|------|-----|",
      "| 时间（最好） | O(n)有优化 |",
      "| 时间（平均） | O(n²) |",
      "| 时间（最坏） | O(n²) |",
      "| 空间 | O(1) - 原地 |",
      "| 稳定 | 是 |",
      "",
      "## 示例：[5, 3, 8, 4, 2]",
      "",
      "```",
      "遍历1：比较相邻，需要则交换",
      "  5>3: 交换 → [3, 5, 8, 4, 2]",
      "  5<8: 无交换 → [3, 5, 8, 4, 2]",
      "  8>4: 交换 → [3, 5, 4, 8, 2]",
      "  8>2: 交换 → [3, 5, 4, 2, 8]",
      "  (最大元素8现在在末尾)",
      "",
      "遍历2：（忽略最后元素，现在就位）",
      "  3<5: 无交换 → [3, 5, 4, 2, 8]",
      "  5>4: 交换 → [3, 4, 5, 2, 8]",
      "  5>2: 交换 → [3, 4, 2, 5, 8]",
      "  (第二大5就位)",
      "",
      "继续直到无遍历交换...",
      "最终：[2, 3, 4, 5, 8]",
      "```",
      "",
      "## 为什么用冒泡排序",
      "",
      "冒泡排序实际中很少使用，因为更快的算法（归并排序、快速排序）存在。然而，它擅长：",
      "",
      "**何时使用：**",
      "- 教排序概念（最易理解）",
      "- 近似排序数组有优化（O(n)最好情况）",
      "- 小数据集，简洁胜于速度",
      "- 教育演示",
      "",
      "**何时不使用：**",
      "- 大数据集（O(n²)太慢）",
      "- 性能关键代码（使用归并/快速排序）",
      "- 通用排序（使用内置排序）",
      "",
      "## 与其他简单排序比较",
      "",
      "| 算法 | 时间 | 空间 | 何时 |",
      "|------|------|------|------|",
      "| 冒泡 | O(n²) | O(1) | 近似排序，教学 |",
      "| 选择 | O(n²) | O(1) | 写入昂贵时 |",
      "| 插入 | O(n²) | O(1) | 近似排序，需稳定 |",
      "",
      "## 关键属性",
      "",
      "- **原地：**仅需O(1)额外空间",
      "- **稳定：**保留相等元素的相对顺序",
      "- **自适应：**优化版在排序数据上O(n)",
      "- **简单：**无需复杂数据结构或比较",
      "",
      "## 为什么叫\"冒泡\"",
      "",
      "较大元素\"冒泡\"到右端每遍历，像气泡在水中上升。类似地，较小元素逐渐向左移动。"
    ].join('\n'),
  },
  leetcode: [
    { id: 912, title: 'Sort an Array', titleZh: '排序数组', difficulty: 'Medium' },
  ],
}
