import type { TopicContent } from '../../types'

export const mergeSortContent: TopicContent = {
  id: 'sorting-merge-sort',
  title: { en: 'Merge Sort', zh: '归并排序' },
  description: { en: 'Master the divide-and-conquer algorithm with guaranteed O(n log n) and stable sorting', zh: '掌握分治算法，保证O(n log n)和稳定排序' },
  timeEstimate: '40 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'mergeSort',
  content: {
    en: [
      "## Divide and Conquer Paradigm",
      "",
      "Merge sort exemplifies divide-and-conquer:",
      "",
      "1. **Divide:** Split array into halves recursively until arrays of size 1",
      "2. **Conquer:** Merge two sorted subarrays into one sorted array",
      "3. **Combine:** Final result is a sorted array",
      "",
      "## Algorithm",
      "",
      "```javascript",
      "function mergeSort(arr) {",
      "  if (arr.length <= 1) return arr",
      "  ",
      "  const mid = Math.floor(arr.length / 2)",
      "  const left = mergeSort(arr.slice(0, mid))",
      "  const right = mergeSort(arr.slice(mid))",
      "  ",
      "  return merge(left, right)",
      "}",
      "",
      "function merge(left, right) {",
      "  const result = []",
      "  let i = 0, j = 0",
      "  ",
      "  while (i < left.length && j < right.length) {",
      "    if (left[i] <= right[j]) {",
      "      result.push(left[i++])",
      "    } else {",
      "      result.push(right[j++])",
      "    }",
      "  }",
      "  ",
      "  result.push(...left.slice(i))",
      "  result.push(...right.slice(j))",
      "  return result",
      "}",
      "```",
      "",
      "## Recursion Tree",
      "",
      "```",
      "For array [3, 1, 4, 1, 5]",
      "",
      "                [3,1,4,1,5]",
      "               /           \\",
      "           [3,1,4]         [1,5]",
      "          /        \\        /     \\",
      "        [3,1]     [4]    [1]    [5]",
      "       /     \\",
      "     [3]    [1]",
      "",
      "        Merge Phase",
      "     [1,3]      [4]",
      "           \\    /",
      "        [1,3,4]",
      "              \\    /",
      "        [1,1,3,4,5]",
      "```",
      "",
      "## Merge Operation",
      "",
      "The key insight: merging two sorted arrays is O(n).",
      "",
      "**Example:** merge([1, 3, 5], [2, 4])",
      "- Compare 1 vs 2: take 1 → [1]",
      "- Compare 3 vs 2: take 2 → [1, 2]",
      "- Compare 3 vs 4: take 3 → [1, 2, 3]",
      "- Compare 5 vs 4: take 4 → [1, 2, 3, 4]",
      "- Take remaining 5 → [1, 2, 3, 4, 5]",
      "",
      "## Complexity Analysis",
      "",
      "| Metric | Value |",
      "|--------|-------|",
      "| Time (all cases) | O(n log n) |",
      "| Space | O(n) |",
      "| Stable | Yes |",
      "| In-place | No |",
      "",
      "**Why O(n log n)?**",
      "- Each level of recursion: O(n) work (merging all arrays at that level)",
      "- Depth of recursion: log n (keep dividing by 2)",
      "- Total: O(n) × log n = O(n log n)",
      "",
      "## Stability",
      "",
      "Merge sort is stable: equal elements keep their original relative order.",
      "",
      "Example with objects: [(name: \"Alice\", score: 90), (name: \"Bob\", score: 90)]",
      "After sorting by score, Alice still comes before Bob (stable).",
      "",
      "This is because in merge, when `left[i] === right[j]`, we take from left first (preserving order).",
      "",
      "## Advantages",
      "",
      "- **Guaranteed O(n log n):** Worst case is same as average case",
      "- **Stable:** Preserves relative order of equal elements",
      "- **Predictable:** No worst-case degradation",
      "- **Works on linked lists:** Can sort linked lists efficiently without random access",
      "",
      "## Disadvantages",
      "",
      "- **O(n) extra space:** Need temporary array for merging",
      "- **Not in-place:** Extra memory requirement",
      "- **Slower in practice:** For small arrays, overhead makes it slower than quick sort",
      "",
      "## When to Use Merge Sort",
      "",
      "- Need guaranteed O(n log n) worst case",
      "- Stability is critical",
      "- Sorting linked lists",
      "- External sorting (sorting files larger than memory)",
      "- Parallel processing (can parallelize divide phase)",
      "",
      "## In-Place Merge Sort (Space-Optimized)",
      "",
      "Possible but complex. Requires careful merging in-place. Usually not worth the complexity.",
      "",
      "## Comparison with Quick Sort",
      "",
      "| Property | Merge | Quick |",
      "|----------|-------|-------|",
      "| Average time | O(n log n) | O(n log n) |",
      "| Worst time | O(n log n) | O(n²) |",
      "| Best time | O(n log n) | O(n log n) |",
      "| Space | O(n) | O(log n) |",
      "| Stable | Yes | No |",
      "| In-place | No | Yes |",
      "| Practice | Slower | Faster |",
      "",
      "Merge sort guarantees O(n log n) but uses extra space. Quick sort is faster in practice but can degrade. Choice depends on whether you need worst-case guarantee or extra space."
    ].join('\n'),
    zh: [
      "## 分治范例",
      "",
      "归并排序是分治的示例：",
      "",
      "1. **分：**递归地将数组分成一半，直到大小为1的数组",
      "2. **治：**合并两个排序的子数组为一个排序数组",
      "3. **合：**最终结果是排序数组",
      "",
      "## 算法",
      "",
      "```javascript",
      "function mergeSort(arr) {",
      "  if (arr.length <= 1) return arr",
      "  ",
      "  const mid = Math.floor(arr.length / 2)",
      "  const left = mergeSort(arr.slice(0, mid))",
      "  const right = mergeSort(arr.slice(mid))",
      "  ",
      "  return merge(left, right)",
      "}",
      "",
      "function merge(left, right) {",
      "  const result = []",
      "  let i = 0, j = 0",
      "  ",
      "  while (i < left.length && j < right.length) {",
      "    if (left[i] <= right[j]) {",
      "      result.push(left[i++])",
      "    } else {",
      "      result.push(right[j++])",
      "    }",
      "  }",
      "  ",
      "  result.push(...left.slice(i))",
      "  result.push(...right.slice(j))",
      "  return result",
      "}",
      "```",
      "",
      "## 递归树",
      "",
      "```",
      "对数组[3, 1, 4, 1, 5]",
      "",
      "                [3,1,4,1,5]",
      "               /           \\",
      "           [3,1,4]         [1,5]",
      "          /        \\        /     \\",
      "        [3,1]     [4]    [1]    [5]",
      "       /     \\",
      "     [3]    [1]",
      "",
      "        合并阶段",
      "     [1,3]      [4]",
      "           \\    /",
      "        [1,3,4]",
      "              \\    /",
      "        [1,1,3,4,5]",
      "```",
      "",
      "## 合并操作",
      "",
      "关键洞察：合并两个排序数组是O(n)。",
      "",
      "**示例：**合并([1, 3, 5], [2, 4])",
      "- 比较1 vs 2：取1 → [1]",
      "- 比较3 vs 2：取2 → [1, 2]",
      "- 比较3 vs 4：取3 → [1, 2, 3]",
      "- 比较5 vs 4：取4 → [1, 2, 3, 4]",
      "- 取剩余5 → [1, 2, 3, 4, 5]",
      "",
      "## 复杂度分析",
      "",
      "| 指标 | 值 |",
      "|------|-------|",
      "| 时间（所有情况） | O(n log n) |",
      "| 空间 | O(n) |",
      "| 稳定 | 是 |",
      "| 原地 | 否 |",
      "",
      "**为什么O(n log n)?**",
      "- 每个递归级别：O(n)工作（合并该级别所有数组）",
      "- 递归深度：log n（持续除以2）",
      "- 总计：O(n) × log n = O(n log n)",
      "",
      "## 稳定性",
      "",
      "归并排序稳定：相等元素保留原相对顺序。",
      "",
      "带对象的示例：[(name: \"Alice\", score: 90), (name: \"Bob\", score: 90)]",
      "按分数排序后，Alice仍在Bob前面（稳定）。",
      "",
      "这是因为在合并中，当`left[i] === right[j]`时，我们先从左取（保留顺序）。",
      "",
      "## 优点",
      "",
      "- **保证O(n log n)：**最坏情况与平均情况相同",
      "- **稳定：**保留相等元素的相对顺序",
      "- **可预测：**无最坏情况降级",
      "- **适用链表：**可无随机访问高效排序链表",
      "",
      "## 缺点",
      "",
      "- **O(n)额外空间：**需临时数组合并",
      "- **非原地：**额外内存需求",
      "- **实际较慢：**对小数组，开销使其比快速排序慢",
      "",
      "## 何时使用归并排序",
      "",
      "- 需要保证O(n log n)最坏情况",
      "- 稳定性关键",
      "- 排序链表",
      "- 外部排序（排序大于内存的文件）",
      "- 并行处理（可并行化分割阶段）",
      "",
      "## 原地归并排序（空间优化）",
      "",
      "可能但复杂。需谨慎原地合并。通常不值得复杂性。",
      "",
      "## 与快速排序比较",
      "",
      "| 属性 | 归并 | 快速 |",
      "|------|-------|-------|",
      "| 平均时间 | O(n log n) | O(n log n) |",
      "| 最坏时间 | O(n log n) | O(n²) |",
      "| 最好时间 | O(n log n) | O(n log n) |",
      "| 空间 | O(n) | O(log n) |",
      "| 稳定 | 是 | 否 |",
      "| 原地 | 否 | 是 |",
      "| 实际 | 较慢 | 较快 |",
      "",
      "归并排序保证O(n log n)但使用额外空间。快速排序实际更快但可退化。选择取决于是否需要最坏情况保证或额外空间。"
    ].join('\n'),
  },
  leetcode: [
    { id: 912, title: 'Sort an Array', titleZh: '排序数组', difficulty: 'Medium' },
    { id: 315, title: 'Count of Smaller Numbers After Self', titleZh: '计算右侧小于当前元素的个数', difficulty: 'Hard' },
  ],
}
