import type { TopicContent } from '../../types'

export const quickSortContent: TopicContent = {
  id: 'sorting-quick-sort',
  title: { en: 'Quick Sort', zh: '快速排序' },
  description: { en: 'Master the most practical sorting algorithm with pivot selection and partition logic', zh: '掌握最实用的排序算法，掌握支点选择和分割逻辑' },
  timeEstimate: '45 min',
  contentType: 'all',
  hasVisualizer: true,
  visualizerKey: 'quickSort',
  content: {
    en: [
      "## Quick Sort Core Idea",
      "",
      "Quick sort is a divide-and-conquer algorithm that:",
      "1. **Selects a pivot** element",
      "2. **Partitions** the array: elements < pivot go left, > pivot go right",
      "3. **Recursively sorts** left and right partitions",
      "",
      "The key difference from merge sort: quick sort does the hard work during partition, not during merge.",
      "",
      "## Algorithm",
      "",
      "```javascript",
      "function quickSort(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    const pi = partition(arr, low, high)",
      "    quickSort(arr, low, pi - 1)",
      "    quickSort(arr, pi + 1, high)",
      "  }",
      "  return arr",
      "}",
      "",
      "function partition(arr, low, high) {",
      "  const pivot = arr[high]  // Choose last element as pivot",
      "  let i = low - 1",
      "  ",
      "  for (let j = low; j < high; j++) {",
      "    if (arr[j] < pivot) {",
      "      i++",
      "      [arr[i], arr[j]] = [arr[j], arr[i]]  // Swap",
      "    }",
      "  }",
      "  [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]]  // Place pivot",
      "  return i + 1",
      "}",
      "```",
      "",
      "## Partition Visualization",
      "",
      "**Example:** Array [3, 7, 2, 5, 1, 8, 4], pivot = 4 (last element)",
      "",
      "```",
      "Start:        [3, 7, 2, 5, 1, 8, 4]  pivot=4, i=-1",
      "",
      "j=0, arr[0]=3 < 4: i=0, swap → [3, 7, 2, 5, 1, 8, 4]",
      "j=1, arr[1]=7 ≥ 4: no action",
      "j=2, arr[2]=2 < 4: i=1, swap → [3, 2, 7, 5, 1, 8, 4]",
      "j=3, arr[3]=5 ≥ 4: no action",
      "j=4, arr[4]=1 < 4: i=2, swap → [3, 2, 1, 5, 7, 8, 4]",
      "j=5, arr[5]=8 ≥ 4: no action",
      "",
      "Place pivot at i+1=3: [3, 2, 1, 4, 7, 8, 5]",
      "Pivot (4) is now in final position!",
      "Return 3 (pivot index)",
      "",
      "Left partition [3, 2, 1], Right partition [7, 8, 5]",
      "```",
      "",
      "## Pivot Selection Strategies",
      "",
      "The pivot choice dramatically affects performance:",
      "",
      "**1. Last element (simple but risky)**",
      "```javascript",
      "const pivot = arr[high]",
      "```",
      "Worst case: sorted array with last element as pivot → O(n²)",
      "",
      "**2. Random element (good on average)**",
      "```javascript",
      "const randomIndex = low + Math.floor(Math.random() * (high - low + 1))",
      "const pivot = arr[randomIndex]",
      "```",
      "Avoids worst case on sorted data",
      "",
      "**3. Median-of-three (practical)**",
      "```javascript",
      "const first = arr[low]",
      "const middle = arr[Math.floor((low + high) / 2)]",
      "const last = arr[high]",
      "const pivot = median(first, middle, last)",
      "```",
      "Good balance between simplicity and avoiding worst case",
      "",
      "## Complexity Analysis",
      "",
      "| Metric | Value | When |",
      "|--------|-------|------|",
      "| Time (best/avg) | O(n log n) | Good pivot selection |",
      "| Time (worst) | O(n²) | Bad pivot (sorted array with naive pivot) |",
      "| Space | O(log n) | Recursion stack (average depth) |",
      "| Stable | No | Elements with same key may reorder |",
      "| In-place | Yes | Only O(log n) extra space |",
      "",
      "## Why Quick Sort in Practice",
      "",
      "Despite O(n²) worst case, quick sort is faster than merge sort in practice because:",
      "- **In-place:** No extra array allocation",
      "- **Cache friendly:** Works on contiguous memory",
      "- **Average case:** O(n log n) with good pivot selection",
      "- **Simple:** Minimal overhead compared to merge sort",
      "",
      "## Avoiding Worst Case",
      "",
      "Always use a good pivot selection strategy:",
      "",
      "```javascript",
      "function quickSortRandom(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    // Randomize pivot to avoid worst case on sorted data",
      "    const randomIndex = low + Math.floor(Math.random() * (high - low + 1))",
      "    [arr[randomIndex], arr[high]] = [arr[high], arr[randomIndex]]",
      "    const pi = partition(arr, low, high)",
      "    quickSortRandom(arr, low, pi - 1)",
      "    quickSortRandom(arr, pi + 1, high)",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "## Stability",
      "",
      "Quick sort is **not stable** because of in-place partition. If stability is critical, use merge sort.",
      "",
      "## When to Use Quick Sort",
      "",
      "- General purpose sorting (it's the standard)",
      "- Arrays where extra space is limited",
      "- When average O(n log n) is acceptable",
      "- When cache locality matters",
      "",
      "## When NOT to Use Quick Sort",
      "",
      "- Must guarantee O(n log n) worst case (use merge sort)",
      "- Stability is critical (use merge sort)",
      "- Highly adversarial input (use random pivot or heap sort)",
      "",
      "## Comparison: Quick Sort vs Merge Sort",
      "",
      "Quick sort is faster in practice due to better cache locality and no extra array. Merge sort guarantees O(n log n) worst case. Most libraries use hybrid approaches (intro sort) that start with quick sort and switch to heap sort if recursion depth gets too deep."
    ].join('\n'),
    zh: [
      "## 快速排序核心想法",
      "",
      "快速排序是分治算法，：",
      "1. **选择支点**元素",
      "2. **分割**数组：元素 < 支点走左，> 支点走右",
      "3. **递归排序**左右分割",
      "",
      "与归并排序的关键区别：快速排序在分割时做艰难工作，不在合并时。",
      "",
      "## 算法",
      "",
      "```javascript",
      "function quickSort(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    const pi = partition(arr, low, high)",
      "    quickSort(arr, low, pi - 1)",
      "    quickSort(arr, pi + 1, high)",
      "  }",
      "  return arr",
      "}",
      "",
      "function partition(arr, low, high) {",
      "  const pivot = arr[high]  // 选择最后元素为支点",
      "  let i = low - 1",
      "  ",
      "  for (let j = low; j < high; j++) {",
      "    if (arr[j] < pivot) {",
      "      i++",
      "      [arr[i], arr[j]] = [arr[j], arr[i]]  // 交换",
      "    }",
      "  }",
      "  [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]]  // 放置支点",
      "  return i + 1",
      "}",
      "```",
      "",
      "## 分割可视化",
      "",
      "**示例：**数组[3, 7, 2, 5, 1, 8, 4]，支点 = 4（最后元素）",
      "",
      "```",
      "开始：        [3, 7, 2, 5, 1, 8, 4]  支点=4，i=-1",
      "",
      "j=0，arr[0]=3 < 4：i=0，交换 → [3, 7, 2, 5, 1, 8, 4]",
      "j=1，arr[1]=7 ≥ 4：无动作",
      "j=2，arr[2]=2 < 4：i=1，交换 → [3, 2, 7, 5, 1, 8, 4]",
      "j=3，arr[3]=5 ≥ 4：无动作",
      "j=4，arr[4]=1 < 4：i=2，交换 → [3, 2, 1, 5, 7, 8, 4]",
      "j=5，arr[5]=8 ≥ 4：无动作",
      "",
      "在i+1=3放置支点：[3, 2, 1, 4, 7, 8, 5]",
      "支点(4)现在在最终位置！",
      "返回3（支点索引）",
      "",
      "左分割[3, 2, 1]，右分割[7, 8, 5]",
      "```",
      "",
      "## 支点选择策略",
      "",
      "支点选择极大影响性能：",
      "",
      "**1. 最后元素（简单但有风险）**",
      "```javascript",
      "const pivot = arr[high]",
      "```",
      "最坏情况：排序数组最后元素为支点 → O(n²)",
      "",
      "**2. 随机元素（平均很好）**",
      "```javascript",
      "const randomIndex = low + Math.floor(Math.random() * (high - low + 1))",
      "const pivot = arr[randomIndex]",
      "```",
      "避免排序数据最坏情况",
      "",
      "**3. 三数中值（实用）**",
      "```javascript",
      "const first = arr[low]",
      "const middle = arr[Math.floor((low + high) / 2)]",
      "const last = arr[high]",
      "const pivot = median(first, middle, last)",
      "```",
      "简洁和避免最坏情况的好平衡",
      "",
      "## 复杂度分析",
      "",
      "| 指标 | 值 | 何时 |",
      "|------|-----|------|",
      "| 时间（最好/平均） | O(n log n) | 好支点选择 |",
      "| 时间（最坏） | O(n²) | 坏支点（排序数组幼稚支点） |",
      "| 空间 | O(log n) | 递归栈（平均深度） |",
      "| 稳定 | 否 | 相同键元素可能重排 |",
      "| 原地 | 是 | 仅O(log n)额外空间 |",
      "",
      "## 为什么在实际中快速排序",
      "",
      "尽管O(n²)最坏情况，快速排序比归并排序快实际上因为：",
      "- **原地：**无额外数组分配",
      "- **缓存友好：**在连续内存工作",
      "- **平均情况：**好支点选择O(n log n)",
      "- **简单：**与归并排序相比最小开销",
      "",
      "## 避免最坏情况",
      "",
      "总使用好支点选择策略：",
      "",
      "```javascript",
      "function quickSortRandom(arr, low = 0, high = arr.length - 1) {",
      "  if (low < high) {",
      "    // 随机支点以避免排序数据最坏情况",
      "    const randomIndex = low + Math.floor(Math.random() * (high - low + 1))",
      "    [arr[randomIndex], arr[high]] = [arr[high], arr[randomIndex]]",
      "    const pi = partition(arr, low, high)",
      "    quickSortRandom(arr, low, pi - 1)",
      "    quickSortRandom(arr, pi + 1, high)",
      "  }",
      "  return arr",
      "}",
      "```",
      "",
      "## 稳定性",
      "",
      "快速排序**不稳定**因为原地分割。如果稳定性关键，用归并排序。",
      "",
      "## 何时使用快速排序",
      "",
      "- 通用排序（它是标准的）",
      "- 额外空间有限的数组",
      "- 平均O(n log n)可接受",
      "- 缓存局部性重要",
      "",
      "## 何时不使用快速排序",
      "",
      "- 必须保证O(n log n)最坏情况（用归并排序）",
      "- 稳定性关键（用归并排序）",
      "- 高度对抗输入（用随机支点或堆排序）",
      "",
      "## 比较：快速排序vs归并排序",
      "",
      "快速排序实际更快因为更好缓存局部性和无额外数组。归并排序保证O(n log n)最坏情况。大多库用混合方法（内省排序），开始快速排序，如果递归深度太深切换到堆排序。"
    ].join('\n'),
  },
  leetcode: [
    { id: 912, title: 'Sort an Array', titleZh: '排序数组', difficulty: 'Medium' },
    { id: 215, title: 'Kth Largest Element in an Array', titleZh: '数组中的第K个最大元素', difficulty: 'Medium' },
  ],
}
